### ISSUE TITLE
XML Sitemap - Add support for multiple languages

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#102]
Our XML sitemap needs to support translation plugins such as Polylang and qTranslate X.  

The XML sitemap should include the correct URLs for all translated content with the correct URL structure, i.e. http://mydomain.com/fr/hello-world/

We should generate a separate XML sitemap for each language, i.e. an XML sitemap for English content, and a different XML sitemap for French content.

**Comment by wpsmort** [comment]
Results of testing with Polylang v2.1.4:

Our XML Sitemap and Sitemap Indexes works fine in the URL settings in Polylang is set to "The language is set from different domains".  However, it does not work if the URL settings in Polylang is set to the following:

1). The language is set from the directory name in pretty permalinks - The XML Sitemap should appear at the sub directory URL but it does not (i.e mydomain.com/en/sitemap.xml or mydomain.com/fr/sitemap.xml).  

2). The language is set from the subdomain name in pretty permalinks - With this setting we get the Unsafe attempt to load URL http://stevemortiboy.com/sitemap.xsl error.

We should fix these two issues so that our sitemap works with all URL settings in Polylang.

**Comment by wpsmort** [comment]
Results of testing with qTranslate X v3.4.6.8:

Our XML Sitemap and Sitemap Indexes works fine in the URL settings in qTranslate X is set to either "Use Pre-Path Mode (domain.com/en/)" or "Use Per-Domain mode".  However, it does not work if the URL settings in qTranslate X is set to the following:

1). Use Query Mode (domain.com?lang=en) - With this setting we get a 404 (Not Found) for the XSL stylesheet.

2). Use Pre-Domain Mode (en.domain.com) - With this setting we  get the Unsafe attempt to load URL http://stevemortiboy.com/sitemap.xsl error.  It also looks like the URLs on the sitemap are incorrect.

We should fix these two issues so that our sitemap works with all URL settings in qTranslate X.

**Comment by wpsmort** [comment]
Note from #2131:

Currently we create different sitemaps for each language. We do this regardless of whether the translated content is in subdirectories, subdomains or their own domains.

For sites where translated content is in subdirectories, Google recommends including every language variation for each URL in the same sitemap. Here is Google's article about this - https://support.google.com/webmasters/answer/189077?hl=en

We should look at implementing this and ensuring compatibility with WPML, Polylang, qTranslate and any other translation plugin we are compatible with.

There's a good article about this here - https://wplang.org/sitemaps-multiple-languages-wordpress/

**Comment by wpsmort** [comment]
See also #941 for Polyang support

**Comment by wpsmort** [comment]
This has been moved to our feature request system.

**Comment by Ajilis** [comment]
Hi,
i dont understand very well activity on this post.
Seems all issues for multilanguage plugin :

#941 for Polyang support
#2795 for GTranslate
#2956 for TranslatePress support

were closed , exact ?

**Comment by wpsmort** [comment]
As it says above, we've moved these to our new feature request system.

**Comment by Ajilis** [comment]
ok thanx , its you're internal tool for managing feature request ?

**Comment by wpsmort** [comment]
Yes, this is currently an internal tool for handling all feature requests and votes for new features.

**Comment by Ajilis** [comment]
Any news of this ?

**Comment by arnaudbroes** [comment]
> Any news of this ?

Not yet.

**Comment by yrxwin** [comment]
Any news of this?

**Comment by Ajilis** [comment]
For me i have desactived sitemap in the plugin , now in the core of WP sitemap are OK and compatible with polylang

**Comment by grubioloIxiam** [comment]
Hello @wpsmort. Do you have any news on this issue? I am currently translating the website with Polylang and the sitemap is not generated for all languages.

Has anyone solved it with another method?

**Comment by grubioloIxiam** [comment]
Hello @wpsmort . Do you have any news on this issue? I am currently translating the website with Polylang and the sitemap is not generated for all languages.

Has anyone solved it with another method?

**Comment by grubioloIxiam** [comment]
> For me i have desactived sitemap in the plugin , now in the core of WP sitemap are OK and compatible with polylang

Hello @Ajilis . I do not understand. Have you stopped generating the sitemap with all-in-one seo? Do you generate it statically?

**Comment by arnaudbroes** [comment]
@grubioloIxiam we only integrate from our side with WPML. However, we've added all the "infrastructure" that is required for other multilingual plugins to integrate with our plugin from their end.

So, if you'd like for Polylang to integrate with us so that we can generate a multilingual sitemap, then I would recommend you to reach out to their team. You can pass this documentation onto them which details what they'd need to integrate - https://aioseo.com/docs/localizing-aioseo-data-via-the-translations-api/
