### ISSUE TITLE
Move and remove force rewrites option

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1061]
Reference https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/894#issuecomment-299555077 
Probably, it's been long enough that we don't need to do a database migration... there's no reason everyone shouldn't have a setting in the performance module for this (make sure that's always the case).
We can most likely just remove the "option" in aioseop_class, then change the code to access it in the performance module as needed.

In #1059 we simply covered it up with a CSS rule, so we'll want to remove that too.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #769](https://github.com/awesomemotive/aioseop-pro/issues/769) via [**ZenHub**](https://www.zenhub.com/)
