### ISSUE TITLE
Social Meta module - Posts Object Type (post) is being displayed by default

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#1068]
The Posts Object Type (post) drop down is displayed even if no checkboxes are checked under Social Meta > Facebook Settings > Enable Facebook Meta for Post Types.

That drop down should only be displayed if Posts is checked.  

See screenshot:

<img width="769" alt="screen shot 2017-08-09 at 3 29 36 pm" src="https://user-images.githubusercontent.com/17548525/29140195-a393a636-7d17-11e7-968e-c6b04b5bce37.png">

**Comment by arnaudbroes** [comment]
@wpsmort 
I tested this with two different, fresh local test sites and a few versions of WordPress (ranging from 4.8.1 to 4.0) and All in One SEO Pack and it seems that this behaviour has been there since the launch of the Social Meta module with version 2.1.0. Good catch.

**Comment by michaeltorbert** [comment]
This goes away if/when we remove these checkboxes.

**Comment by wpsmort** [comment]
This should go away in the redesign.
