### ISSUE TITLE
Social Meta Module - Add support for controlling which size image is used for og:image

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#107]
By default, we should be using the full size image as the og:image although this needs to be confirmed.  

We should have a drop down where the user can select which image size (https://codex.wordpress.org/Settings_Media_Screen#Image_sizes) they want to use as the og:image.  This would accommodate users who have created custom image sizes.

**Comment by contactashish13** [comment]
@wpsmort Is this related to #260?

**Comment by wpsmort** [comment]
@contactashish13 This issue is about adding an option in the UI where users can set which image size they want to use.  Rather than adding an option in the UI, perhaps we should start with a filter where users can set the image size that is used.

**Comment by contactashish13** [comment]
@wpsmort I have already created a PR for #260 where I have added a filter, that's why I felt both are related.
