### ISSUE TITLE
Social meta is not output when SEO on only these post types are unchecked

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#1070]
If you uncheck the box for a post type under General Settings > Custom Post Type Settings > SEO on only these post types but check that post type box under Social Meta > Facebook Settings > Enable Facebook Meta for Post Types then edit a post, you'll see the AIOSEOP meta box with only the Social Settings tab and you can complete the fields, however, nothing is output to the source code.

Steps to reproduce:
1. Go to General Settings > Custom Post Type Settings > SEO on only these post types and uncheck all the boxes
2. Go to Social Meta > Facebook Settings > Enable Facebook Meta for Post Types and check all the boxes
3. Edit a post and verify you see the AIOSEOP meta box for Social Settings
4. Complete the fields in the Social Settings and update the post
5. View the source code.  There should be nothing output from AIOSEOP, not even the green HTML comment line

**Comment by arnaudbroes** [comment]
@wpsmort
I tested this with two different, fresh local test sites and a few versions of WordPress (ranging from 4.8.1 to 4.0) and All in One SEO Pack and it seems that this behaviour has been there since the launch of the Social Meta module with version 2.1.0.

**Comment by michaeltorbert** [comment]
What do we want this behavior to be?

1) Social tab shows up, and social SEO shows up in the source code also?
2) Social tab doesn't show up?
3) There's no separate option for Social SEO per post type, and it just goes off the one in general settings?
4) ?

**Comment by arnaudbroes** [comment]
@michaeltorbert 
Option three is the most logical imo. What does @wpsmort think?

**Comment by wpsmort** [comment]
@michaeltorbert I agree with @arnaudbroes that we should just have one option to control whether AIOSEOP is active on a post type or taxonomy (Pro) and that one option should control both the SEO and Social Settings tabs.  We can have a filter if users was to disable OG meta.

**Comment by wpsmort** [comment]
This should go away in the redesign.
