### ISSUE TITLE
Social Meta Module - Add Filter to Control default OG image for each post type

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#108]
We currently only have one default og:image field (http://semperplugins.com/documentation/social-meta-module/#default-og-image).  Users have requested that we have an advanced option where they can select different default images for each post type.

**Comment by michaeltorbert** [comment]
I see the value in this but I think it's still a bit of an edge case and would just be clutter for 99.9% of users. 
We should make a filter for it. The variable is dimg.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #780](https://github.com/awesomemotive/aioseop-pro/issues/780) via [**ZenHub**](https://www.zenhub.com/)
