### ISSUE TITLE
Broken XML Sitemap filter for additional pages

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1113]
#Reported here:

https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/progamatically-adding-pages-to-the-sitemap-using-aiosp_sitemap_addl_pages/

Our filter hook aiosp_sitemap_addl_pages at https://semperplugins.com/documentation/aiosp_sitemap_addl_pages/ doesn't seem to work (although aiosp_sitemap_addl_pages_only does).

From looking at the code, it looks like it adds it to /sitemap_addl.xml which I think only exists when indexes are turned on. We should update the documentation.

**Comment by michaeltorbert** [comment]
Update.. looks like it adds it to:
 'addl' === $sitemap_type

**Comment by wpsmort** [comment]
I've updated the documentation for this filter.
