### ISSUE TITLE
Add to API documentation how to remove metaboxes

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1117]
For example, for certain roles:
https://wordpress.org/support/topic/remove-meta-box-for-authors/#post-9231056

Improve the API as needed.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #755](https://github.com/awesomemotive/aioseop-pro/issues/755) via [**ZenHub**](https://www.zenhub.com/)
