### ISSUE TITLE
images in sitemap should be included in documentation and product page

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1162]
https://github.com/semperfiwebdesign/semperpluginstore/issues/390
https://github.com/semperfiwebdesign/semperpluginstore/issues/391

**Comment by michaeltorbert** [comment]
Once this is done, I recommend change the links from github to our documentation in the sfwd and sp release histories.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #753](https://github.com/awesomemotive/aioseop-pro/issues/753) via [**ZenHub**](https://www.zenhub.com/)
