### ISSUE TITLE
XML Sitemap - Full size image for sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1202]
When we include an image in the xml sitemap, make sure it's the full size image.

**Comment by contactashish13** [comment]
@michaeltorbert @arnaudbroes PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1350

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #920](https://github.com/awesomemotive/aioseop-pro/issues/920) via [**ZenHub**](https://www.zenhub.com/)
