### ISSUE TITLE
Taxonomy formats should mirror post formats

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1211]
apply_tax_title_format only has 6 macros, but it should have the same ones from post/page

Why do we even have separate functions for this?

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #846](https://github.com/awesomemotive/aioseop-pro/issues/846) via [**ZenHub**](https://www.zenhub.com/)
