### ISSUE TITLE
Privacy settings warning

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1226]
In the sitemap module we have the following warning:

"Warning: your privacy settings are configured to ask search engines to not index your site; you can change this under Reading Settings for your blog."

This seems like a unnecessary duplicate of the admin notice we also have.

**Comment by EkoJr** [comment]
Looks like code that can be consolidated #43

**Comment by michaeltorbert** [comment]
@EkoJr Yes, but I was specifically referring to this https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/modules/aioseop_sitemap.php#L702 as a duplicate of an existing admin notice.

**Comment by EkoJr** [comment]
It looks like this is it...

![notice](https://user-images.githubusercontent.com/2794445/32529173-d29ae3ac-c3eb-11e7-8aa9-1bbea242b006.png)

**Comment by michaeltorbert** [comment]
@EkoJr Right. I meant that it can be removed, since the other one should be showing at the top of all pages in wp-admin anyway.

**Comment by EkoJr** [comment]
Fixed / Removed
https://github.com/EkoJr/all-in-one-seo-pack/commit/311489ae6a9967e4c91e74d6625f4dd3fa310119
