### ISSUE TITLE
XML Sitemap - Sitemap generated log message appears when activating plugin

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#1241]
When testing PRs for v2.4.1 I saw the log message that says the sitemap was generated after activating the plugin.  This is new in v2.4.1.

**Comment by michaeltorbert** [comment]
We need to know what version this started with.

**Comment by michaeltorbert** [comment]
@arnaudbroes Can you see what commit this started with?
