### ISSUE TITLE
Internal deep linking

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1289]
Requested via email by Nick (as "suggested links"), as well as many others. 

Similar to Yoast (premium only?) or SEO Ultimate.

Also make sure this supports Chinese.

**Comment by EkoJr** [comment]
This may be an idea that I've slowly been expanding on, and may be the same thing.

* WP Websites with AIOSEOP to cross communicate.
* NOT to be confused with only just the Multi-site. However, a Prototype could start with Multi-site.
* Avoid Keyword Spamming. It’s intended as an assistant when creating/editing content. 
  * Spamming may have worked in the past, but google also considers the quality of the link as well. It is very important to avoid what could turn into abuse.
* Similar to the Hyperlink Search function.
  * Add other websites to a search list.
* May want to reserve for future. 
  * For cross-site linking, the biggest worry is version compatibility across multiple plugin installations.
  * WP has pushed auto-updates for WP Core, but did not for themes and plugins. Which would help force bug fixes if it was possible.

**Comment by wpsmort** [comment]
This has been moved to our feature request system.
