### ISSUE TITLE
Cornerstone content

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1290]
Requested via email by Nick.

Resource: https://www.elegantthemes.com/blog/tips-tricks/how-to-identify-cornerstone-articles-in-wordpress

We should review how site structure helps with this and what ways AIOSEOP can help…
Anything marked as “cornerstone” should be high up the list of suggested links… we should weight suggested links:

cornerstone label
same category (figure out how to deal with hierarchies)
same tags
same meta keywords
similar words in content/title meta/desc meta/etc (we can probably fine some help in other plugins for this)
same images

See also - https://alienwp.com/cornerstone-content/

**Comment by wpsmort** [comment]
I have moved this to our feature request system.
