### ISSUE TITLE
Exclude Pages option not working for titles

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#1304]
As reported by Albert Belzer (belzer9@gmail.com) on October 14, 2017.

In his original e-mail, Albert states that both the "Disable SEO for this post/page option" setting on the Edit screen and the "Exlude Pages" setting in the General Settings are not working.

**Comment by arnaudbroes** [comment]
I'm going to look whether I can trace this down.

**Comment by michaeltorbert** [comment]
Ok so here is the relevant code: https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/5f978e35b467db9ca35b9d08d97fd5f79afaadcd/inc/aioseop_functions.php#L751

I would have figured that it would accept the slug and/or the post id. In reality, it looks like it takes whatever is in the option, and looks to see if that is in the URL. So it's essentially the slug (or post id if you have permalinks turned off), but really it's the path.

We can discuss if we want to change this or not. Either way we should improve the documentation.

**Comment by michaeltorbert** [comment]
Update: after rereading the report, looks like this IS broken for titles.

**Comment by wpsmort** [comment]
This should be resolved in the v4 architecture.
