### ISSUE TITLE
Expand documentation for Exclude Pages setting

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#1305]
Expand the documentation for the Exclude Pages setting that's part of the Advanced Settings.
https://semperplugins.com/documentation/all-in-one-seo-pack-advanced-settings/#exclude-pages

Related to #1304.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #754](https://github.com/awesomemotive/aioseop-pro/issues/754) via [**ZenHub**](https://www.zenhub.com/)
