### ISSUE TITLE
Make documentation more clear for XML sitemap caching exclusion

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#1307]
https://semperplugins.com/documentation/excluding-the-xml-sitemap-from-caching/

We should update the documentation with screenshots and make a bit more clear.
One of our users confused the Peformance menu of W3 Total Cache with the Performance menu from All in One SEO Pack Pro.

https://semperplugins.com/support/optimizing-all-in-one-seo-pack-pro/excluding-the-xml-sitemap-from-caching/#p7076

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #750](https://github.com/awesomemotive/aioseop-pro/issues/750) via [**ZenHub**](https://www.zenhub.com/)
