### ISSUE TITLE
Delete Unused Functions in All_in_One_SEO_Pack_Module

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#1323]
This is in relation to #1156 

The two unused are...
* `All_in_One_SEO_Pack_Module::help_text_helper()`
* `All_in_One_SEO_Pack_Module::add_help_text_links`

After the updated code with the Help Text/Tooltips. These two functions are no longer being used after applying the concept in a different class ( `AIOSEOP_Helper` ) . I've ran some test and breakpoints, and don't see it being applied in any functional way.

The only implementation it has is an IF statement that is always false. However, it is a Class Variable isset check, and if any external code implements this (ex. like the **PRO** version might). Then there may be issues that surface.

This will likely need to be reviewed before approving deletion.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #794](https://github.com/awesomemotive/aioseop-pro/issues/794) via [**ZenHub**](https://www.zenhub.com/)
