### ISSUE TITLE
Data Importer - Add taxonomy term meta

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1331]
_"We successfully migrated SEO meta title, description etc. from Yst for pages and products.
But when it comes to product categories, settings are not migrated from Yst."_

Requested by Marko.

**Comment by michaeltorbert** [comment]
BTW All these others are related 
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20import%20

**Comment by michaeltorbert** [comment]
Also, we do have a copy of the Yst WooCommerce addon if needed.

**Comment by contactashish13** [comment]
@michaeltorbert i have configured a couple of products along with product categories. When I try to analyze the import I see the below. I'm not sure if this is correct. Will it mention that 2 products are being imported?

![image](https://user-images.githubusercontent.com/12953439/32414095-9973dd4c-c245-11e7-9cff-42347f87bcef.png)

**Comment by michaeltorbert** [comment]
You have to have metadata entered to import for the product.

**Comment by michaeltorbert** [comment]
@contactashish13 You have to have metadata entered to import for the product.

**Comment by contactashish13** [comment]
@michaeltorbert I did save the metadata on a few posts but I'm not sure how this works. Any steps to replicate would be great

**Comment by michaeltorbert** [comment]
Requested here https://semperplugins.com/support/configuring-all-in-one-seo-pack-pro/woocommerce-product-category-migration-from-yoast/

**Comment by michaeltorbert** [comment]
This is a tricky one. Taxonomy meta is only supported in Pro, however, we can still import it in free.

**Comment by arnaudbroes** [comment]
Requested by info@goinkjet.co.uk.

**Comment by wpsmort** [comment]
We have an issue for this in another repo.
