### ISSUE TITLE
Description placeholder text not counted in character count

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1352]

**Comment by michaeltorbert** [comment]
<img width="774" alt="screen shot 2017-11-09 at 8 57 31 am" src="https://user-images.githubusercontent.com/17364998/32608976-0e95527a-c52c-11e7-82a8-8fe24522884a.png">
<img width="767" alt="screen shot 2017-11-09 at 8 57 09 am" src="https://user-images.githubusercontent.com/17364998/32608977-0ea3cb2a-c52c-11e7-8549-8392b96e50f6.png">

**Comment by bostmaguy** [comment]
I'm having the same problem but the character count shows up after I save or publish but the count is wrong! And if I edit the description after I save or publish, it still won't accurately count the characters. Also happens with the Title as well.

**Comment by wpsmort** [comment]
This was fixed a while back.
