### ISSUE TITLE
General - Hide private post types

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1373]
Reported here: https://wordpress.org/support/topic/seo-on-only-these-post-types-lists-posts-multiple-times/#post-9703235

We should determine if this is intentional or not.

> It seems AIOSEO is displaying ALL post types, even the ones that have public disabled. The function to return a sites post types normally excludes these post types 
 https://codex.wordpress.org/Function_Reference/get_post_types). We don’t provide our custom post types any labels because public is disabled and they are not exposed to the UI at all. They are for internal use and we reference them using the slugs. So in this use case, AIOSEO is pulling our private post types, then simply displaying ‘Posts’ since they do not have a label defined.

**Comment by EkoJr** [comment]
In regards to AIOSEOP, everything functions as it should. Contact Form by WPForms on the other hand was written very loosely. Most of which, has little to no labels used, which in turn defaults to 'post' labels.

Even though the author says he has the CPTs set to private ( public = false ). WordPress says from their own codex.

> While the default settings of $exclude_from_search, $publicly_queryable, $show_ui, and $show_in_nav_menus are inherited from public, each does not rely on this relationship and controls a very specific intention.

https://developer.wordpress.org/reference/functions/register_post_type/

**Comment by jaredatch** [comment]
In the next release we have defined a labels, so that should at least avoid the confusion of having multiple "Posts" display - at least from our plugin.

I don't know if I'd go as far as not defining labels for an internal post type as loose though 😆 I've seen that from other plugins as well. If a developer registers a post type that has no UI, export, etc (by all counts, should be invisible) I think its understandable that they may omit the label.

This is how we are registering our post type:

```
'public'  => false,
'exclude_from_search'  => true,
'show_ui'  => false,
'show_in_admin_bar'  => false,
'rewrite'  => false,
'query_var' => false,
'can_export' => false,
```

There is literally nothing more we can do in the arguments to tell WordPress that this post type has no UI and is not accessible via conventional means. 😁

I mean I'm fine with our private post types showing up in the AIOSEO settings, I'm just playing devils advocate here.

**Comment by EkoJr** [comment]
That is true, many plugins do the same...but at the same time, some of those can easily become error prone.

I was just skimming over the issue, and noticed there were only a few lines of code to register post types; which felt like a bit of a surprise at the time, but perhaps I was just being too strict about it. I had a simular issue with an internal post type. In regards to `public` settings, this is what I used...

```
'public'                => true,
'exclude_from_search'   => true,
'publicly_queryable'    => false,
// Shows up in admin area.
'show_ui'               => false,
'show_in_menu'          => false,
'show_in_nav_menus'     => false,
'show_in_admin_bar'     => false,
```

I believe not filling in variables, risks the chance of something else filling in the gaps, so I normally try to avoid it if I can.

Impressive plugin btw.

**Comment by michaeltorbert** [comment]
@jaredatch Thanks for following up. 
I wouldn't call it "loose" on your part, I'd just say there's an unfortunate clash between two awesome plugins that can make things confusing for mutual our users. :)
This is something we should and will resolve on our end, and as you said you'll take care of it on yours too.

**Comment by michaeltorbert** [comment]
Unless anyone can think of any reason why we should include private post types we should probably do this. 
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L3136

Three things to think about
a) Are there any circumstances why we'd want to include private post types?
b) Should we look into a filter hook to override?
c) We probably no longer have to manually remove revision, nav_menu_item, custom_css, and customize_changeset in https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L3138

**Comment by wpsmort** [comment]
Replaced by this issue - https://github.com/awesomemotive/aioseop-pro/issues/705
