### ISSUE TITLE
XML Sitemap - Wrong behavior on multisite context

### ISSUE THREAD

**Issue by jeremydenoun** [awesomemotive/all-in-one-seo-pack#1399]
I found a bug or a weird behavior with WP multisite context on sitemap generation :

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/350b32f77003910051a4614abf03c5a85101556f/modules/aioseop_sitemap.php#L647

- the url_path isn't a correct way to find right rewrite regexp by example if wordpress is located in /wordpress/ URL_PATH value is wordpress/{filename}.xml and this don't match {filename}.xml
- this can be fixed with some solution like removing home_url base or basename path or find another way to find correct rewrite

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/350b32f77003910051a4614abf03c5a85101556f/modules/aioseop_sitemap.php#L2621

- in multi-site context permalink doesn't contain hostname, this isn't valid for a correct sitemap
- this can be fixed with something like
```
+                    if (is_multisite()) {
+                        $url_parts = wp_parse_url( aioseop_home_url() );
+                        $url = $url_parts['scheme'] . '://' . $url_parts['host'];
+                    }
```

**Comment by contactashish13** [comment]
@michaeltorbert I tested this and was unable to replicate either problem. All seems to work well.

**Comment by jeremydenoun** [comment]
For reproduce issue, you can follow this step :
1) setup a clean WP install
2) setup a multi-site and 2 site look like :
`blog.com/blog1
  blog.com/blog2`
3) setup aiosp with sitemap plugin
4) try to check result

**Comment by wpsmort** [comment]
This is no longer an issue and must have been fixed in a previous release.  We've had no other reports of this either.
