### ISSUE TITLE
Replace Google OAuth code with new OAuth 2.0

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#140]
In version 2.1 of All in One SEO Pack we added a Connect with Google Analytics button to the Google Settings section of the General Settings screen.  Users could click on this button and it would ask them to authenticate with their Google account and we could then pull their Google Analytics tracking ID and populate that in the Google Analytics ID field.  See screenshot below.

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14332211/6c56ca0a-fc16-11e5-9a9f-e9ac07d6e74e.png)

This button used Google's OAuth and was removed last year when Google deprecated OAuth.  I believe the code is still in our plugin but commented out.

Google replaced OAuth with Google+ Sign-In.  We now need to replace our Google OAuth code with new code that works with Google+ Sign-In - https://developers.google.com/+/web/api/rest/auth-migration#timetable  

The goal is for users to be able to easily connect All in One SEO Pack to their Google account so that we can then fetch information from tools such as Google Analytics and Google Webmaster Tools.  There are a number of other plugins that do this including Yoast SEO and Google Analytics Dashboard for WP.

**Comment by michaeltorbert** [comment]
We should revisit this in light of G+ shutting down soon.

**Comment by wpsmort** [comment]
The new connection method is OAuth 2.0 detailed here - https://developers.google.com/identity/protocols/OAuth2
