### ISSUE TITLE
Bug - No OG:image radio button selected when custom image is removed

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1400]
Reported by Eric D via email.

We should try to reproduce this and determine under what conditions it happens. For instance, does the problem occur immediately after saving, a day later, after some other event?

**Comment by EkoJr** [comment]
The only instance I've been able to reproduce this is when Adding/Removing the Custom Image.

Adding a custom image, it was expected to select the Custom Image instead. 

However, removing the custom image resulted in nothing selected, even when an alternate image ( Non-Custom Image ) was selected selected.

Removing a Custom Image, I believe would need a check for what image is selected, and a fallback to default.

**Comment by arnaudbroes** [comment]
I'll check this again to see if there are any other cases that trigger this.

**Comment by arnaudbroes** [comment]
I wasn't able to find any other ways to reproduce this besides the one @EkoJR found. @EkoJR suggested we add a check and then a fallback but this is already happening as far as the actual source code is concerned; but not the UI. I guess we could just add a bit of JavaScript that selects the radio button for the default user image when the custom OG:image field is blank and when no other image is selected.

**Comment by wpsmort** [comment]
This should go away with the redesign.
