### ISSUE TITLE
Add a Post Data object/class

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#1413]
This is to organize code by creating a separate object; which most of the variables and functions reside in file: `aioseop_class.php` class: `All_in_One_SEO_Pack`. So, many of the functions and concepts are already created, and will just need to be migrated over, but how data is being stored within the database will need to be closely watched/noted.

To load post variables with All in One SEO Pack plugin, an example would look something like this...

```
$aopseop_post = new AIOSEOP_Post_Metadata( $id:int || $slug:string );
$title = $aopseop_post->post_title;
$seo_name = $aioseop->seo_title;
```

WP variables could be added to the class, but probably only if it is required.

## Project Milestones
This could probably be set into different phases. For the most part, it appears to be mainly code migration.

* Phase 1 - Class Construction (Soft)
Move variables and functions to a classes marked for the intended purpose.
* Phase 2 - Class Implementations & Conversions (Hard)
Anything that might be intense or break a site. Hopefully this is little to none.
Pre-phase: Could add preparation for a Final Phase.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #792](https://github.com/awesomemotive/aioseop-pro/issues/792) via [**ZenHub**](https://www.zenhub.com/)
