### ISSUE TITLE
Code Refactor - Add Admin Class

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#1414]
Using the Boilerplace as an example, create an Admin class to handle core admin functionality, and rendering admin pages.

A few things that it may contain.

* Check User Role / `is_admin`.
* Admin Enqueue Scripts and Styles.
* Metabox register & add.
* Handle Post Actions (Save Post)/ Transitions. ( possibly better as an Editor class ).
* Menu register & add.

## Module Structure ( Inheritance )

This might be a future enhancement to further organize code.

Following a similar concept with the current module structure may help since many of the settings pages share the same UI functionality, and it would provide consistency with the plugin as a whole.

However, I would lean towards the module/inherent structure being separate from the core/init admin class.

**Comment by EkoJR** [comment]
This will need to be postponed to a later version. There's a few related issues I've been running against, mainly with the db options #3010, and they way classes are initiated with the module_manager #1516.

The aioseop_options ( in wp_options ) is currently encapsulated into the module(s) and complicates access to the methods. The options are also tied into the render variables, and defaults are loosely written. Seeing how public & admin share some of the same code, it would be safer to create a seperate object that the two can access, as well as any other code; including access to `global $aioseop_options`.

The module_manager was another issue I had workaround, and how classes were being initialized. Initialization occurs with the `feature_manager` to get active modules, and `aioseop_class` also occurs separately. Initialization need to be better centralized, and there's a core class to migrate some of the initialize operations in `aioseop_class`.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #791](https://github.com/awesomemotive/aioseop-pro/issues/791) via [**ZenHub**](https://www.zenhub.com/)
