### ISSUE TITLE
Add Post Editor class for Post Actions

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#1415]
This would be part of code organization, and possibly part of Add Admin Class #1414.

It is intended mainly to handle the actions with Post Transitions and/or AJAX, or anything that involves the Post Editor and the plugin.

* Post Transitions.
* AJAX.
* Process Input (sanitation & esc).

Most of the code could reside in the main admin class or aioseop_class.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #790](https://github.com/awesomemotive/aioseop-pro/issues/790) via [**ZenHub**](https://www.zenhub.com/)
