### ISSUE TITLE
XML Sitemap - Automatically submit sitemaps to Google Search Console via API

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1456]
Is this something we can do with their API, given the proper credentials?

**Comment by tonyzeoli** [comment]
Sites ADD -
https://developers.google.com/webmaster-tools/search-console-api-original/v3/sites/add


Sitemaps SUBMIT -
https://developers.google.com/webmaster-tools/search-console-api-original/v3/sitemaps/submit

That's just two of a bunch of API actions that can happen - you can sort
out the rest on those pages if needed.

[image: photo]
Tony Zeoli
Founder, Digital Strategy Works LLC
A  310 Roxbury Pl, Arden NC 28704
O  (828) 412-0990  <(828) 412-0990> M  (917) 705-4700  <(917)
705-4700> E  az@digitalstrategyworks.com
<az@digitalstrategyworks.com>
W  https://digitalstrategyworks.com
Whatsapp 9177054700
Skype tonyzeoli

<http://www.facebook.com/digitalstrategyworks>
<http://www.twitter.com/dswks>
<http://www.linkedin.com/company/digital-strategy-works>
<http://plus.google.com/digitalstrategyworks>
<https://linkedin.com/in/+tonyzeoli>
<https://facebook.com/digitalstrategyworks> <https://twitter.com/dswks>
<https://digitalstrategyworks.com/how-developers-are-getting-wordpress-theme-development-wrong/2016/05/25/1816/>
From
the blog:How developers are getting WordPress theme development wrong
<https://digitalstrategyworks.com/how-developers-are-getting-wordpress-theme-development-wrong/2016/05/25/1816/>

**Comment by wpsmort** [comment]
Also do this for Bing, Baidu and Yandex (as per #424)

**Comment by wpsmort** [comment]
Moved to our feature request system.
