### ISSUE TITLE
Sub-menu link 'Upgrade to Pro' disappears when (De-)Activating modules

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#1463]
To reproduce this issue...

1. Go to 'Feature Manager'.
2. Activate or deactivate any module.

The Sub-menu 'Upgrade to Pro' disappears in the Admin Menu.

**Before**
![menu-before-ajax](https://user-images.githubusercontent.com/2794445/34782662-4632322e-f5de-11e7-8b39-ee931cf63a9a.png)

**After**
![menu-after-ajax](https://user-images.githubusercontent.com/2794445/34782668-4a99e15e-f5de-11e7-901d-2d729f17f410.png)

## Additional Info

The function for the menu seems to be `aioseop_ajax_get_menu_links()` located in `...\wp-content\plugins\all-in-one-seo-pack\inc\aioseop_functions.php`

**Comment by wpsmort** [comment]
This should be resolved in the v4 architecture.
