### ISSUE TITLE
Improve control of the description text under Home Title and Home Description fields

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#1464]
Whilst working on #1395 we found that you cannot change the wording under the Home Description without it affecting the Home Title as well.  There should be more independent control of this wording.  

The text we need to control for the two fields is this:

"Most search engines use a maximum of 320 chars for the home description."

The code is in admin/aioseop_module_class.php

**Comment by EkoJr** [comment]
The root issue seems to be Located in `All_in_One_SEO_Pack_Module::get_option_html()`

```
if ( isset( $options['count_desc'] ) ) {
	$count_desc = $options['count_desc'];
} else {
	$count_desc = __( ' characters. Most search engines use a maximum of %s chars for the %s.', 'all-in-one-seo-pack' );
}
```

Which appears to set the output at `All_in_One_SEO_Pack::get_post_description()`

Also, here are a few ideas I had....

* Change the description from a database variable to a static variable string instead.
    * Might even be able to change to a static string in the function itself.
* Remove database check, and just use the function's method.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #847](https://github.com/awesomemotive/aioseop-pro/issues/847) via [**ZenHub**](https://www.zenhub.com/)
