### ISSUE TITLE
Improve aioseop_description filter operations

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#1474]
There is a mixture of double negatives and interesting concepts that make the code rather perplexing, and suspiciously error prone.

* Apply Filter sends `empty( $aioseop_options['aiosp_dont_truncate_descriptions'] )`. Which will be false when a variable is set, and true when not in use. See *Ref 1.*
    * *Possible Solution*: Send `$aioseop_options['aiosp_dont_truncate_descriptions']` variable instead of empty().
    * Redundant if there is a global variable.
    * Seems error prone, but has been set elsewhere; as a string instead of a boolean.
    * Makes *not/prevent* truncating difficult when making a custom filter.
* $aioseop_options['aiosp_dont_truncate_descriptions'] uses a double negative. See *Ref 2.*
    * *Possible Solution*: Changing to `$aioseop_options['aiosp_truncate_descriptions']` would be easier, but flips operations.
    * Flips the coding style.

### Ref. 1

Located in `All_in_One_SEO_Pack` class
```
$description = apply_filters(
	'aioseop_description',
	$description,
	empty( $aioseop_options['aiosp_dont_truncate_descriptions'] )
);
```

### Ref. 2

Located in `All_in_One_SEO_Pack` class
```
public function filter_description( $value, $truncate = false ) {
	/*
	 * Doing stuff...
	 */

	// Truncate / crop
	if ( ! empty( $truncate ) && $truncate )
		$value = $this->trim_excerpt_without_filters( $value );
	// Encode to valid SEO html entities
	return $this->seo_entity_encode( $value );
}
```

This seems like it may need a **new filter**, and/or a **major update**. Since it would potentially change operations for websites using 2 variables in a filter. However, those using 1 variable in the filter hook shouldn't be affected.

Some of the functionality connected to this include...

* Post Description.
* OG Description.
* Google Snippet example ( in Edit Posts ).

**Comment by wpsmort** [comment]
The aioseop_description filter does need to be separated out so there is a filter for the SEO description and a filter for the OG description.  See discussion in #1470.

**Comment by wpsmort** [comment]
See also #1869

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #797](https://github.com/awesomemotive/aioseop-pro/issues/797) via [**ZenHub**](https://www.zenhub.com/)
