### ISSUE TITLE
Add support for Custom Post Type archives

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#154]
Add support for Custom Post Type archives
http://wordpress.org/support/topic/archive-title-not-being-rewritten

**Comment by michaeltorbert** [comment]
Also reported here https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/custom-post-type-meta/#p5641

**Comment by michaeltorbert** [comment]
Maybe related to #409

**Comment by michaeltorbert** [comment]
We have an option for this in advanced CPT support, though it doesn't seem to be doing anything for regular CTPs, and certainly not for Woo products.

**Comment by michaeltorbert** [comment]
@wpsmort I've installed version 2.2.4.1 and this doesn't work for me using the "advanced" option for CPT archive titles in General Settings.

It was first introduced much earlier (2.0.something?) and modified a lot in various versions.

Can you see if it ever worked?

**Comment by michaeltorbert** [comment]
Ok so basically it looks like we have code checking for CPT archive format but no way to store it that I can see. It probably makes more sense than having a format to just have where they can enter it somewhere in the UI... we should discuss how best to do this.

**Comment by wpsmort** [comment]
@michaeltorbert The first release where this worked properly was 2.2.3.  It's worked only based on the Archive Title Format field.  There has never been a separate field for each custom post type archive title format.

**Comment by wpsmort** [comment]
@michaeltorbert The code snippet provided for the user who wanted to edit titles and descriptions on custom post type archive pages is not working. I tested it and could not get it to work either.  Here is the code snippet - https://gist.github.com/michaeltorbert/e3ec9b78d7ac0ab282ab723d4869950f#file-gistfile1-txt

**Comment by michaeltorbert** [comment]
Update: the code snippet was missing the first add_filter. It works now.

**Comment by michaeltorbert** [comment]
https://wordpress.org/support/topic/add-description-and-keyword-in-cpt-archive/

**Comment by wpsmort** [comment]
https://wordpress.org/support/topic/no-seo-options-in-archive-template-for-custom-post-type/

**Comment by kickbk** [comment]
Same as @wpsmort social meta tags are missing in custom post type archive templates

**Comment by arnaudbroes** [comment]
Reported again here - https://wordpress.org/support/topic/change-page-post-title-to-meta-value-or-taxonomy/#post-12178690

I'm going to move this up to 3.5 since this has been requested a few times now.

**Comment by wpsmort** [comment]
Moved to the Pro repo.

**Comment by sporkman** [comment]
> Moved to the Pro repo.

I'm a Pro user, does this mean the feature is implemented or that it's just attached to a new milestone? If the latter, can you share what release this would be in?

**Comment by arnaudbroes** [comment]
@sporkman It's not implemented yet; we moved the feature request over to another repository. We'll definitely add this at some point although we don't have a milestone for this yet.

**Comment by naimanispayman** [comment]
I'd like to add my voice to this...
