### ISSUE TITLE
XML Sitemap - Add support for images in NextGen galleries

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#1546]
In Issue #1191 we added support for images in the built in WordPress galleries. We now need to add support for images in galleries and albums in the popular NextGen Gallery plugin.

**Comment by contactashish13** [comment]
@wpsmort This has already been done as #1230 was originally to support both.

**Comment by wpsmort** [comment]
@contactashish13 I tested PR #1279 and it does not detect images in NextGen galleries.

**Comment by contactashish13** [comment]
@wpsmort have fixed this. 

I've labeled this as needs unit tests because the unit test is incomplete and will require much more digging into the NGG code for it to be complete.
