### ISSUE TITLE
not compatible with enfold Versión: 3.5.4

### ISSUE THREAD

**Issue by mbanyuls** [awesomemotive/all-in-one-seo-pack#1547]
I'm using Enfot theme version: Versión: 3.5.4 and is not compatible with your plugin.
Could you help me please?

**Comment by michaeltorbert** [comment]
@mbanyuls Can you give more details about the problem? Is it the same as this? https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2120

**Comment by wpsmort** [comment]
I'm closing this as we don't have any more details or any other reports of this problem.
