### ISSUE TITLE
Undefined index notice in sitemap file

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1551]
Reported here: https://wordpress.org/support/topic/xml-sitemap-error-15/

> line 5:
> Notice: Undefined index: host in /var/www/html/public/plugins/all-in-one-seo-pack/modules/aioseop_sitemap.php on line 1995

In addition to checking the index before using it, we should look and see why it's empty in the first place. Looks like it's $_SERVER['HTTP_HOST']

**Comment by wpsmort** [comment]
Closing this as we don't have steps to reproduce and we've had no other reports of this notice.
