### ISSUE TITLE
i18n - Make illegal license notification translatable

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1583]

**Comment by arnaudbroes** [comment]
Should go into the common strings file.

**Comment by michaeltorbert** [comment]
Will need to test this works pre-release.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #771](https://github.com/awesomemotive/aioseop-pro/issues/771) via [**ZenHub**](https://www.zenhub.com/)
