### ISSUE TITLE
General - Default SEO/social to enabled for all post types

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1584]
This would probably supersede other issues, including #667 and #590.

Is there any reason SEO should be disabled for a public post type? We may want to consider removing all the checkboxes, and just leaving it on for all.

If we do this, we'd want to consider whether to respect old settings. My vote on that is not to unless we can think of a reason why we should. It seems like more people would benefit from this, who don't know they need to go manually enable it on two settings pages.

We could then add a simple API filter hook to remove unwanted post types from SEO.

If we do this, we'd need to add an issue in Pro for taxonomies.

**Comment by arnaudbroes** [comment]
I think that's a great idea. Removing all the checkboxes in the General Settings/Social Meta menus will result in less confusion for our users.

**Comment by wpsmort** [comment]
I agree.  We should default this to on for all new installs and current users.  We have a similar issue open for this - #68.

**Comment by EkoJr** [comment]
> Is there any reason SEO should be disabled for a public post type? 

Yes, some plugins use CPTs ( Custom Post Types ) to store their data, and some data may also be useless ( possibly also sensitive data ). Which could undesirable.

In the case of APL ( Advanced Post List ), I added 2 CPTs, which allows using some of the built in features of WordPress; most notably the cache. It is publicly rendered, but it isn't necessarily public data. So, there is no need for SEO, and only adds a metabox; which may also be undesirable for a number of other plugins.

I do agree it would decrease confusion.  Considering other plugins though, I worry how large the implications might be.

**Comment by contactashish13** [comment]
I agree with @EkoJr's point about CPTs but it will remove a lot of confusion for users for sure.

**Comment by michaeltorbert** [comment]
Presumably those plugins with useless or sensitive data stored as CPTs would be false == public (we may need to fine tune this a bit), which would be excluded.

**Comment by EkoJr** [comment]
Not necessarily. Some plugins are public and rendered by the plugin according to its format, but have little to no need for SEO. 

Another note, `public` also breaks down to `$exclude_from_search`, `$publicly_queryable`, `$show_ui`, and `$show_in_nav_menus`; which can be fine tuned by the plugin author(s), but is often limited in its configuration. So, more often than none, the CPT is set to public in order for the plugin to function.

There was the thought of having a method to manage which plugins are SEO enabled/disabled (or a filter), but something like that would seem to have a large amount of responsibility and implications needed.

**Comment by michaeltorbert** [comment]
I'd think it's best to err on the side of providing SEO meta unnecessarily (where it can be removed) than to not provide it.

**Comment by michaeltorbert** [comment]
We do need to make sure this doesn't change anything for existing sites.

**Comment by wpsmort** [comment]
I discussed this with Michael and we agreed to push this out to 3.4.  

The only way to do this is to swap the logic throughout the plugin so that wherever we check for which post types are checked, we swap this to check for which are unchecked, and vice versa.

Note that in the database we store the option as this:

aiosp_cpostactive {
	i:0;s:4:"post";
	i:1;s:4:"page";
}
