### ISSUE TITLE
Quick-Settings for various wp-admin locations

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#1585]
Would be intended as smaller save functions, or function.

Some quick-save options could include...
* Turning on SEO for a post type while viewing the add/edit-post screen or all posts screen.
    * Adding or removing general setting features & OG settings.
* Admin Warning notifications with click-to-change setting.
    * For example: Sitemap index warning to change max amount per page. Instead of navigating to settings page.

**Comment by michaeltorbert** [comment]
Good ideas, although I'd say these are unrelated to each other. :)

**Comment by EkoJr** [comment]
They could possibly be made into separate issues. I believe I was mostly reflecting on the functionality. Sort of a semi-dynamic and smaller save_settings function. Then added a couple examples to help imagine the concept (although, I do like the ideas).
