### ISSUE TITLE
Action links on Plugins page

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#159]
Ddd a break for the All in One SEO Pack action links URL's on the WP Plugins page so that the Plugin Descriptions are not pushed so far right.

https://wordpress.org/support/topic/action-links-on-plugins-page?replies=2#post-8248003

**Comment by michaeltorbert** [comment]
This is a reference to #160 by @Ed-AITpro 
@wpsmort What are your thoughts? My main concern is its scalability for mobile.

Before:
![screen shot 2016-04-19 at 6 48 29 pm](https://cloud.githubusercontent.com/assets/17364998/14658140/c7d5fe70-065f-11e6-9051-9089a3537e9b.png)

After:
![screen shot 2016-04-19 at 6 48 15 pm](https://cloud.githubusercontent.com/assets/17364998/14658135/c433f222-065f-11e6-9acb-020193498b8a.png)

**Comment by Ed-AITpro** [comment]
![aio-action-links](https://cloud.githubusercontent.com/assets/18339306/14659492/5dc52d98-0651-11e6-999d-561f0e12a5ef.jpg)

**Comment by Ed-AITpro** [comment]
Oh and by the way the whiner who would not let this go switched to another SEO plugin just because of this silly thing.  Jeez seriously???

**Comment by wpsmort** [comment]
@michaeltorbert I am fine with this.

**Comment by Ed-AITpro** [comment]
Yep me too. I said my good byes to that troublesome ex-customer. ;)

**Comment by michaeltorbert** [comment]
The problem with just inserting a br is that it doesn't scale for mobile. (Which currently is fine.)
The only thing I can think of is that we'd need to extend the WP_List_Table class and insert a CSS id for just our plugin by rewriting the code that generates the surrounding div. That's not really a good option either.
@Ed-AITpro  I'm open to other suggestions.

**Comment by Ed-AITpro** [comment]
@michaeltorbert when you say "it doesn't scale for mobile", what exactly are you saying/seeing?  How would I test that?  I looked at things with the Google Chrome dev tools mobile device emulator and my actual mobile devices and things looked ok to me visually, but I agree about one thing - using a basic br does not look good in general.  ie hackish/not sophisticated.  So yeah doing something more sophisticated like WP Toolbar classes (example code below) does would not look hackish.  I have never tried messing around with adding a class to Action Links so I do not know if WP even allows that.  The 2 CSS properties that come to mind off the top of my head would be wordwrap or max-width.

```
	$admin_bar->add_menu( array(
        'id'    => 'aitpro-video-tutorials',
        'title' => 'Video Tutorials',
       	'href'  => 'http://forum.ait-pro.com/video-tutorials/', 
        'meta'  => array(
            'title' => __('Video Tutorials'),            
            'class' => 'aitpro_adminbar_videos_menu_class'    
        ),
```

**Comment by michaeltorbert** [comment]
@Ed-AITpro 

As you scale down to mobile, the br isn't appropriate anymore (since it already wraps the text) and makes it look worse than it currently does on mobile (which is currently fine).
There's no way via hook to add a css class or id to the action row. Without more investigation, I don't know any other way than to make a (php) class to extend the WP_List_Table class and overwrite the function that generates it. This wouldn't be a great solution for a variety of reasons.

There could be another solution I'm missing though.

**Comment by Ed-AITpro** [comment]
Ok I think i see what you are saying.  When I resized my Browser the Responsive scaling does affect text wrapping differently than allowing the normal resize "wrap".  Not sure if this is even worth doing, but logically it seems like you would need some conditional code and then display Action Links code based on mobile or Browser size.  ie if mobile... 

https://codex.wordpress.org/Function_Reference/wp_is_mobile
```
if ( wp_is_mobile() ) {
	/* Display and echo mobile specific stuff here */
}
```
this is hackish and is just supposed to be a general idea.  if Browser size...
```
<script type="text/javascript">
  <!--
  if (screen.width <= 800) {
    //
  }
  //-->
</script>
```

**Comment by michaeltorbert** [comment]
That would probably work, but seems like it's not worth it for the extra checks.

**Comment by Ed-AITpro** [comment]
My thoughts exactly.  So I guess wait and see if a significant number of people complain about this later on. Although in my experience even the smallest minute things set people off and I hate hearing that crap from Users.  ;)  ie yes your plugin does every under the sun perfectly, EXCEPT I am trashing everything about your plugin because of this X ridiculous insignificant thing.  I am currently working on changing several things in my plugin because I get tired of hearing those ridiculous minute detail complaints from Users. ;)

**Comment by michaeltorbert** [comment]
There's been exactly one person complain about it in all these years. ;)

There is one other possibility. That div doesn't have a css id, but it does have a unique "data-slug". Possibly we could use javascript to identify it by that and change the css properties for the div? That may be a less bad way than the other 3 methods we've discussed so far.

**Comment by michaeltorbert** [comment]
http://html5doctor.com/html5-custom-data-attributes/

**Comment by Ed-AITpro** [comment]
Yeah where this is 1 there is 1,000 that are not saying anything publicly.  Recently I started asking people about things instead of waiting for them to say something and the feedback I got was suprising.  I was assuming only a couple of people did not like something because only a couple of people were saying anything about it publicly. So I have learned a couple things:  1.  the more you improve something the higher the bar you have set for that something. The complaints become less significant, but I guess you will always get complaints no matter how much you improve something.  2. Ask for feedback (even though you risk irritating folks) and don't wait for feedback.  ;)  I don't ask for feedback from "free" plugin users for obvious reasons and only ask my premium plugin customers for feedback. ;)

Yep that sounds like a much more clean/sophisticated method.

**Comment by michaeltorbert** [comment]
Agreed, most people don't say anything... which isn't a good thing of course... we love ANY constructive feedback, ESPECIALLY negative so we can get better.

Feel free to contribute the change to github if you like. ;)
Very soon, we'll have a page (similar to the Welcome/Updated page that WP and various other plugins have) which, among other things, will list credits of contributors. So developers contributing to the project will have their name displayed to all 4.5 million or so users. :)

**Comment by Ed-AITpro** [comment]
Well personally I don't think you need to change anything with the Action Links code you are currently using.  I never even noticed it until that whiner pointed it out. So I would feel embarrased about getting credit for something that is this insignificant/unimportant.  If I do see/find anything that is worthy of getting credit for then I will gladly offer to contribute whatever that is. ;)

Congrats on your huge user base!  I use and love your plugin and recommend it to everyone - it kicks ASS!

**Comment by michaeltorbert** [comment]
Thank you!
I agree, it's pretty low on the priority list, if it's going to change at all. ;)

Feel free to pick out any issues you like, or even just clean up some code or whatever you feel like contributing. https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues

**Comment by Ed-AITpro** [comment]
That is one hell of a "shopping task list".  At one point I had 300 issues that needed to be handled/fixed.  I am now down to 100 after 1 year.  You know how it goes though.  new things are always coming in so 3 things fixed then 1 new thing added to the pile...rinse and repeat...rinse and repeat.....  LOL :)

**Comment by michaeltorbert** [comment]
Well some are new features, some are improvements, some are bugfixes... it varies
Sometimes when working on one, discover several other issues that need to be created. ;)

**Comment by Ed-AITpro** [comment]
Yep that is exactly what I meant and could not have said it better myself. ;)

**Comment by wpsmort** [comment]
I'm moving this issue over to our new repo on Github.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #842](https://github.com/awesomemotive/aioseop-pro/issues/842) via [**ZenHub**](https://www.zenhub.com/)
