### ISSUE TITLE
XML Sitemap - Add filter API hook to remove unwanted URLs from sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1592]
Requested by Rudy via email:

`Subject: Sitemap pruning

Problem: (REGARDING UNWANTED SITEMAP ENTRIES)
We wish to NOT include unwanted or content-less pages in our site map. The attached code snippet will give developers a crack at what they wish to decide to prune. 

Location:
/ plugins/all-in-one-seo-pack/modules/aioseop_sitemap.php (around line 1932 or so…)

Code snippet:
// Added by RJM to give developer a chance to remove/review unwanted links
 $prio = apply_filters( $this->prefix . 'srip_useless', $prio, $page, $this_options );`

![pastedimage](https://user-images.githubusercontent.com/17364998/36870231-b16ab092-1d9e-11e8-8502-ad7d0e76e64c.png)

We already have aiosp_sitemap_data (https://semperplugins.com/documentation/filter-xml-sitemap-data/) so we should discuss whether adding an additional hook, such as aiosp_sitemap_urls, provides any usefulness.

**Comment by michaeltorbert** [comment]
We'll need to decide whether this should support removing by id, slug, or url, and what to pass, such as an array.
We also could consider making a function for people to use aioseop_remove_sitemap_urls( $array_to_remove );

**Comment by michaeltorbert** [comment]
We already have a checkbox to exclude from sitemap on each page, a list of excluded pages on the XML Sitemap options page, and a aiosp_sitemap_post_filter filter.

**Comment by michaeltorbert** [comment]
Make sure to create documentation as well (in its own issue).

**Comment by wpsmort** [comment]
This could work as a solution for #1744.  We should test if this is the case.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #783](https://github.com/awesomemotive/aioseop-pro/issues/783) via [**ZenHub**](https://www.zenhub.com/)

**Comment by EldonYoder** [comment]
Just curious if this is going to make it into a future version of aioseop-pro :) Currently trying to remove child pages of a specific page from the sitemap.

Thanks!

**Comment by wpsmort** [comment]
@EldonYoder Are you trying to remove pages because you don't want search engines to index those pages?  If so, then should use the Noindex setting in the All in One SEO box on the Edit Page screen to do this, as this will set the noindex tag and exclude the content from the sitemap.

We're currently refactoring the XML Sitemap code any this issue is assigned so that it gets included in that work.  We don't have a release date for it as yet.

**Comment by EldonYoder** [comment]
@wpsmort - I was trying to remove a page and all of its children. I ended up using aiosp_sitemap_data and reworking what the page sitemap_type returned... So I was able to come up with a solution, I was just wishing it would have been simpler. :)

**Comment by wpsmort** [comment]
@EldonYoder Thanks for the feedback. We'll certainly look at adding this filter to make it easier.
