### ISSUE TITLE
Add a "Custom Canonical URL" option in the "Home Page Settings" section of "General Settings"

### ISSUE THREAD

**Issue by jsandeo** [awesomemotive/all-in-one-seo-pack#1603]
This would allow for the definition of a canonical URL for the homepage of the site when using "Latest posts" as the homepage.

Useful if you run two blogs with virtually the same content.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #926](https://github.com/awesomemotive/aioseop-pro/issues/926) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
I've moved this to our new repo for inclusion in the v4 release.
