### ISSUE TITLE
aioseop_title filter hook doesn't change the preview snippet

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1611]
When helping a customer in the Pro forum https://semperplugins.com/support/configuring-all-in-one-seo-pack-pro/custom-meta-description-auto-generated/page-2 it was discovered that using the aioseop_title filter hook doesn't change our preview snippet, while the aioseop_description filter hook does does.

We should determine what the desired UX is here.

As we have lots of other situational filter hooks for the title and description, we should probably consider rewriting the snippet code to use the same code as the live title/desc instead of largely its own.

We could also use this opportunity to extract out all the title production code into its own file(s) (and for descriptions as well) as part of the goal of reorganizing the main class file.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #848](https://github.com/awesomemotive/aioseop-pro/issues/848) via [**ZenHub**](https://www.zenhub.com/)
