### ISSUE TITLE
XML Sitemap - Some bbPress topics missing in sitemap

### ISSUE THREAD

**Issue by DjMorgul** [awesomemotive/all-in-one-seo-pack#1620]
Only some of the bbPress topics my site has are showing up on the sitemap generated by All in One SEO Pack. I don't know what's the criteria making those "the chosen ones", but it's consistent the ones that are picked. Within the same forums, some are picked and others aren't. Disabling and re-enabling Topics post type didn't solve it (it shows no topics when disabled, and the lucky chosen ones when enabled).

**Comment by michaeltorbert** [comment]
You can submit your login information to our secure form here and we'll take a look: https://semperplugins.com/contact/submit-login-information/
Make sure to note which topics are missing.

**Comment by DjMorgul** [comment]
Done submitting that information. Thank you!

**Comment by wpsmort** [comment]
@DjMorgul Thank you for submitting your login information.  We found that only the topics marked Open are included in the XML Sitemap.  Topics that have a post status of Closed are not included.  We'll correct this in a future release.  For the time being you could use the Additional Pages section in the XML Sitemap to add the five closed topics.

**Comment by wpsmort** [comment]
We currently only include posts with a post_status of Published in the XML Sitemap.  We should have a filter to add more post statuses such as Closed for closed bbPress forum topics.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #925](https://github.com/awesomemotive/aioseop-pro/issues/925) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
Moved this to our new repo for inclusion in the v4 release.
