### ISSUE TITLE
XML Sitemap - Consider adding PDF support for XML sitemap

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#1621]
There's been several users that inquire about PDF support for our sitemap. We're currently not detecting PDFs automatically, but users can manually add them through the 'Additional Pages' section. Perhaps we should consider supporting this in the future. We could add an 'Exclude PDFs' setting similar to the 'Exclude Images' setting. I'm guessing the easiest way to support this would be to scan the Media Library for .pdf files.

**Comment by wpsmort** [comment]
Moved this to our feature request system.
