### ISSUE TITLE
XML Sitemap - bbPress Private forums are included

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#1629]
Whilst testing the problem in #1620 I found that bbPress forums that are marked as Private are being included in the XML Sitemap.  We should not included Private forums.

**Comment by DjMorgul** [comment]
I believe this was already addressed and solved by bbPress. That's probably how they broke your sitemap's query from returning other posts than bbPress related (the cause for issue #1947 in here).

**Comment by wpsmort** [comment]
@DjMorgul I just tested with Version 2.5.14 of bbPress and the problem is still present.  Do you know if the fix has been released by bbPress?

**Comment by michaeltorbert** [comment]
@arnaudbroes See if this still exists.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #890](https://github.com/awesomemotive/aioseop-pro/issues/890) via [**ZenHub**](https://www.zenhub.com/)
