### ISSUE TITLE
wrong canonical when removing category base

### ISSUE THREAD

**Issue by ulissse** [awesomemotive/all-in-one-seo-pack#1630]
Hello,

When people goes on some pages of my WP blog without using the category folder, for exemple : 

www.mysite.com/category_name/page/2/ 
instead of 
www.mysite.com/category/category_name/page/2/

All In One SEO Pack plugin use a wrong URL like this :

www.mysite.com/category/category_name/2/    (404 not found page)
instead of 
www.mysite.com/category/category_name/page/2/   

Can anyone tell my why is all in one seo delete the page folder of the URL ?

And is anyone having the same issue ?

Thank you for all the help you can provide and have a nice day.

**Comment by michaeltorbert** [comment]
Please provide the exact URLs.

**Comment by ulissse** [comment]
URL :   https://arnaqueoufiable.com/gagner-argent/page/2/ 

rel="canonical" URL : https://arnaqueoufiable.com/category/gagner-argent/2/

**Comment by wpsmort** [comment]
I'm closing this as we've not had any other reports of this and cannot reproduce it without more information.
