### ISSUE TITLE
file editor shows sanitized .htaccess content

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1632]
Reported here: https://wordpress.org/support/topic/file-editor-shows-sanitized-htaccess-content/

Original .htaccess content is…
`RedirectMatch 403 (?i)/(\$(\&)?|\*|\"|\.|,|&|&amp?)/?$
`
But file editor shows…
`RedirectMatch 403 (?i)/(\$(\&)?|\*|\"|\.|,|&|&?)/?$
`
When I save this, then website shows 403 Forbidden.

**Comment by wpsmort** [comment]
I'm no longer able to reproduce this.
