### ISSUE TITLE
Plugin adds unwanted meta description to woocommerce product archive pages

### ISSUE THREAD

**Issue by tilen0011** [awesomemotive/all-in-one-seo-pack#1638]
I have noticed that plugin adds meta descriptions to Woocommerce product archive page if I set category description (description to be shown on site) even if I uncheck "automatically generate a Meta Description" and similar options.

My temporary solution was to remove following:
     if ( empty( $description ) ) {
	   $description = term_description();
     }

in get_main_description function (aioseop_class.php).

Can this be fixed in next update?

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #891](https://github.com/awesomemotive/aioseop-pro/issues/891) via [**ZenHub**](https://www.zenhub.com/)
