### ISSUE TITLE
Non-static method WP_Feed_Cache::create() should not be called statically

### ISSUE THREAD

**Issue by campusboy87** [awesomemotive/all-in-one-seo-pack#1639]
Hello. Thanks for the plugin!

I use the [Query Monitor](https://wordpress.org/plugins/query-monitor/) plugin for the site's debugging. In the "Deprecated" tab I get the error "Non-static method WP_Feed_Cache::create() should not be called statically".

Screenshot:

![screen](https://user-images.githubusercontent.com/20075333/38085018-b454cd28-3357-11e8-975e-c937f6f8dadf.png)

I use:
* PHP 7.0.28
* WordPress 4.9.4
* All In One SEO Pack 2.4.6.1

**Comment by contactashish13** [comment]
looks like this is a WP core bug that is still unresolved: https://core.trac.wordpress.org/ticket/29204

**Comment by wpsmort** [comment]
I'm closing this as the WP core bug is still open and unresolved.
