### ISSUE TITLE
Improve contributing to git instructions

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#164]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/CONTRIBUTING.md#contributing-code

**Comment by wpsmort** [comment]
@michaeltorbert Here is a list of the screenshots:

http://semperplugins.com/wp-content/uploads/2016/04/1-Fork-the-repository.png
http://semperplugins.com/wp-content/uploads/2016/04/2-Forked-repository.png
http://semperplugins.com/wp-content/uploads/2016/04/3-Watch-the-original-repository.png
http://semperplugins.com/wp-content/uploads/2016/04/4-Select-the-development-branch.png
http://semperplugins.com/wp-content/uploads/2016/04/5-Create-a-branch-for-the-issue-you-are-working.png
http://semperplugins.com/wp-content/uploads/2016/04/6-Select-your-branch-in-our-repository.png
http://semperplugins.com/wp-content/uploads/2016/04/7-Select-your-branch-for-the-issue.png
http://semperplugins.com/wp-content/uploads/2016/04/8-Submit-your-pull-request.png

**Comment by michaeltorbert** [comment]
Instructions for adding WP standards to netbeans (we should also include for PHPStorm):

https://www.google.com/search?q=wordpress+coding+standards&oq=wordpress+coding&aqs=chrome.0.69i59j69i60j69i57j69i60l2j69i65.2684j0j7&sourceid=chrome&ie=UTF-8#q=wordpress+coding+standards+netbeans+phpstorm

**Comment by michaeltorbert** [comment]
http://kbroman.org/github_tutorial/pages/fork.html
http://www.pontikis.net/blog/how-to-collaborate-on-github-open-source-projects

**Comment by michaeltorbert** [comment]
https://guides.github.com/activities/contributing-to-open-source/
https://help.github.com/categories/collaborating-with-issues-and-pull-requests/
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/CONTRIBUTING.md#contributing-code

**Comment by michaeltorbert** [comment]
Main topics:

Github workflow

coding standards

dev tools
-editor/ide (preference for ones that have code sniffer or otherwise have WPCS compatibility)
-MAMP Pro or Local by Flywheel
