### ISSUE TITLE
Social Meta - Most of last name is lowercased

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1660]
Specifically %post_author_lastname%

Reported here: 

https://wordpress.org/support/topic/last-name-not-correct-on-social-media/

**Comment by H-K-P** [comment]
Hi Michael,
I was wondering if there is any chance of getting this bug fixed soon?
I just checked and it is still the same as 7 months ago.
Regards and thanks,
Angus

**Comment by H-K-P** [comment]
Hi Michael,
I was wondering if there is any chance of getting this bug fixed soon?
I just checked and it is still the same as 11 months and 3 weeks ago.
Honestly. i'd like to get me name back.....   :) 
Regards and thanks,
Angus

**Comment by michaeltorbert** [comment]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L2250

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #892](https://github.com/awesomemotive/aioseop-pro/issues/892) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
This has been assigned to a developer for the v4 release.
