### ISSUE TITLE
Add info to social meta troubleshooting documentation about social network sites cache

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#1692]
https://semperplugins.com/documentation/troubleshooting-incorrect-social-meta-when-sharing-or-publishing-content/

I've seen a few people reporting issues regarding LinkedIn's social snippet preview because "it is wrong" or "not fetching updated OG meta data". This is often caused because of the fact that LinkedIn caches all previews for one week. This solves that issue - https://www.linkedin.com/pulse/how-clear-linkedin-link-preview-cache-ananda-kannan-p/

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #749](https://github.com/awesomemotive/aioseop-pro/issues/749) via [**ZenHub**](https://www.zenhub.com/)
