### ISSUE TITLE
Link rel=”next” missing on a CPT custom query archive used on a Page Template

### ISSUE THREAD

**Issue by gicolek** [awesomemotive/all-in-one-seo-pack#1693]
Hello,

I’m sorry if this is a duplicate. I did my best to search for a solution of the problem both here, on wordpress.org forums and on stackoverflow and failed miserably.

Basically the linked page uses a custom WP_Query to list the article posts as well as produce the bottom pagination.

However for some reason (explained below) the global **$wp_query** variable **max_num_pages** property returns 0, in the end causing the plugin not render the corresponding <link rel=”next”> tag within the <head> element. 

The call occurs here: https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L4301

Has anyone figured out how to sort such an issue?

I do know that I can hook into **aioseop_next_link** filter and modify the link myself, however I was wondering if there was any other / simpler solution. I think this is quite a common problem and would be nice to figure out an optimal solution for such.

As a temporary fix I tried to overwrite the global **$wp_query** variable with my custom query variable directly from within the template. However the AIOSEOP fetches this variable a bit sooner hence the trick didn't work.

I'm not sure if this could be labelled a core WordPress bug. The global **$wp_query** variable, fetched on a page template will reference the page's global variable and won't reference custom **WP_Query** object. This seems quite logical.

As a sample let's take a look at the following page: https://luckystreet.com/article.

**Comment by wpsmort** [comment]
I'm closing this as it's quite out of date and could be more of a core WP issue in the way wp_query works.
