### ISSUE TITLE
Social Meta - Behavior of social images when removing image from post

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1697]
Reported here: https://wordpress.org/support/topic/images-custom-images-not-purging-from-social-settings-tab/

> Once a post is saved (autosave or otherwise), all the images in the post at that time, are saved permanently and show up henceforth on the Social Settings tab.

> Any post revisions which add or replace images, irrespective of whether they are Social Tab ‘Custom Images’, are also added but the deleted images still remain.

> cannot purge any of the old images

![saved-images_preview](https://user-images.githubusercontent.com/17364998/40310529-1b8a5916-5cdb-11e8-902b-b6ae46359ed2.jpeg)

**Comment by michaeltorbert** [comment]
We need to be careful about how to handle improving the experience here. It's possible that someone could be using an image as their social image that's no longer in the post, in which case we'd be breaking things for them.
One way to handle it is to have a little "x" or something so that they can manually remove images from the list.
Any other ideas?

**Comment by arnaudbroes** [comment]
I think having a Delete option would already be a big improvement. But I'm not a big fan of the our social image reel anyway.

**Comment by michaeltorbert** [comment]
Requested by Karen via email:

_I have a static front page and I change my photos frequently. On the Social Setting tab I have noticed a buildup of images and would like to delete them._ 

Should these be generated on the fly instead of stored in the db?

**Comment by michaeltorbert** [comment]
We should discuss if there's a better way to handle this, maybe with temporary caching instead of permanent?
or maybe if we just add an "x" or something to delete each?

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #923](https://github.com/awesomemotive/aioseop-pro/issues/923) via [**ZenHub**](https://www.zenhub.com/)
