### ISSUE TITLE
New Feature - Uninstall form

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1708]
When someone uninstalls, we should use the pre_uninstall_plugin action (requires WP 4.5) to a) find out why they're uninstalling ( switching to another plugin (ask which), other (blank space), just testing/development ) and b) what can we do to keep them from uninstalling ( have space for them to send us a message )

Info should be sent via some method that's not email... to our (data?) server

**Comment by michaeltorbert** [comment]
Some plugins have this.

**Comment by wpsmort** [comment]
Here's an example of what this looks like in other plugins:

![deactivation-form-example](https://user-images.githubusercontent.com/17548525/59230780-94e23800-8bac-11e9-9f9b-bf4283854f27.jpg)

**Comment by arnaudbroes** [comment]
![image](https://user-images.githubusercontent.com/18156697/59538426-fd594e00-8ef9-11e9-9edf-4ec924f3746a.png)
