### ISSUE TITLE
XML Sitemap - URLs are not encoded correctly

### ISSUE THREAD

**Issue by demon-ru** [awesomemotive/all-in-one-seo-pack#1711]
To retrieve links when writing a sitemap used the function aioseop_get_permalink:
return urldecode( get_permalink( $post_id ) );

To write to a file used "esc_url" that does not encode urls.

Thats why urls are not encoded.

For example:
`
       <url>
                <loc>https://sample.com/reply/re-jabber-и-телефон-14/</loc>
                <lastmod>2014-01-13T20:53:29Z</lastmod>
                <changefreq>yearly</changefreq>
                <priority>0.1</priority>
        </url>
`

**Comment by demon-ru** [comment]
Temporary fixed by replacing
return aioseop_get_permalink( $post )
by
return get_permalink( $post );
in modules/aioseop_sitemap.php (line 3161)

**Comment by michaeltorbert** [comment]
Hi @demon-ru 

Thank you for reporting this. To ensure a patch goes in (and to expedite the process), you can feel free to submit a PR.

**Comment by wpsmort** [comment]
@arnaudbroes I'm assigning this to you to look at for the v4 release.

**Comment by arnaudbroes** [comment]
@wpsmort this is what I have in V4 now so I'm guessing V4 will fix this?
![image](https://user-images.githubusercontent.com/18156697/81511041-c280b580-9316-11ea-822d-ffb87a24519e.png)

I'm afraid that I do not fully understand the issue as the description is a bit vague.

**Comment by wpsmort** [comment]
@arnaudbroes I don't understand this enough to say.  I'd say that you just want to be sure you're correctly encoding URLs that contain non Latin alphabets such as Cyrillic, Chinese, Japanese, etc.

We've only had this one report though so I'm not entirely sure it's an actual problem.  Surely if it was, we'd have had many more reports.  We may want to set up a public test site where we can submit the sitemap to Google Search Console and see if there are errors.

**Comment by karipe** [comment]
I am experiencing the same problem.
Percent encoding is required to use non-ascii charactor. ( https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier and https://en.wikipedia.org/wiki/Percent-encoding )
So unless you fix the problem, Google Search Bots cannot recognize the non-ascii url of sitemap.

Temporary workaround on 3.6.2 version
return urldecode( get_permalink( $post_id ) ); -> return get_permalink( $post_id );
in inc/aioseop_functions.php (line 27)

**Comment by arnaudbroes** [comment]
@karipe would you be able to provide us with an example of a raw URL and what it should look like? I'm afraid that we're all Latin alphabet users so it would definitely make things a bit more clear for us.

**Comment by karipe** [comment]
@arnaudbroes Examples I can provide are as follows:

Korean
wrong: http://example.com/Hello/세상아/세상아-안녕
correct: http://example.com/Hello/%EC%84%B8%EC%83%81%EC%95%84/%EC%84%B8%EC%83%81%EC%95%84-%EC%95%88%EB%85%95

Japanese
wrong: http://example.com/Hello/世界/こんにちは、世界
correct: http://example.com/Hello/%E4%B8%96%E7%95%8C/%E3%81%93%E3%82%93%E3%81%AB%E3%81%A1%E3%81%AF%E3%80%81%E4%B8%96%E7%95%8C

Chinese
wrong: http://example.com/Hello/世界/你好，世界
correct: http://example.com/Hello/%E4%B8%96%E7%95%8C/%E4%BD%A0%E5%A5%BD%EF%BC%8C%E4%B8%96%E7%95%8C

Russian
wrong: http://example.com/Hello/мир/Здравствуй-мир
correct: http://example.com/Hello/%D0%BC%D0%B8%D1%80/%D0%97%D0%B4%D1%80%D0%B0%D0%B2%D1%81%D1%82%D0%B2%D1%83%D0%B9-%D0%BC%D0%B8%D1%80

Czech
wrong: http://example.com/Hello/Světe/Ahoj-Světe
correct: http://example.com/Hello/Sv%C4%9Bte/Ahoj-Sv%C4%9Bte

**Comment by arnaudbroes** [comment]
@karipe thank you, that is really helpful. We'll try to get this resolved ASAP.

**Comment by karipe** [comment]
I think #1445 problems can cause confusion. The problem mentioned in #1445 is the right point. However, in order to correct the bug, it was necessary to use urldecode only for the URL to be printed on the screen on the snippet.

The #1446 issue has created bugs everywhere else instead of correct Snippet's bugs. Multilingual characters in the UTF-8 area are not allowed in URLs, therefore url must be decode only when visible to the human eye.
