### ISSUE TITLE
flip seo on these post types

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1718]
Instead of having "SEO only on these post types," we should flip it so that every post type defaults to on, and you have to remove it.

**Comment by arnaudbroes** [comment]
@michaeltorbert that's a fantastic idea and should help us avoid a lot of support tickets.

**Comment by wpsmort** [comment]
@michaeltorbert I agree that we should flip this so that all post types are set to on.  We will need to check for only custom post types that are public so that post types such as oEmbed Responses and User Requests are not included.

See also #68
