### ISSUE TITLE
Meta Description - Remove image caption text for autogenerated description

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1736]
Requested by Gorbatschow via Facebook. https://www.facebook.com/aioseopack/inbox/?selected_item_id=100011387821738

Remove image caption text from autogenerated meta description.

`<p class="wp-caption-text">Caption goes here</p>`

We should discuss if this is something we want to do.

**Comment by michaeltorbert** [comment]
Perhaps we should be stripping out all HTML?

**Comment by arnaudbroes** [comment]
@wpsmort will see if he can reproduce this since we thought this we are already stripping out HTML.

**Comment by wpsmort** [comment]
@arnaudbroes I was able to reproduce this in the new Block editor but not in the old classic editor.  

Steps to reproduce:

1. Ensure that Autogenerate Descriptions is enabled
2. Create a post using the Block editor
3. Add an image using the Image block and set a caption
4. Add some paragraph text after the image
5. View the source code of the post and check the meta description, og:description and twitter:description and you'll see the image caption text

The change that occurred here is that an image with a caption in the classic editor looked like this:

```
[caption]<img src="https://mydomain.com/wp-content/uploads/2019/02/image.jpg" /> This is my image caption[/caption]
```

But with the Block editor it now looks like this:

```
<figure><img src="https://mydomain.com/wp-content/uploads/2019/02/image.jpg" /><figcaption>This is my image caption</figcaption></figure>
```

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #870](https://github.com/awesomemotive/aioseop-pro/issues/870) via [**ZenHub**](https://www.zenhub.com/)
