### ISSUE TITLE
REST API Integration

### ISSUE THREAD

**Issue by luisherranz** [awesomemotive/all-in-one-seo-pack#1760]
**Is your feature request related to a problem? Please describe.**
Thanks to the REST API we can now consume WP content outside of its PHP templating system. We should have a way to retrieve the data created by AIOSEOP using the REST API. If not, this plugin will become useless for all those new WP use cases.

**Describe the solution you'd like**
It should expose the relevant data using the REST API. One solution would be to include it the existing endpoints and other to create new endpoints.

Any thoughts?

**Comment by luisherranz** [comment]
> Can you give some example of how this would work with existing endpoints? What are those endpoints?

Ok. Imagine you want to fetch your content using the REST API and build the final HTML using that data. Your endpoint would be something like this:
https://demo.worona.org/wp-json/wp/v2/posts/60?_embed=true
(`_embed=true` is used to include the author/tags/categories/images data in the same response)

You need to populate your HTML with that data, for example `<title>`, but the only thing you have is the post title. If someone wants to use AIOSEOP to change their posts `<title>` tags, that data won't be available in the REST API.

If AIOSEOP includes a field with this data in the existing endpoints, then this answer
https://demo.worona.org/wp-json/wp/v2/posts/60?_embed=true
would have a new field, for example called `seo`, so devs get the info without having to fetch an additional response:
```js
{
  id: 60,
  modified: "2018-03-22T17:09:55",
  slug: "the-beauties-of-gullfoss",
  type: "post",
  link: "https://demo.worona.org/the-beauties-of-gullfoss/",
  title: {
    rendered: "The Beauties of Gullfoss"
  },
  seo: {
    title: "Discover the Beauties of Gullfoss - My Awesome Blog",
    description: "Gullfoss is a waterfall located in the canyon of the Hvítá river in southwest Iceland.",
    keywords: "nature, iceland, gullfoss" 
  },
  ...
}
```

If AIOSEOP exposes a new endpoint, then a new url is needed. Something for example like:
https://demo.worona.org/wp-json/aioseop/v1/posts/60
that will expose only the seo data:
```js
{
  title: "Discover the Beauties of Gullfoss - My Awesome Blog",
  description: "Gullfoss is a waterfall located in the canyon of the Hvítá river in southwest Iceland.",
  keywords: "nature, iceland, gullfoss" 
}
```

This approach has the drawback of having to fetch two different endpoints to retrieve all the content needed to render that post.

In any case, data needs to be exposed for posts, pages, cpts, tags, categories and custom taxonomies.

----- 

An additional problem appears with the "home" and "cpt archives" pages, as those don't have a proper endpoint in the REST API. For example, if you are about to render the home of a blog, your endpoint would be:
https://demo.worona.org/wp-json/wp/v2/posts?_embed=true
which is an array of posts. But there's no way to know what `<title>` you should use, and there's no way to extend this endpoint because it's an array.

One solution would be to add the info in the Headers (like WP does for the total number of pages and posts in this type of lists). Another solution would be to create dedicated endpoints for these cases, maybe something like:
https://demo.worona.org/wp-json/aioseop/v1/posts
```js
{
  title: "My Awesome Blog - I travel and write about it",
  description: "My name is Andrew and I travel around the world visiting amazing places",
  keywords: "travel, andrew, blog"
}
```
The same might work for custom post types:
https://demo.worona.org/wp-json/aioseop/v1/my_custom_post_type

----

> what are your thoughts on whether it would be better to do that vs create new endpoints?

Hmm... not sure yet. I think from a dev perspective, one fetch is always better than two, but on the other hand the "home" problem can't be solved with the existing endpoints.

**Comment by michaeltorbert** [comment]
Sounds like creating new endpoints is probably the way to go.
If you're interested in submitting a PR, that would ensure this gets included more quickly.

**Comment by luisherranz** [comment]
I'll do it as soon as I have time to explore AIOSEOP code and internal APIs.

**Comment by fakesamgregory** [comment]
Have there been any updates on this? Definitely a needed feature for this plugin.

**Comment by michaeltorbert** [comment]
@fakesamgregory There's no update for this at the moment (any updates will show up in this issues). 
If this issue is particularly important, you're welcome to submit a PR.

**Comment by michaeltorbert** [comment]
Suggestion from Hiroaz https://wordpress.org/support/topic/get-ogp-title-and-description-via-wordpress-rest-api/

`add_action( 'rest_api_init', 'adding_post_meta_rest' );
function adding_post_meta_rest() {
  register_rest_field( 'post',
	'_aioseop_title',
	array(
		'get_callback'      => 'post_meta_callback',
		'update_callback'   => null,
		'schema'            => null,
	)
   );
  register_rest_field( 'post',
	'_aioseop_description',
	array(
		'get_callback'      => 'post_meta_callback',
		'update_callback'   => null,
		'schema'            => null,
	)
   );

  function post_meta_callback( $post, $field_name, $request) {
	return get_post_meta( $post[ 'id' ], $field_name, true );
  }
 `

**Comment by wpsmort** [comment]
This has been moved to our new feature request system.

**Comment by luisherranz** [comment]
May I know where is it? :)

**Comment by wpsmort** [comment]
It's currently not public yet.

**Comment by mikestopcontinues** [comment]
Has this happened yet? Trying to decide which SEO plugin to choose.

**Comment by wpsmort** [comment]
@mikestopcontinues No, it has not yet but we'll add your vote for this to happen.

**Comment by zombiefredrik** [comment]
Any news on this? really need to get some aio info for headless data from wp.

**Comment by arnaudbroes** [comment]
@zombiefredrik we're exploring the possibilities but haven't decided on an approach yet.
