### ISSUE TITLE
Redo our WP Filesystem API interface code

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1778]
Our code to interface with the WP filesystem API is old and probably outdated. We should look at it to see if can be improved/modernized.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #796](https://github.com/awesomemotive/aioseop-pro/issues/796) via [**ZenHub**](https://www.zenhub.com/)
