### ISSUE TITLE
XML Sitemap - Multisite sitemap with domain cross-reference

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#1800]
Reported here: https://wordpress.org/support/topic/multisite-sitemap-with-domain-cross-reference/

http://bahngebote.de/sitemap.xml (Dynamic sitemap is being used here).

**Comment by Sandjab** [comment]
Same here. I have a multisite  WP install consisting in 4 onepager sites (one main, and 3 subdomains). 

As already described by @arnaudbroes, the mainsite sitemap contains the subdomains sitemaps URLs. 

I would normally don't mind, but as you can see below, the substites sitemaps are not between `<sitemap>` tags but between `<url>` tags. 

Thus google tries to index them, but as they are obviously marked as noindex, it generates coverage errors in the Google Search Console (which i do mind :) )

```
<!-- Sitemap dynamically generated by All in One SEO Pack 3.1 by Michael Torbert of Semper Fi Web Design on Fri, 14 Jun 2019 11:15:10 UTC -->
<?xml-stylesheet type="text/xsl" href="https://starling.partners/sitemap.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
	<url>
		<loc>https://earth.starling.partners/sitemap.xml</loc>
	</url>
	<url>
		<loc>https://health.starling.partners/sitemap.xml</loc>
	</url>
	<url>
		<loc>https://one.starling.partners/sitemap.xml</loc>
	</url>
	<url>
		<loc>https://starling.partners/</loc>
		<lastmod>2019-06-12T10:03:04Z</lastmod>
		<changefreq>daily</changefreq>
		<priority>1.0</priority>
	</url>
</urlset>

```

Also, for some reason, i cannot uncheck the "dynamically generate sitemap" checkbox, so the only way i have to work around this issue and use handwritten static sitemaps is by inactivating the sitemap feature as a whole.

PS: Another workaround is to check the "Enable Sitemap Indexes" option, leading to syntaxically correct sitemaps, but it's a bit an overkill for a one page site...

**Comment by arnaudbroes** [comment]
I'm going to close this issue since our multilingual sitemap now lists all translated versions.
