### ISSUE TITLE
Placeholder text does not match autogenerated title or description

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#1808]
Whilst testing #1421 I found that the placeholder text shown in the Title and Description fields on the Edit Post screen does not always match the autogenerated title and description.

I believe this is a problem we've known about for some time but I couldn't find an issue open for this.  

The code that controls how placeholders are created needs to be reviewed.  The placeholders should match what's displayed as the title tag and meta description in the source.  

To test this, change the Title Format fields and Description Format field under Title Settings to any of the supported macros and see if the placeholder text matches the format used and matches what's displayed in the source code.

For example, test using these formats:

Post Title Format: %post_title% - %category_title% | %blog_title%
Description Format: %description% - %post_date% 

If you edit a post and look at the placeholder text in the Title and Description fields you'll see that they don't match the format and the title tag and meta description in the source code.

This affects all post types and taxonomies.

**Comment by michaeltorbert** [comment]
We need to completely extract all the code that deals with generating the title, and then do the same for the description. Currently, different (overlapping) code handles it differently depending on whether it's the placeholder text or the live site.

**Comment by wpsmort** [comment]
I'm closing this as it should be taken care of in the v4 architecture.
