### ISSUE TITLE
Bug - Redirect attachments should ignore trashed content

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#1810]
Whilst testing #1425 I found that there is a bug with the Redirect Attachments to Post Parent setting that is specific to WooCommerce Products.

If you create a product and add images to the content and/or the Product Image or Product Gallery and then you delete the product, the attachment pages are still present in the XML Sitemap and when you click on one of these URLs you get a Too many redirects error.

Here are the steps to reproduce:

1. Create a product called Test Product and upload some new images to the product.  You can add them to the content or the Product Image or Product Gallery.
2. Go to the Media Library and ensure the images are attached to the product.
3. Trash the product then go back to the Media Library and verify that the images are still attached to the product.
4. Making sure you have Media / Attachments included in your XML Sitemap, go to your sitemap.  You should see a URL like this - https://mydomain.dev/?attachment_id=2620.  Click on this link and you should get a redirect loop for a URL that looks like this https://aioseop.dev/product/test-product__trashed/
5. Uncheck the Redirect Attachments to Post Parent setting and try clicking on the link to the attachment page again and it should work fine.

As far as I can tell this only happens with WooCommerce Products.  I can't reproduce this with any other post type.

**Comment by contactashish13** [comment]
@wpsmort I cannot reproduce the behavior exactly. Instead of a redirect loop I get the behavior mentioned in https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1810. And using the PR there solves this.

**Comment by michaeltorbert** [comment]
@contactashish13 Which PR and issue are you referring to? This is 1810.

**Comment by contactashish13** [comment]
@michaeltorbert my bad. Have updated my comment.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #895](https://github.com/awesomemotive/aioseop-pro/issues/895) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
I've moved this to our new repo for the dev team to work on.
