### ISSUE TITLE
SEO Data Importer - Import broken

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1829]
The import from yoast prompt no longer shows up after a recent update of yst.

**Comment by arnaudbroes** [comment]
I'll check if I can narrow down the version.

**Comment by arnaudbroes** [comment]
@michaeltorbert I traced this back to version 7.1. This is what [their changelog](https://goo.gl/NBtBHM) says:

> Detects when you need to import old SEO plugin data and allows you to import it on the import plugins page. After importing you can check whether the import was completed successfully and then delete the data.

**Comment by michaeltorbert** [comment]
I'm a bit curious as to exactly why this behavior changed, but the thing to do may be just to redo the notice completely. (We'd borrowed their code to show the exact same notice they had.)

@arnaudbroes Can you install old versions of both plugins (from say, a year ago) and grab some screenshots of the notices for whoever takes this over?

**Comment by arnaudbroes** [comment]
![image](https://user-images.githubusercontent.com/18156697/47394656-f0e27400-d723-11e8-9411-9d53405a18fb.png)

**Comment by arnaudbroes** [comment]
![image](https://user-images.githubusercontent.com/18156697/47394677-05267100-d724-11e8-8c66-048de8fd69d9.png)

**Comment by arnaudbroes** [comment]
Clicking on "import its settings" for Yst -> AIOSEOP redirects to the SEO Data Importer and shows another notice "sorry, can't do that". 

Clicking on "import its settings" for AIOSEOP -> Yst automatically imports data.
