### ISSUE TITLE
file_exists requires credentials check

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1844]
in aioseop_module_class.php, all the file interface functions start with get_filesystem_object() which requires a credentials check. This seems unneeded in many cases, such as simply checking if a file exists.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #779](https://github.com/awesomemotive/aioseop-pro/issues/779) via [**ZenHub**](https://www.zenhub.com/)
