### ISSUE TITLE
New Feature - Add taxonomies and custom fields via shortcode

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1859]
Requested via email by Jason B.

> Just wondering, if I have custom taxonomies that I want specific in TITLE or DESCRIPTION, e.g. I'm making a car dealer site, & I want the descriptions to only show certain TAX, like year_made make_manufacture manufacturer_model etc.
_____________________________

> I know Yoast can do it like this:
%%cf_year_made%% %%ct_make_manufacturer%% %%ct_make_model%% %%cf_series_vehicle%% %%cf_badge_variant%% For Sale.

Sample code: https://katz.co/1003/

**Comment by jasonb4u** [comment]
Hi,
I had found this on Yoast  and believe that the All In One SEO Pack should have this feature also as we can fully customize our SEO pages.
https://kb.yoast.com/kb/yoast-wordpress-seo-titles-metas-template-variables/#advanced-variables
[](https://kb.yoast.com/kb/yoast-wordpress-seo-titles-metas-template-variables/#advanced-variables) 


This is current All In One SEO 
![sem](https://user-images.githubusercontent.com/20693414/44363830-afa5cc00-a508-11e8-9e99-69275afafb23.jpg)

This is current YOAST
![yo](https://user-images.githubusercontent.com/20693414/44363995-322e8b80-a509-11e8-863e-453d9a001309.jpg)

I'd love for this feature to be in All In One SEO, a few tweaks should do it, that I dont know how to do

**Comment by michaeltorbert** [comment]
We already do this for custom fields in post titles and descriptions, whether at the post level or in the templates. https://semperplugins.com/documentation/advanced-custom-fields-integration-with-title-format-fields/

We'll need to make this work for adding taxonomies as well.

**Comment by jasonb4u** [comment]
Hi,

 

Yes, Taxonomies, am major part of worpress users make use of the TAX yet we cant add it to AIO.  Hopefully this will be very sooooooon in next update.

 

 

Cheers

 

Jason.

**Comment by jasonb4u** [comment]
I see there was an update to 2.9, and still nothing for custom taxonomies, how come ?

**Comment by michaeltorbert** [comment]
@jasonb4u You will see in this issue when development has been done on it. No need to post additional comments asking.

**Comment by jasonb4u** [comment]
Delays lol,
Maybe this might help, I dont know, but getting TAXONOMIES into the plugin is a must, I have no idea why ya said will cause delays unless it sound like something you guys arent interested in doing

https://katz.co/1003/

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #927](https://github.com/awesomemotive/aioseop-pro/issues/927) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
I've moved this to our new repo for the v4 release that's currently in development.
