### ISSUE TITLE
Meta Description - Add autopopulate to fields

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1860]
This should apply to title/desc/etc in post editor as well as fields in options pages. (This may be multiple issues.)

Requested via email by Jason B:

> Here you can see I started typin the TAX I wanted and the list populates & I can select:  http://prntscr.com/kjzuu4

**Comment by arnaudbroes** [comment]
This should be done after the meta description code is refactored.
