### ISSUE TITLE
UI - URL in preview snippet doesn't show permalink until page is published

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1875]
Until then it's example.com/?p=123

Reported here: https://wordpress.org/support/topic/permalink-and-page-title/

**Comment by michaeltorbert** [comment]
We need to review this considering Gutenberg. Any fix needs to be tested with and without Gutenberg, in older versions of WP (4.6) and the latest. In the latest it should be tested with Gutenberg and with the visual editor plugin installed.

**Comment by contactashish13** [comment]
This needs discussion keeping the following in mind: 

- a permalink is created when the post is published. That is why it shows an ugly permalink till the post is in auto-draft status
- when creating a new post, the post title is empty till the user starts typing.
- do we want the permalink to keep updating as the title updates?
- do we want to hide the snippet area till the post is published?

somewhat related to this, do we want the snippet title to keep updating as well?

**Comment by michaeltorbert** [comment]
The permalink is created when a draft is saved as well. 

As soon as a permalink is created, ours should update as well.

**Comment by arnaudbroes** [comment]
I won't be able to get this done for 3.2 but I'll do this properly once https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2736 is merged by sending the active permalink setting to our JavaScript code and then generating the permalink for the preview snippet on-the-fly based on the active setting.
