### ISSUE TITLE
Add API hook to filter our robots.txt output

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1879]
As we hook into the WP core API filter hook robots_txt, we should have our own (aioseop_robots_txt or something) that runs after we've finished with it.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #782](https://github.com/awesomemotive/aioseop-pro/issues/782) via [**ZenHub**](https://www.zenhub.com/)
