### ISSUE TITLE
user aioseop_get_options()

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1881]
In some places within the plugin and in testing we use get_option( 'aioseop_options' ) instead of aioseop_get_options(). Is this an oversight or is there a reason not to?

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #799](https://github.com/awesomemotive/aioseop-pro/issues/799) via [**ZenHub**](https://www.zenhub.com/)
