### ISSUE TITLE
Plugin doesn't output any meta tags for bbPress Topic Tags

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#1902]
Reported by Iskandar Ibragimov by email.

The Use noindex for Taxonomy Archives option doesn't work for bbPress Topic Tags.  Neither does the NOINDEX this page/post option when you edit the Topic Tag (Pro only).

To reproduce this:

1. Install bbPress and create a forum and add a topic.  
2. Then add a Topic Tag to your topic (this is a taxonomy just like Tags).  
3. Check the Topic Tags box under Use noindex for Taxonomy Archives in AIOSEOP.
4. Check the source code and there is no meta tag.
5. Edit the Topic Tag and check the NOINDEX this page/post box (Pro only).
6. Check the source code and there is no meta tag.

**Comment by arnaudbroes** [comment]
@wpsmort that's correct, we've never output any meta tags for Topic Tags so I'll change the title of the issue.

**Comment by wpsmort** [comment]
I tested and this is now fixed.
