### ISSUE TITLE
Review save post hooks

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1906]
In admin/aioseop_module_class.php we have 6 hooks that call the "save_post_data". We need to look at each and see are they all actually needed or if just save_post is enough.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #773](https://github.com/awesomemotive/aioseop-pro/issues/773) via [**ZenHub**](https://www.zenhub.com/)
