### ISSUE TITLE
Add a UI for entering link titles

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#193]
Prior to WordPress v4.2 you could enter link titles in the Link popup dialog.  They then removed this feature and in WordPress v4.5 they completely changed the Link dialog with the new inline link dialog.

As link titles are still a part of SEO, we should consider adding support for this.

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/16024777/8d9e88d2-3191-11e6-96e0-35f9fc3a80e6.png)

**Comment by wpsmort** [comment]
Here's a mockup of how this could look:

![screen-capture-1](https://cloud.githubusercontent.com/assets/17548525/16024852/f3a625cc-3191-11e6-9b24-57f10f8b0178.png)

**Comment by wpsmort** [comment]
There is a plugin that does this here - https://wordpress.org/plugins/restore-link-title-field/

**Comment by michaeltorbert** [comment]
After we write it, we need to make sure we test this on various versions of WP.

**Comment by wpsmort** [comment]
We added this in v3.4
