### ISSUE TITLE
Robots.txt - Duplicate paths are not allowed

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1934]
Reported here: https://wordpress.org/support/topic/block-soe-user-agents-with-robots-txt-feature/

To reproduce, enter agent1 and any path, then enter agent2 and the same path. You'll get the message "Path cannot be overridden:"

-----------

We need to discuss exactly how we want to handle this. Do we have this behavior to keep from having conflicting rules? If so, is it our job to do so?

**Comment by michaeltorbert** [comment]
@arnaudbroes Can you see if this still applies considering our new robots.txt functionality?

**Comment by arnaudbroes** [comment]
I'll see if I can still reproduce this.

**Comment by arnaudbroes** [comment]
This is still an issue.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #900](https://github.com/awesomemotive/aioseop-pro/issues/900) via [**ZenHub**](https://www.zenhub.com/)

**Comment by admindotnu** [comment]
Issue is moved, link not working. Issue still an issue.

**Comment by wpsmort** [comment]
This has been moved to our new Github repo which is not yet public.

**Comment by admindotnu** [comment]
But when will this issue be resolved ? Ticket already started in 2018...

**Comment by wpsmort** [comment]
We expect to resolve it in the v4 release.  We have no release date yet.
