### ISSUE TITLE
Make display of Column Labels dependent of "SEO on these post types" setting

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#1950]
If SEO for a custom post type is disabled, but the column labels are enabled, then they still show up, which doesn't make much sense to me. Shouldn't we simply make the display of column labels dependent of whether or not SEO for a certain post type is enabled?

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #834](https://github.com/awesomemotive/aioseop-pro/issues/834) via [**ZenHub**](https://www.zenhub.com/)
