### ISSUE TITLE
Canonical URL for archives wrong when using custom canonical

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#1971]
If the latest post in a date or author archive has has a custom canonical URL then this is used as the canonical URL for the archives.

Steps to reproduce:
1.  On a brand new site, create two posts and enable Custom Canonical URLs in AIOSEOP
2.  View the source code of the date archives and the author archives. The canonical URL should be correct
3.  Edit the latest post and enter a custom canonical URL and save
3.  View the source code of the date archives and the author archives. The canonical URL is now the custom canonical set for the latest post

This happens for all post types including CPTs.

**Comment by wpsmort** [comment]
@arnaudbroes Can you test and see when this bug was introduced.

**Comment by arnaudbroes** [comment]
@wpsmort this never broke and has been a bug since the release (v2.2.4) of this feature.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #864](https://github.com/awesomemotive/aioseop-pro/issues/864) via [**ZenHub**](https://www.zenhub.com/)
