### ISSUE TITLE
XML Sitemap - Exclude Media Attachments when redirection to post parent is enabled

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#1977]
Steve noted that we should consider excluding attachment pages from the sitemap when the "redirect to post parent" setting is enabled since it doesn't make sense for those pages to be in the sitemap if they redirect to somewhere else.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #928](https://github.com/awesomemotive/aioseop-pro/issues/928) via [**ZenHub**](https://www.zenhub.com/)
