### ISSUE TITLE
Refactor All_in_One_SEO_Pack::add_page_icon

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2019]
Class method `All_in_One_SEO_Pack::add_page_icon` does what `All_in_One_SEO_Pack::admin_enqueue_scripts`
should be doing instead.

There is also JavaScript code that should be in a JS file.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L3035

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #801](https://github.com/awesomemotive/aioseop-pro/issues/801) via [**ZenHub**](https://www.zenhub.com/)
