### ISSUE TITLE
See if it's possible to support bbPress forum / topic titles 

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#202]
See if it's possible to support bbPress forum / topic titles etc. on top of BuddyPress Groups as per Gary Archer's support issue

**Comment by arnaudbroes** [comment]
@contactashish13 We received the question via e-mail, but the user did not provide details.
This is what he said:

> "I am looking at using your SEO plugin and have been testing it. Do you know if it fully works with Buddpress. I have tested it and it seems to somewhat but I am not seeing BBpress group areas working. "

**Comment by wpsmort** [comment]
This now works.
