### ISSUE TITLE
Documentation - New filters from v2.9/v2.10 that need API docs

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2020]
1).  https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/752

```
add_filter( 'aiosp_sitemap_tax_args', 'change_sitemap_tax_args', 10, 1 );

function change_sitemap_tax_args( $args ) {
    unset( $args['exclude'] );
    return $args;
}

```

2).  https://github.com/semperfiwebdesign/aioseop-pro/issues/186

```
add_filter( 'aiosp_opengraph_default_image_type', 'change_opengraph_default_image_type', 10, 2 );

function change_opengraph_default_image_type( $img_type, $post ) {
	// use the featured for a hypothetical post type 'xxx'
	if ( 'xxx' === $post->post_type ) {
		return 'featured';
	}
	return $img_type;
}

```

3).  https://github.com/semperfiwebdesign/aioseop-pro/issues/186

```
add_filter( 'aiosp_opengraph_default_image', 'change_opengraph_default_image', 10, 2 );

function change_opengraph_default_image( $thumbnail, $post ) {
	// use a hypothetical image for a hypothetical post type 'xxx'
	if ( 'xxx' === $post->post_type ) {
		return 'https://mydomain.com/wp-content/uploads/2018/10/my-image.jpg';
	}
	return $thumbnail;
}
```

4).  https://github.com/semperfiwebdesign/aioseop-pro/issues/255

`add_filter( 'aisop_woocommerce_hide_hidden_products', '__return_false' );`

**Comment by EkoJR** [comment]
@arnaudbroes I would recommend having the filter, as well as the documentation, changed to remove $post (before this become official). There is no reason to have `$post` since it is just a `global $post` when programmers can just use `global $post` themselves.

It would eliminate having to be tied to a variable that is unnecessary to have as a param.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #748](https://github.com/awesomemotive/aioseop-pro/issues/748) via [**ZenHub**](https://www.zenhub.com/)
