### ISSUE TITLE
Categories result in blank page when both AIOSEOP and Yoast SEO are activated

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2063]
I identified a bug where category pages result in a blank page when both AIOSEOP and Yoast SEO are installed and activated. The issue can be reproduced using these steps:

1. Install both AIOSEOP and Yoast SEO
2. Create one or multiple categories and assign them to the nav menu of the theme
3. Go to the site and click on one of the categories. You'll end up on a blank page.

I've traced this back to Yoast SEO v. 7.9. This is what I found in there changelog relating to categories for that specific version:

> Fixes a bug in the UI that happend when do_shortcode was run on category descriptions in the admin list. Additionally, fixes rendering of shortcodes in category descriptions on the frontend.

I'll see if I can find the commit and determine whether there's something we can/should do on our end.
EDIT: couldn't find the commit nor test commits because they use specific tools to compile their code.

**Comment by wpsmort** [comment]
I'm closing this because you shouldn't be running Yoast SEO and AIO on the same site and we're the only ones to report this.
