### ISSUE TITLE
Override title / description format at page / post level

### ISSUE THREAD

**Issue by besweeet** [awesomemotive/all-in-one-seo-pack#2067]
I'm very surprised this plugin doesn't have a way of doing this, but it would be great to ignore the global title rewrite settings (among others) for certain pages / posts.

For example, for a page I have, I don't want it to follow the standard `%page_title% | %blog_title%` formatting but rather whatever I set as the actual page title in the WordPress editor.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #924](https://github.com/awesomemotive/aioseop-pro/issues/924) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
I've moved this over to our new repo for inclusion in v4.
