### ISSUE TITLE
Image attributes do not show up in sitemap when added in content

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2077]
The sitemap currently only shows the caption/title attributes for featured images. However, it does not include caption/title attributes for images that are added into the content.

Follow these steps to reproduce the issue:

1. Install AIOSEOP
2. Create a new page
3. Upload a new image, set its title and caption and add it into the content
4. Go to the sitemap and view the source code. You'll see that there are no caption/title attributes

If you then add a featured image to the page, you'll see that it includes caption/title attributes.

**Comment by contactashish13** [comment]
@arnaudbroes what version are you testing with? Some features were rolled back by Ben recently as part of 2.9.1. If you can verify that this was removed from 2.9 which became 2.9.1, it would make it easier.

**Comment by arnaudbroes** [comment]
@contactashish13 agreed.

**Comment by wpsmort** [comment]
This works now so I'm closing it.
