### ISSUE TITLE
Social Meta Module - OG for WhatsApp, Telegram ecc.

### ISSUE THREAD

**Issue by brainssolutions** [awesomemotive/all-in-one-seo-pack#2089]
**Is your feature request related to a problem? Please describe.**
The OG: Image tags With regard to the image in highlight is not displayed the same way on WhatsApp, Telegram etc.

**Describe the solution you'd like**
```
<link itemprop="thumbnailUrl" href="<?php $large_image_url = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID), 'large'); echo $large_image_url[0];
?>"> <span itemprop="thumbnail" itemscope itemtype="http://schema.org/ImageObject"> <link itemprop="url" href="<?php $large_image_url = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID), 'large'); echo $large_image_url[0]; ?>"> </span>
```

**Additional context**
The above mentioned code has been tested on the latest version of WordPress. It would be good to adapt it to your plugin.

**Comment by wpsmort** [comment]
Also requested here - https://github.com/awesomemotive/all-in-one-seo-pack/issues/1627

**Comment by wpsmort** [comment]
I'm closing this as it looks like Whatsapp now uses the standard og:image tag.
