### ISSUE TITLE
Bug - Wrong canonical on paginated article list

### ISSUE THREAD

**Issue by msslovi0** [awesomemotive/all-in-one-seo-pack#2109]
We use the latest version 2.10, we have „Canonical URLs“ on and „No pagination for canonical URLs“ off. However, the canonical on https://www.cross-channel-lawyers.de/page/2/ still points to https://www.cross-channel-lawyers.de/.
Custom canonicals are also turned off.

**Comment by wpsmort** [comment]
@msslovi0 This is a development repository and not a support forum.  Please start by following the troubleshooting steps here - https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/

**Comment by msslovi0** [comment]
The link I followed from Wordpress says „Report a bug“. So I did as this is a bug. If you don't want bug reports, don't put that link in wordpress.

**Comment by wpsmort** [comment]
@msslovi0 I directed you to those troubleshooting steps just to ensure it's not a problem caused by your theme or another plugin.  Can you please send us an Administrator login for your site using the secure form here and we can troubleshoot this - https://semperplugins.com/contact/support-login-information/

**Comment by wpsmort** [comment]
I've confirmed that this is a compatibility issue between AIOSEOP and the Salient WPBakery Page Builder (http://themenectar.com/docs/salient/page-builder-general/) plugin.  This plugin is a modified version of the WP Bakery plugin.  It was modified by Nectar Themes for use with their themes.  

This plugin adds some new elements to the page builder.  One of these elements is a Blog element which will display all the posts from the site.  There are some options, one of which is to set pagination.  When this element is used and pagination is enabled it creates a page 2, 3, etc. of the page.  We're unable to detect that this is happening so we return the canonical URL for the page without the page number.

For example, on page 2 of the homepage we return a canonical of http://domain.com/ when we should return http://domain.com/page/2/

If I deactivate AIOSEOP and check the canonical output by WordPress then it returns http://domain.com/2/ which results in a 404.

On an internal page, neither us or WordPress output the correct canonical with the page number.  

We should look into whether we can improve upon what we're doing now by detecting if we're on a paginated page.  This could be part of the work we do to overhaul canonical URLs in #1631.

I've got a clone of the customer site and a local site with the theme and the Salient WPBakery Page Builder plugin.  

The steps to reproduce this are:
1. Activate the theme and the plugin on a site with at least 2 posts
2. Create a page and, using the page builder, add the Blog element
3. Check the box next to Enable Pagination and set the Posts Per Page to 1
4. View the page and click to navigate to page 2
5. View the source code and check the canonical URL.  You should see the canonical is for the main page and not page 2.

<img width="973" alt="screen shot 2018-12-13 at 6 22 13 pm" src="https://user-images.githubusercontent.com/17548525/49973689-1a3da600-ff04-11e8-8c8a-2d501baa536b.png">
