### ISSUE TITLE
2nd and subsequent pages of paginated homepage have no rel="next" link

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2118]
Works fine on regular pages.

In order to reproduce this, follow these steps:

1. Install All in One SEO Pack Pro on a fresh test site
2. Create a paginated page with at least three pages and set it as the static homepage
3. Go to the second page and check the source code. There should be a rel="next" link to the third page, but there isn't.

**Comment by arnaudbroes** [comment]
@wpsmort please confirm if this, then mark it as "has been reproduced" and assign it to a developer.

**Comment by wpsmort** [comment]
I have been able to reproduce this by following the steps above.

**Comment by arnaudbroes** [comment]
I've also troubleshooted a website where the homepage was paginated using the Advanced Custom Fields plugin and no rel="next" nor rel="prev" links were present in the source code, so the issue could be a bit broader. I've got a clone on CW.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #902](https://github.com/awesomemotive/aioseop-pro/issues/902) via [**ZenHub**](https://www.zenhub.com/)
