### ISSUE TITLE
Hide Exclude Categories when there are no categories besides uncategorized

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2138]
This is just a minor thing we could improve. Might not be needed after https://github.com/semperfiwebdesign/aioseop-pro/issues/240.

![image](https://user-images.githubusercontent.com/18156697/50993989-4c4e2200-151b-11e9-8d45-618c466b3ce3.png)

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #833](https://github.com/awesomemotive/aioseop-pro/issues/833) via [**ZenHub**](https://www.zenhub.com/)
