### ISSUE TITLE
Social Meta - Update the list of Facebook Object Types

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#2140]
Requested here - https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/cant-change-facebook-object-type/

We need to update the list of Facebook Object Types in the drop down in the main Social Meta settings and on the Social Settings tab on the Edit Post screen.

Here's the current list of Facebook Object Types: https://developers.facebook.com/docs/reference/opengraph#object-type

We need to determine what to do for backwards compatibility if someone has set an Object Type that is no longer valid.  My recommendation would be to fall back to a default of Article.

**Comment by wpsmort** [comment]
Here's the new list of Open Graph types:
```
'Websites' => array(
	'article' => __( 'Article', 'all-in-one-seo-pack' ),
	'website' => __( 'Website', 'all-in-one-seo-pack' ),
),
'Music'    => array(
	'music.song'          => __( 'Song', 'all-in-one-seo-pack' ),
	'music.album'         => __( 'Album', 'all-in-one-seo-pack' ),
	'music.playlist'      => __( 'Playlist', 'all-in-one-seo-pack' ),
	'music.radio_station' => __( 'Radio Station', 'all-in-one-seo-pack' ),
),
'Video'    => array(
	'video.movie'   => __( 'Movie', 'all-in-one-seo-pack' ),
	'video.episode' => __( 'Episode', 'all-in-one-seo-pack' ),
	'video.tv_show' => __( 'TV Show', 'all-in-one-seo-pack' ),
	'video.other'   => __( 'Other', 'all-in-one-seo-pack' ),
),
'People'   => array(
	'profile' => __( 'Profile', 'all-in-one-seo-pack' ),
),
'Other'    => array(
	'book' => __( 'Book', 'all-in-one-seo-pack' ),
),
```

This will need a database migration to map the following OG Types from current to new:

Song
Album
Movie
Episode
TV Show

Anything not in the new list should default to Article.

@arnaudbroes Do you want to do the development on this?

**Comment by arnaudbroes** [comment]
@wpsmort that works for

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #850](https://github.com/awesomemotive/aioseop-pro/issues/850) via [**ZenHub**](https://www.zenhub.com/)
