### ISSUE TITLE
Learnpress LMS lessons display course title instead of own title

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2145]
Looks like our plugin is taking the title of the course instead of the lesson. We might be able to improve this a bit, but someone will need to look into that.

https://wordpress.org/support/topic/lms-site-lessons-are-not-displaying-meta-title-set-at-plugin-2/

**Comment by ninadbe** [comment]
hmm till date no solution

**Comment by wpsmort** [comment]
This has been moved to our new feature request system.
