### ISSUE TITLE
Fix undefined variables in Sitemap ( $prio_options & $freq_options )

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2148]
This is part of the WPCS PR changes that occured from #2084

This appears it could be a possible bug/warning-notice.

Fix areas marked `// TODO Fix undefined variable.`.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L407

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L414

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #800](https://github.com/awesomemotive/aioseop-pro/issues/800) via [**ZenHub**](https://www.zenhub.com/)
