### ISSUE TITLE
Code Refactor - Move Nonce verification

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2150]
This is part of the WPCS PR changes that occured from #2084

There is no nonce security check.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L905

**Comment by EkoJR** [comment]
Nonce verification is called in prior functions. So, this would be more of a refactor of other variables that access global variables `$_POST` & `$_GET` so that they aren't being accessed outside the initial function.

**Comment by arnaudbroes** [comment]
@EkoJR this has to be done in this release.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #826](https://github.com/awesomemotive/aioseop-pro/issues/826) via [**ZenHub**](https://www.zenhub.com/)
