### ISSUE TITLE
Change to prevent direct access to $_POST

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2151]
This is part of the WPCS PR changes that occured from #2084

Areas marked as

`// TODO Add/Change to filter_input().`

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L956

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L959

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L969

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L970

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L971

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #825](https://github.com/awesomemotive/aioseop-pro/issues/825) via [**ZenHub**](https://www.zenhub.com/)
