### ISSUE TITLE
Change urlencode() to rawurlencode()

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2152]
This is part of the WPCS PR changes that occured from #2084

Area marked as 

`// TODO Change urlencode() to rawurlencode().`

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L1641

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #824](https://github.com/awesomemotive/aioseop-pro/issues/824) via [**ZenHub**](https://www.zenhub.com/)
