### ISSUE TITLE
Move All_in_One_SEO_Pack_Sitemap::get_images_from_post() to static aiosp_common

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2156]
Part of restoring some of the old concepts from 2.9 was moving `All_in_One_SEO_Pack_Sitemap::get_images_from_post()` back to the static class `aiosp_common`.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L3347

This would improve code quality and allow other classes methods and functions to use the method.

However, there is growing concern with aiosp_common becoming too cluttered, especially with additional functions being added that `get_images_from_post()` depends on.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #823](https://github.com/awesomemotive/aioseop-pro/issues/823) via [**ZenHub**](https://www.zenhub.com/)
