### ISSUE TITLE
Title - Drop support for %page_title% macro in favour of %post_title%

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2165]
As suggested by Ben in #2142.

> I also think it would help if the plugin would drop %page_title% in favor of just %post_title%; as well as reduce any other %page_*% in favor of %post_*% shortcodes. Both likely operate the same already, and it would reduce code, bugs like this, and confusion.

**Comment by wpsmort** [comment]
This would help address the problem reported here - https://wordpress.org/support/topic/post-title-page_title-error/

**Comment by michaeltorbert** [comment]
Just to be clear, "drop support" could mean we don't explicitly call it page_title, but still support it when used.

**Comment by EkoJR** [comment]
Deprecate might be a better approach. Continue to support it in the backend, but mark it for deprecation and remove the messages/help-text.

**Comment by michaeltorbert** [comment]
@EkoJR We have to _always_ support it in the backend.

**Comment by EkoJR** [comment]
@michaeltorbert That is true. Marking it as deprecate doesn't remove it, but discourages its use.

**Comment by arnaudbroes** [comment]
We'll still support it but remove it from the tooltips just like we did for %blog_title%.
