### ISSUE TITLE
Bug - WP Ultimate Recipe Shortcode output in autogenerated description

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#2170]
Reported by JO (name removed at user request) by email on 11/6/2018.

When the WP Ultimate Recipe plugin is active and the [recipe] shortcode is used in a recipe, the shortcode is output in the autogenerated meta description and og:description.  This bug first occurred in v2.9. 

Steps to reproduce:
1. Install and activate the WP Ultimate Recipe plugin
2. Go to Recipes and publish the Demo Recipe.  Note that the [recipe] shortcode appears in the content area
3. Go to AIOSEOP General Settings and enable SEO for the Recipes post type and enable Run Shortcodes in Autogenerated Descriptions
4. Activate the Social Meta module and enable social meta for the Recipes post type and enable Run Shortcodes in Descriptions
5. View the source code of the demo recipe and you should see the [recipe] shortcode in the meta and og descriptions.  See screenshot below:

Note that this does not happen if you use the [ultimate-recipe] shortcode in a post or page.  It only seems to happen with the [recipe] shortcode.  Not sure if this indicates a problem with the WP Ultimate Recipe plugin or us.

<img width="1357" alt="screen shot 2019-01-29 at 7 41 10 pm" src="https://user-images.githubusercontent.com/17548525/51950497-c0833380-23fe-11e9-96dd-a79342068774.png">

**Comment by arnaudbroes** [comment]
@EkoJR you should be able to easily do this with the conflicting shortcode function we added in aioseop-functions.php.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #869](https://github.com/awesomemotive/aioseop-pro/issues/869) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
I've moved this to our new Github repo for our dev team to work on.
