### ISSUE TITLE
Improve cron jobs with the cron improvements from WP 5.1

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2200]
WP 5.1 added improvements to the cron jobs. [Cron API changes in WordPress 5.1](https://make.wordpress.org/core/2019/01/23/cron-api-changes-in-wordpress-5-1/)

Be sure it is backwards compatible, and may want to create a wrap function for it to be easily removed in the future.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #851](https://github.com/awesomemotive/aioseop-pro/issues/851) via [**ZenHub**](https://www.zenhub.com/)
