### ISSUE TITLE
Investigate/Add improvements to PHPUnit from WP 5.1

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2201]
WP 5.1 made some changes to their PHPUnit testing. most notably...

> Starting in WordPress 5.1, the WP_TESTS_CONFIG_FILE_PATH constant can now be added to the phpunit.xml configuration file to define a custom location for the wp-tests-config.php file.

[Miscellaneous Developer Focused Changes in 5.1](https://make.wordpress.org/core/2019/01/23/miscellaneous-developer-focused-changes-in-5-1/)

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #802](https://github.com/awesomemotive/aioseop-pro/issues/802) via [**ZenHub**](https://www.zenhub.com/)
