### ISSUE TITLE
Review constant definitions

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2207]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/all_in_one_seo_pack.php#L93

We define a bunch of constants like WP_CONTENT_DIR, some of which should already be defined by WP. We should look at why we have these, and whether we should get rid of any.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #822](https://github.com/awesomemotive/aioseop-pro/issues/822) via [**ZenHub**](https://www.zenhub.com/)
