### ISSUE TITLE
General - Add nofollow to user registration and login links

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2216]
This will correct a problem we see a lot of Google indexing admin urls.

We can probably just use the filters lostpassword_url, loginout, and register to do this.

**Comment by michaeltorbert** [comment]
Stuff like this needs to go in its own file.

**Comment by arnaudbroes** [comment]
Shouldn't we instead output noindex,nofollow on those three pages? We could use those filters but I think it will conflict with other plugins who change those links.

**Comment by michaeltorbert** [comment]
We could think about doing that too but I still think we should apply nofollow to the links themselves. It *shouldn't conflict if we just add it. We aren't changing the entire link.

**Comment by arnaudbroes** [comment]
I had a look at it this morning. Looks like we'll have to do it through the screens because, as far as I can see, those filters require the links to be in a 'http://' or 'https://' format and can't be in HTML.

**Comment by michaeltorbert** [comment]
https://core.trac.wordpress.org/browser/tags/5.2.1/src/wp-includes/general-template.php#L0
They're the full HTML so we can just use a string replace function.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #930](https://github.com/awesomemotive/aioseop-pro/issues/930) via [**ZenHub**](https://www.zenhub.com/)
