### ISSUE TITLE
XML Sitemap - Make publish/update ping more obvious

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2219]
Reported here: https://wordpress.org/support/topic/bugs-with-the-sitemap-please-fix-them/

I'm pretty sure we already do this, but maybe we can somehow make it more clear that it's happening? (Feel free to fact-check me.)

Maybe we could put it toward the top of the Sitemap Module settings page with a check next to it.
https://developer.wordpress.org/resource/dashicons/#yes

(checkmark) XML Sitemap generated.
(checkmark) Pinging Google about updates.
(checkmark) Pinging Bing about Updates.

**Comment by arnaudbroes** [comment]
@michaeltorbert I don't think so - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/550

**Comment by wpsmort** [comment]
We removed this notification in #551.

**Comment by michaeltorbert** [comment]
@wpsmort If I'm not mistaken, that just removed the option.

@arnaudbroes Someone can feel free to verify the behavior, but unless I'm missing something, looks like we do it for new posts if static sitemaps are enabled. https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/7550dd8f46ce436216288c3dada2e71ad9929f12/modules/aioseop_sitemap.php#L525

**Comment by arnaudbroes** [comment]
@michaeltorbert I'll run it through Xdebug when I get the chance.

**Comment by wpsmort** [comment]
I verified that we did remove the ping status updates in v2.3.10 (#551).  Here's a screenshot of what the Sitemap Status box looked like before v2.3.10:

<img width="627" alt="screen shot 2019-02-20 at 9 19 58 am" src="https://user-images.githubusercontent.com/17548525/53098127-fb095900-34f0-11e9-9a60-001b69396249.png">

**Comment by michaeltorbert** [comment]
> I verified that we did remove the ping status updates in v2.3.10

I don't think that's what he's asking for. He's asking that AIOSEOP pings Google after a post is published (which we already do for static sitemaps) or updated, and as part of that we'd possibly want to give some indication it's happening.

**Comment by vikingrunes** [comment]
So if Google is pinged instantly whenever a post is published then its not well described in "Schedule Updates:" where options are only Daily, Weekly, Monthly
People will think if they choose "Daily" that Google gets pinged only once a day based on wp-cron instead of an instant action. People will especially believe this after reading the HELP for Schedule Updates which actually says that this action is based on wp-cron which like a "TO DO IN THE FUTURE" action instead of an immediate action. So perhaps another option should be added? Immediately, Daily, Weekly, Monthly.

**Comment by michaeltorbert** [comment]
@vikingrunes You're absolutely correct that this is confusing. What we'd talked about previously was having the pings happen on 1) publish new post 2) updating a published post and 3) daily, and removing the Schedule Updates option. We'd then add in a filter hook so that someone could change this behavior, as most people wouldn't need to.

**Comment by arnaudbroes** [comment]
Related to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1166.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #931](https://github.com/awesomemotive/aioseop-pro/issues/931) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
Moved to new repo for inclusion in v4 release.
