### ISSUE TITLE
XML Sitemap - Include externally hosted images

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2220]
Reported here: https://wordpress.org/support/topic/bugs-with-the-sitemap-please-fix-them/

> Images included in the sitemap are only the ones uploaded on my host but external images such as the ones hosted on photobucket or tinypic aren’t included. This is the most easiest thing to fix, just make the sitemap include all .jpg, .png .gif .bmp extensions found inside a post.

We already support this via filter, but we could explore whether we could do it automatically without a performance hit.

Maybe related: 
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1872
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1258
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1264

**Comment by vikingrunes** [comment]
Where do I need to add that external images hook? In theme’s function.php ? Thanks

**Comment by michaeltorbert** [comment]
@vikingrunes https://semperplugins.com/documentation/how-do-i-use-your-api-code-examples/
