### ISSUE TITLE
Social Meta - Changing default OG:Type doesn't affect posts 

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#2227]
Reported by Kasturi P by email.

When you change the default OG:Type for a post type, it doesn't seem to change the og:type meta tag in the source code for posts in that post type.

**Comment by wpsmort** [comment]
I've been able to reproduce this and I've tested back through the versions of AIO and found that this bug originates in v2.2 of the plugin.

Here's the steps to reproduce:
1. Create a new site and install AIO
2. Activate the Social Meta module and go to it
3. Click Update Options to ensure default settings are written to the database
4. Create a new post and view the source code, the og:type should show "article" which is the default
5. Go back to the Social Meta module and change the Posts Object Type to Movie
6. View the source code of your post and the og:type will still show "article"

Looking at the database, prior to v2.2 the post_meta showed aioseop_opengraph_settings_category as empty, but in v2.2 this changes to article.  It's this value that doesn't get changed when the default Object Type is changed.  

I can think of two options here:
1. We don't store the object type in post_meta unless it's been set for a specific post.  When outputting the og:type, we check if an object type is set in the post_meta for each post and if it's not, we pull the object type from the main AIO options table.

2. We update the post_meta any time the default is object type is changed.  Presumably this is a bad idea for sites with lots of posts and post meta.

@contactashish13 @EkoJR - Please can you review and comment on this.

**Comment by contactashish13** [comment]
@wpsmort when you save a post, it is assumed that the value of the **Facebook Object Type** under the social media tab is being saved. This defaults to the value set under **Posts Object Type in the Social Meta** settings. Therefore when the value of **Posts Object Type** is Article, the default value of **Facebook Object Type** is also Article and the value of the post_meta saved is Article.

When you change the value of the **Posts Object Type in the Social Meta** module to Movie, this means that any new posts will take that value by default. Thus when a new post is saved, its post_meta is Movie. This obviously does not (and should not) affect posts saved previously.

I'm not sure this a bug but maybe a feature that needs to be explained better.

**Comment by wpsmort** [comment]
@contactashish13 I feel that if you change the default Object Type for a post type then it should affect all posts, not just new posts.  It's not good practice to make a user go through every published post tp update them to the new Object Type. 

Given this, which of the two options are the best way to handle this, or is there an alternative option that is better?

**Comment by contactashish13** [comment]
@wpsmort I don't understand why there is an object type defined in the main settings as well in the post when you want the former to always supersede the latter. None of the options you have mentioned make sense to me. From my point of view, we should either remove the per-post setting so that the main object type is used for each post or consider the "bug" not a bug.

**Comment by wpsmort** [comment]
@contactashish13 This allows a user to set a default object type per post type and then override it on an individual post basis if they so wish.  If you change the default, it should change for all posts except any individual posts where the object type has been changed.  

We need the default object type setting because it would be unrealistic to have a user go through all posts to set an object type.  I've opened issue #2231 to discuss removing the object type setting from the individual posts.

For now, let's fix this "bug".

**Comment by michaeltorbert** [comment]
I'm punting this to 3.1 so we can focus on other 3.0 PRs and issues.

**Comment by contactashish13** [comment]
Unfortunately there is no way to tell if the user changed the default just by looking at the value. What if the user deliberately wanted to retain the same value as the default?

I still don't think it's a bug. If it is, then the bug is in the UX or the UI not in the implementation.

**Comment by wpsmort** [comment]
@contactashish13 What about my suggestion here: 

We don't store the object type in post_meta unless it's been set for a specific post.  When outputting the og:type, we check if an object type is set in the post_meta for each post and if it's not, we pull the object type from the main AIO options table.

**Comment by contactashish13** [comment]
@wpsmort Whenever any field under the social meta tab is filled, the post_meta is populated. So, whether you change the drop down or not, it is always populated when the post is saved so I'm not sure why you say 

> We don't store the object type in post_meta unless it's been set for a specific post

**Comment by michaeltorbert** [comment]
We'll need to change the behavior of this so that on a per post basis it notes that it's the default.
Currently, if "actor" is the default, it's just recorded as "actor" for that post, with no indication that is that because it's the default, rather than having it specifically chosen. Therefore, we can't do anything about existing posts at this point. We can only fix it for posts moving forward.

**Comment by michaeltorbert** [comment]
This also applies to other settings as well.
