### ISSUE TITLE
Make SEO columns on All Posts screen sortable 

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2233]
https://codex.wordpress.org/Plugin_API/Filter_Reference/manage_$post_type_sortable_columns

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #852](https://github.com/awesomemotive/aioseop-pro/issues/852) via [**ZenHub**](https://www.zenhub.com/)
