### ISSUE TITLE
Replace "Save Options" buttons with AJAX

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2240]
We might want to consider replacing all "save options" buttons with AJAX and Event Listeners.

**Comment by michaeltorbert** [comment]
If we decide to do this, depending on how the discussion goes, it could be a candidate for including in 3.0.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #829](https://github.com/awesomemotive/aioseop-pro/issues/829) via [**ZenHub**](https://www.zenhub.com/)
