### ISSUE TITLE
New Feature - Add noindex and nofollow to a custom bulk action

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2277]
Requires #2276 and WordPress 4.7

https://make.wordpress.org/core/2016/10/04/custom-bulk-actions/

**Comment by michaeltorbert** [comment]
Requested here: Requested here - https://wordpress.org/support/topic/nofollow-multiple-selection/

**Comment by wpsmort** [comment]
Moved to our feature request system.
