### ISSUE TITLE
Write blog post about title changes

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2279]
We're fixing some title bugs that will change the homepage title for some users. We may want to make a blog post about it.
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/495

I'd say schedule this to publish a few days after the release post.

**Comment by arnaudbroes** [comment]
Pushing this back to 3.1 since #495 has been pushed back to that release.
