### ISSUE TITLE
Title template on specific posts

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2286]
Currently we have a system where you choose (or use defaults) a title template in our options pages... so for instance, posts may have %post_title% | %blog_title% which would make the doc title for a post with the title "This is My Post" and a site title "My Awesome Website" would be "This is My Post | My Awesome Website".
Unfortunately there's no way to override that in the UI on a per post basis. 

We probably should have treated this differently from the beginning, but we need to find a way to improve this behavior that _does not_ include a database migration on upgrading the plugin.

**Comment by arnaudbroes** [comment]
Test

**Comment by wpsmort** [comment]
Dupe of #2067
