### ISSUE TITLE
Bug - Blank homepage title & description when using ProPhoto theme

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2298]
This theme is known to cause issues with the homepage title and description because it hijacks the homepage in a certain way. It's been reported a few times already so I'm assigning this medium priority. I'm also contacting the developer to see if I can get a copy of the theme for dev purposes.

**Comment by arnaudbroes** [comment]
I received the theme file from Benjamin T. who is a support engineer for ProPhoto.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #868](https://github.com/awesomemotive/aioseop-pro/issues/868) via [**ZenHub**](https://www.zenhub.com/)
