### ISSUE TITLE
Video Sitemap - GDPR compliance plugin blocks videos from being detected

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2318]
On https://www.hikeventures.com/kammiovuori/ (video at the bottom), they're using the complianz-gdpr plugin (https://wordpress.org/plugins/complianz-gdpr/) which requires the user to accept cookies. This apparently blocks the video, and so it doesn't show up in the Video Sitemap https://www.hikeventures.com/video-sitemap.xml

I don't know whether this only applies to the Complianz plugin or whether it applies to all GDPR plugins.
I also don't know whether blocking of videos is intentional and is a part of GDPR compliance. 

The Github repo for that plugin is https://github.com/rlankhorst/complianz-gdpr Perhaps @rlankhorst can be of some assistance here.

(I've put this here instead of the private Pro repository so that the conversation about it is public. Any PR should obviously be in the Pro repo.)

**Comment by arnaudbroes** [comment]
Looks like iFrames store external cookies, which explains why cookie consent is needed in order to be compliant with GDPR.

**Comment by rlankhorst** [comment]
Hi @michaeltorbert, 

That is correct, to prevent placement of thirdparty tracking cookies, iframes and scripts like that from youtube etc are blocked, then activated on consent. 

This sitemap is generated based on the actual html output? If there's a request from your plugin which retrieves the video's, setting a constant like CMPLZ_DO_NOT_BLOCK, JSON_REQUEST, XMLRPC_REQUEST or DOING_AJAX,  will prevent the cookie blocker from activating.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #867](https://github.com/awesomemotive/aioseop-pro/issues/867) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
I've moved this to the Pro repo so it gets taken care of in the next major release.
