### ISSUE TITLE
Hard-coded path

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2319]
In Pro we check for the existence of free by way of a hard-coded path to free "all-in-one-seo-pack/". 
a) If free's directory is named something else this won't work.
b) If when making Pro for dev, you have to change the directory name or it will self-deactivate.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/8bdb9d1c564ec607ae10dbe2821fa228e98d094b/all_in_one_seo_pack.php#L509-L510

A fix for this also renders https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2305 obsolete.

**Comment by EkoJR** [comment]
I just want to note, the `AIOSEOP_PLUGIN_DIRNAME` constant could possibly be used here.

**Comment by michaeltorbert** [comment]
That won't work, because we're talking two different plugins.

Pro needs the path to free, not to itself.
