### ISSUE TITLE
SEO Data Importer - Add support for SEOPress

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2320]
Requested here: https://wordpress.org/support/topic/seo-presss-to-all-in-one-seo/#topic-11363222-replies

**Comment by wpsmort** [comment]
Requested again here - https://secure.helpscout.net/conversation/1149895002/677446

**Comment by wpsmort** [comment]
This has been moved to our feature request system.
