### ISSUE TITLE
Sitemap: Index posts on NoIndex post type

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2323]
Currently there is only an option for NoIndex on the post editor, which only NoIndexes on an Indexed Post Type.

This adds the ability to Index posts on NoIndex post types. This may be useful for indexing only a few post from a post type, rather than have to noindex many of the other posts.

**Comment by wpsmort** [comment]
This is already possible.  When a post type is set to Noindex there's a drop down on the Edit Post screen where you can change a post to Index.
