### ISSUE TITLE
Implementation of help text as a helper is procedural and not OOP

### ISSUE THREAD

**Issue by contactashish13** [awesomemotive/all-in-one-seo-pack#2329]
While doing code review for https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2325 I came across a weird implementation that I thought was unnecessary. As explained https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2325#discussion_r272443543

## Why is this required?
- All help text is in one file **even though** the fields that need the help text are defined **per module, in the module**. It does not make sense.
- Help text should also be defined by the **same module** as it defines its own fields. This was the case before and I don't see why it was necessary to create a helper file while doing a refactor.
- This will prevent conflicts in the future e.g. if fields are being added to 2 modules, not only the module files but also this helper file will be changed. This does not make sense.

## How can this be done?
The filter already provided `aioseop_helper_set_help_text` can be implemented in each module and it will add its own help text corresponding to its fields.

## Points against it
- "Plus, I believe calling the method directly would make it more simple. You can go straight to the method/function rather than having to search through the hooks to get to the function. Those methods are also made to be private functions as well."
  - this is not the best argument for keeping this structure when fields are defined by the modules but help text for the fields are defined by the helper file. It is the modules responsibility and should be implemented by the module. I don't see why it was necessary to create a helper file.
- "I can see it making more sense if the hook had a suffix, and might help for extending purposes."
  - this can also be done and will serve the same purpose

@semperfiwebdesign/aioseop-core-committers comments welcome.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #821](https://github.com/awesomemotive/aioseop-pro/issues/821) via [**ZenHub**](https://www.zenhub.com/)
