### ISSUE TITLE
Bug - Character counter broken for categories, tags, etc

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#2337]
Whilst testing PR #2304 I noticed that the character counter is broken on the Edit Category screen.  This applies to the Edit screen for any taxonomy.  The character counter doesn't increment as you type, but it does show the correct number once you click Update.  

The problem affects the character counter on both the Main Settings tab and the Social Settings tab.  I tested and found this broke in the v2.11 release of Pro.  

<img width="1003" alt="Screen Shot 2019-04-16 at 10 21 42 AM" src="https://user-images.githubusercontent.com/17548525/56217872-f1542b80-6031-11e9-9984-917ae849e456.png">

**Comment by wpsmort** [comment]
@arnaudbroes Can you see which commit broke this please.

**Comment by benjaminprojas** [comment]
fixed already
