### ISSUE TITLE
Further encapsulate enqueue scripts to use with the parent class

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2371]
There's a some modules that still use their own method for enqueue scripts rather than the encapsulated method with the parent module base. Ideally, if it is a module, they should use inheritance to implement enqueuing scripts.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #820](https://github.com/awesomemotive/aioseop-pro/issues/820) via [**ZenHub**](https://www.zenhub.com/)
