### ISSUE TITLE
System Status section made redundant by new WP 5.2 Site Health feature

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2375]
WordPress 5.2's new Site Health function has whatever info we output in the System Status section (Perfomance module) and much more so we need to discuss what we want to do/how to proceed.

Should we take it out (and move the remaining features/settings elsewhere)? Do we want to expand it to match the amount of info Site Health has? etc.

![image](https://user-images.githubusercontent.com/18156697/57101412-27123900-6cef-11e9-882f-edb631071d0c.png)

**Comment by michaeltorbert** [comment]
We may want to look into just hooking into the new health check feature: https://make.wordpress.org/core/2019/04/25/site-health-check-in-5-2/

**Comment by wpsmort** [comment]
The Site Health Info screen provides some of the same information that we display in the System Status section of the Performance module.  We could use this to replace our System Status, adding in the additional information we need.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #835](https://github.com/awesomemotive/aioseop-pro/issues/835) via [**ZenHub**](https://www.zenhub.com/)
