### ISSUE TITLE
switch is equivalent to "break" in aioseop_opengraph.php on line 971

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2383]
Reported by Anatolii P. on 5/4/2019 by e-mail.

> Plugin doesn't work   and I start receiving error switch is equivalent to "break". Did you mean to use "continue 2"? in www/wp-content/plugins/all-in-one-seo-pack-pro/modules/aioseop_opengraph.php on line 971

I've requested login credentials so we access his website. He said he's using v2.12.

**Comment by michaeltorbert** [comment]
Is this a duplicate of #2129
