### ISSUE TITLE
i18n - Make Page Frequency options translatable

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2401]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/923c488b60339be714c9a54b4677b901908f7bbc/modules/aioseop_sitemap.php#L253-L255

These options can be translated by using the code below but URLs that are manually added display the translated frequency string in the sitemap so that first has to be addressed.

![image](https://user-images.githubusercontent.com/18156697/57403807-7bfaf700-71a8-11e9-9319-d76bdc660511.png)

```
foreach (
		array(
			'always' => __( 'always', 'all-in-one-seo-pack' ),
			'hourly' => __( 'hourly', 'all-in-one-seo-pack' ),
			'daily' => __( 'daily', 'all-in-one-seo-pack' ),
			'weekly' => __( 'weekly', 'all-in-one-seo-pack' ),
			'monthly' => __( 'monthly', 'all-in-one-seo-pack' ),
			'yearly' => __( 'yearly', 'all-in-one-seo-pack' ),
			'never' => __( 'never', 'all-in-one-seo-pack' ),
) as $f
```

After this issue has been addressed, the plugin is 100% translatable.

**Comment by michaeltorbert** [comment]
The big question is do we even want to make these translatable?

**Comment by arnaudbroes** [comment]
@michaeltorbert I would since all other dropdowns have been made translatable already.

**Comment by michaeltorbert** [comment]
I'm closing this because I'm pretty sure these have to be in English.  https://www.sitemaps.org/protocol.html
Open it back up if you can find an authority source that says otherwise.

**Comment by michaeltorbert** [comment]
Ok I see what you're trying to do. You just want what's displayed to be translated, but the actual value to be English? If so, that code won't do it. Both the display and the value will be translated with that code.

**Comment by arnaudbroes** [comment]
@michaeltorbert that's correct. I'll have to change some things in the code so I'll do it later when we're working on 3.1.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #772](https://github.com/awesomemotive/aioseop-pro/issues/772) via [**ZenHub**](https://www.zenhub.com/)
