### ISSUE TITLE
Use get_post_gallery_images

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2412]
See if we can optimize our code by using get_post_gallery_images().

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/53b0a5f9c74941979d645caa4866145287f7e944/modules/aioseop_sitemap.php#L3435-L3437

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #819](https://github.com/awesomemotive/aioseop-pro/issues/819) via [**ZenHub**](https://www.zenhub.com/)
