### ISSUE TITLE
Documentation - Add doc on how to fix overlapping meta box in Gutenberg

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2416]
>  I was able to confirm again that this isn't coming from our end and found out it happens whenever a plugin (or something else) is outputting something in the source code of the Edit page before the HTML document declaration. In my case, this was WP_DEBUG displaying an error.

We need to add a doc to explain this as I have no doubt people will keep creating bug reports and opening support threads.

**Comment by arnaudbroes** [comment]
Reported again here - https://wordpress.org/support/topic/cant-see-my-text-with-gutenberg-because-of-plung-ins. I'll assign this to 3.3.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #746](https://github.com/awesomemotive/aioseop-pro/issues/746) via [**ZenHub**](https://www.zenhub.com/)
