### ISSUE TITLE
Full Stack RDF for semantic web

### ISSUE THREAD

**Issue by stefanofantin1981** [awesomemotive/all-in-one-seo-pack#2467]
Hello at all,
my name is Stefano Fantin and my opinion is that json linked data are important for big schema and google support json linked data.
The search engine say "if exist to find" so RDF is important to build semantic web page for neural network on rank brain.
My opinion on rank brain is full stack rdf for learning to neural network.
I think that there is not only open graph but also rdf such as

xmlns="http://www.w3.org/1999/xhtml" prefix="og: http://ogp.me/ns# fb: https://www.facebook.com/2008/fbml dcterms: http://purl.org/dc/terms/" lang="it-IT" xmlns:og="http://opengraphprotocol.org/schema/" xmlns:fb="http://developers.facebook.com/schema/"
 xmlns:og="http://ogp.me/ns#"
 xmlns:foaf="http://xmlns.com/foaf/0.1/"
 xmlns:sioc="http://rdfs.org/sioc/ns#"
 xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
 xmlns:skos="http://www.w3.org/2004/02/skos/core#"
 xmlns:moat="http://moat-project.org/ns#"
 xmlns:lh="http://localhero.biz/uri/localhero-namespace/"
 xmlns:dcterms="http://purl.org/dc/terms/"
 xmlns:sioct="http://rdfs.org/sioc/types#"
 xmlns:tag="http://www.holygoat.co.uk/owl/redwood/0.1/tags/"
 xmlns:georss="http://www.georss.org/georss"
 xmlns:wgs84="http://www.w3.org/2003/01/geo/wgs84_pos#"
 xmlns:xfn="http://vocab.sindice.com/xfn#"
 xmlns:owl="http://www.w3.org/2002/07/owl#"
 xmlns:ore="http://www.openarchives.org/ore/terms/"
 xmlns:event="http://purl.org/NET/c4dm/event.owl#"
 xmlns:void="http://rdfs.org/ns/void#"
 xmlns:sc="http://sw.deri.org/2007/07/sitemapextension/scschema.xsd"
 xmlns:ical="http://www.w3.org/2002/12/cal#"
	prefix="og: http://ogp.me/ns#"  prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">

My opinion is to build semantic web page with rdf,
in follow example linked data are:
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
        {
            "@type": "ListItem",
            "position": 1,
            "item": {
                "@id": "https://www.agenzia-web.online",
                "name": "Agenzia Web | Agenzia Web Marketing | Web Agency"
            }
        }
    ]
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "LocalBusiness",
    "name": "Agenzia Web Online",
    "image": "https://www.agenzia-web.online",
    "url": "https://www.agenzia-web.online",
    "telephone": "+39-3423546303",
    "acceptsReservations": "True",
    "address": {
        "@type": "PostalAddress",
        "streetAddress": "solferino 20",
        "addressLocality": "Lainate",
        "postalCode": "20020",
        "addressCountry": "Italia",
        "addressRegion": "Milano"
    },
    "openingHours": [
        "Mo-Su 8:00-24:00"
    ],
    "openingHoursSpecification": {
        "@type": "OpeningHoursSpecification",
        "opens": "8:00",
        "closes": "24:00",
        "validFrom": "",
        "validThrough": ""
    },
    "priceRange": "euro"
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Organization",
    "name": "Agenzia Web Online",
    "url": "https://www.agenzia-web.online",
    "logo": "https://x9i5p3v8.stackpathcdn.com/wp-content/uploads/2019/01/LOGO_AGENZIA-WEB-ONLINE.png",
    "contactPoint": [
        {
            "@type": "ContactPoint",
            "telephone": "+39-3423546303",
            "contactType": "customer service",
            "email": "stefanofantin@icloud.com",
            "areaServed": [
                "US",
                " IT"
            ],
            "availableLanguage": [
                "English",
                " Italian"
            ]
        }
    ]
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Person",
    "name": "Agenzia Web Online",
    "url": "https://www.agenzia-web.online",
    "homeLocation": {
        "@type": "Place",
        "address": {
            "@type": "PostalAddress",
            "addressCountry": "Italy"
        }
    }
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "SiteNavigationElement",
    "name": [
        "Home",
        "Menu",
        "Business Partner",
        "Social Network",
        "Blog",
        "Contatti",
        "<img class=\"wpml-ls-flag\" src=\"https://x9i5p3v8.stackpathcdn.com/wp-content/plugins/sitepress-multilingual-cms/res/flags/en.png\" alt=\"en\" title=\"English\"><span class=\"wpml-ls-native\">English</span><span class=\"wpml-ls-display\"><span class=\"wpml-ls-bracket\"> (</span>Inglese<span class=\"wpml-ls-bracket\">)</span></span>",
        "<img class=\"wpml-ls-flag\" src=\"https://x9i5p3v8.stackpathcdn.com/wp-content/plugins/sitepress-multilingual-cms/res/flags/it.png\" alt=\"it\" title=\"Italiano\"><span class=\"wpml-ls-native\">Italiano</span><span class=\"wpml-ls-display\"><span class=\"wpml-ls-bracket\"> (</span>Italiano<span class=\"wpml-ls-bracket\">)</span></span>",
        "<img class=\"wpml-ls-flag\" src=\"https://x9i5p3v8.stackpathcdn.com/wp-content/plugins/sitepress-multilingual-cms/res/flags/fr.png\" alt=\"fr\" title=\"Français\"><span class=\"wpml-ls-native\">Français</span><span class=\"wpml-ls-display\"><span class=\"wpml-ls-bracket\"> (</span>Francese<span class=\"wpml-ls-bracket\">)</span></span>",
        "<img class=\"wpml-ls-flag\" src=\"https://x9i5p3v8.stackpathcdn.com/wp-content/plugins/sitepress-multilingual-cms/res/flags/es.png\" alt=\"es\" title=\"Español\"><span class=\"wpml-ls-native\">Español</span><span class=\"wpml-ls-display\"><span class=\"wpml-ls-bracket\"> (</span>Spagnolo<span class=\"wpml-ls-bracket\">)</span></span>",
        "<img class=\"wpml-ls-flag\" src=\"https://x9i5p3v8.stackpathcdn.com/wp-content/plugins/sitepress-multilingual-cms/res/flags/de.png\" alt=\"de\" title=\"Deutsch\"><span class=\"wpml-ls-native\">Deutsch</span><span class=\"wpml-ls-display\"><span class=\"wpml-ls-bracket\"> (</span>Tedesco<span class=\"wpml-ls-bracket\">)</span></span>"
    ],
    "url": [
        "https://www.agenzia-web.online/",
        "https://www.agenzia-web.online/menu/",
        "https://www.agenzia-web.online/business-partner/",
        "https://www.agenzia-web.online/social-network/",
        "https://www.agenzia-web.online/blog/",
        "https://www.agenzia-web.online/contatti/",
        "https://www.agenzia-web.online/en/",
        "https://www.agenzia-web.online",
        "https://www.agenzia-web.online/fr/",
        "https://www.agenzia-web.online/es/",
        "https://www.agenzia-web.online/de/"
    ]
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "WebSite",
    "name": "Agenzia Web Online",
    "alternateName": "",
    "url": "https://www.agenzia-web.online",
    "potentialAction": [
        {
            "@type": "SearchAction",
            "target": "{search_term_string}",
            "query-input": "required name=search_term_string"
        },
        {
            "@type": "SearchAction",
            "target": "{search_term_string}",
            "query-input": "required name=search_term_string"
        }
    ]
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "LocalBusiness",
    "name": "Agenzia Web Online",
    "image": "https://www.agenzia-web.online",
    "url": "https://www.agenzia-web.online",
    "telephone": "+39-3423546303",
    "acceptsReservations": "True",
    "address": {
        "@type": "PostalAddress",
        "streetAddress": "solferino 20",
        "addressLocality": "Lainate",
        "postalCode": "20020",
        "addressCountry": "Italia",
        "addressRegion": "Milano"
    },
    "openingHours": [
        "Mo-Su 8:00-24:00"
    ],
    "openingHoursSpecification": {
        "@type": "OpeningHoursSpecification",
        "opens": "8:00",
        "closes": "24:00",
        "validFrom": "",
        "validThrough": ""
    },
    "priceRange": "euro"
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Organization",
    "name": "Agenzia Web Online",
    "url": "https://www.agenzia-web.online",
    "logo": "https://x9i5p3v8.stackpathcdn.com/wp-content/uploads/2019/01/LOGO_AGENZIA-WEB-ONLINE.png",
    "contactPoint": [
        {
            "@type": "ContactPoint",
            "telephone": "+39-3423546303",
            "contactType": "customer service",
            "email": "stefanofantin@icloud.com",
            "areaServed": [
                "US",
                " IT"
            ],
            "availableLanguage": [
                "English",
                " Italian"
            ]
        }
    ]
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Person",
    "name": "Agenzia Web Online",
    "url": "https://www.agenzia-web.online",
    "homeLocation": {
        "@type": "Place",
        "address": {
            "@type": "PostalAddress",
            "addressCountry": "Italy"
        }
    }
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "SiteNavigationElement",
    "name": [
        "Home",
        "Menu",
        "Business Partner",
        "Social Network",
        "Blog",
        "Contatti",
        "<img class=\"wpml-ls-flag\" src=\"https://x9i5p3v8.stackpathcdn.com/wp-content/plugins/sitepress-multilingual-cms/res/flags/en.png\" alt=\"en\" title=\"English\"><span class=\"wpml-ls-native\">English</span><span class=\"wpml-ls-display\"><span class=\"wpml-ls-bracket\"> (</span>Inglese<span class=\"wpml-ls-bracket\">)</span></span>",
        "<img class=\"wpml-ls-flag\" src=\"https://x9i5p3v8.stackpathcdn.com/wp-content/plugins/sitepress-multilingual-cms/res/flags/it.png\" alt=\"it\" title=\"Italiano\"><span class=\"wpml-ls-native\">Italiano</span><span class=\"wpml-ls-display\"><span class=\"wpml-ls-bracket\"> (</span>Italiano<span class=\"wpml-ls-bracket\">)</span></span>",
        "<img class=\"wpml-ls-flag\" src=\"https://x9i5p3v8.stackpathcdn.com/wp-content/plugins/sitepress-multilingual-cms/res/flags/fr.png\" alt=\"fr\" title=\"Français\"><span class=\"wpml-ls-native\">Français</span><span class=\"wpml-ls-display\"><span class=\"wpml-ls-bracket\"> (</span>Francese<span class=\"wpml-ls-bracket\">)</span></span>",
        "<img class=\"wpml-ls-flag\" src=\"https://x9i5p3v8.stackpathcdn.com/wp-content/plugins/sitepress-multilingual-cms/res/flags/es.png\" alt=\"es\" title=\"Español\"><span class=\"wpml-ls-native\">Español</span><span class=\"wpml-ls-display\"><span class=\"wpml-ls-bracket\"> (</span>Spagnolo<span class=\"wpml-ls-bracket\">)</span></span>",
        "<img class=\"wpml-ls-flag\" src=\"https://x9i5p3v8.stackpathcdn.com/wp-content/plugins/sitepress-multilingual-cms/res/flags/de.png\" alt=\"de\" title=\"Deutsch\"><span class=\"wpml-ls-native\">Deutsch</span><span class=\"wpml-ls-display\"><span class=\"wpml-ls-bracket\"> (</span>Tedesco<span class=\"wpml-ls-bracket\">)</span></span>"
    ],
    "url": [
        "https://www.agenzia-web.online/",
        "https://www.agenzia-web.online/menu/",
        "https://www.agenzia-web.online/business-partner/",
        "https://www.agenzia-web.online/social-network/",
        "https://www.agenzia-web.online/blog/",
        "https://www.agenzia-web.online/contatti/",
        "https://www.agenzia-web.online/en/",
        "https://www.agenzia-web.online",
        "https://www.agenzia-web.online/fr/",
        "https://www.agenzia-web.online/es/",
        "https://www.agenzia-web.online/de/"
    ]
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "WebSite",
    "name": "Agenzia Web Online",
    "alternateName": "",
    "url": "https://www.agenzia-web.online",
    "potentialAction": [
        {
            "@type": "SearchAction",
            "target": "{search_term_string}",
            "query-input": "required name=search_term_string"
        },
        {
            "@type": "SearchAction",
            "target": "{search_term_string}",
            "query-input": "required name=search_term_string"
        }
    ]
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Article",
    "mainEntityOfPage": {
        "@type": "WebPage",
        "@id": "https://www.agenzia-web.online/"
    },
    "headline": "Agenzia Web | Agenzia Web Marketing | Web Agency",
    "datePublished": "2018-02-16T17:38:01+0000",
    "dateModified": "2019-05-09T18:34:57+0000",
    "author": {
        "@type": "Person",
        "name": "Stefano Fantin"
    },
    "description": "Benvenuto nel nuovo sito di agenzia-web.online ;siamo una agenzia web e una agenzia di web marketing, &nbsp;ci",
    "publisher": {
        "@type": "Organization",
        "name": "Agenzia Web Online"
    }
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "BlogPosting",
    "mainEntityOfPage": {
        "@type": "WebPage",
        "@id": "https://www.agenzia-web.online/"
    },
    "headline": "Agenzia Web | Agenzia Web Marketing | Web Agency",
    "datePublished": "2018-02-16T17:38:01+0000",
    "dateModified": "2019-05-09T18:34:57+0000",
    "author": {
        "@type": "Person",
        "name": "Stefano Fantin"
    },
    "description": "Benvenuto nel nuovo sito di agenzia-web.online ;siamo una agenzia web e una agenzia di web marketing, &nbsp;ci",
    "publisher": {
        "@type": "Organization",
        "name": "Agenzia Web Online"
    }
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "LocalBusiness",
    "name": "Agenzia Web Online",
    "image": "https://www.agenzia-web.online",
    "url": "https://www.agenzia-web.online",
    "telephone": "+39-3423546303",
    "acceptsReservations": "True",
    "address": {
        "@type": "PostalAddress",
        "streetAddress": "solferino 20",
        "addressLocality": "Lainate",
        "postalCode": "20020",
        "addressCountry": "Italia",
        "addressRegion": "Milano"
    },
    "openingHours": [
        "Mo-Su 8:00-24:00"
    ],
    "openingHoursSpecification": {
        "@type": "OpeningHoursSpecification",
        "opens": "8:00",
        "closes": "24:00",
        "validFrom": "",
        "validThrough": ""
    },
    "priceRange": "euro"
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "NewsArticle",
    "mainEntityOfPage": {
        "@type": "WebPage",
        "@id": "https://www.agenzia-web.online/"
    },
    "headline": "Agenzia Web | Agenzia Web Marketing | Web Agency",
    "datePublished": "2018-02-16T17:38:01+0000",
    "dateModified": "2019-05-09T18:34:57+0000",
    "author": {
        "@type": "Person",
        "name": "Stefano Fantin"
    },
    "description": "Benvenuto nel nuovo sito di agenzia-web.online ;siamo una agenzia web e una agenzia di web marketing, &nbsp;ci",
    "publisher": {
        "@type": "Organization",
        "name": "Agenzia Web Online",
        "logo": {
            "@type": "ImageObject",
            "url": "https://x9i5p3v8.stackpathcdn.com/wp-content/uploads/2019/01/LOGO_AGENZIA-WEB-ONLINE.png",
            "width": 514,
            "height": 290
        }
    }
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Organization",
    "name": "Agenzia Web Online",
    "url": "https://www.agenzia-web.online",
    "logo": "https://x9i5p3v8.stackpathcdn.com/wp-content/uploads/2019/01/LOGO_AGENZIA-WEB-ONLINE.png",
    "contactPoint": [
        {
            "@type": "ContactPoint",
            "telephone": "+39-3423546303",
            "contactType": "customer service",
            "email": "stefanofantin@icloud.com",
            "areaServed": [
                "US",
                " IT"
            ],
            "availableLanguage": [
                "English",
                " Italian"
            ]
        }
    ]
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Person",
    "name": "Agenzia Web Online",
    "url": "https://www.agenzia-web.online",
    "homeLocation": {
        "@type": "Place",
        "address": {
            "@type": "PostalAddress",
            "addressCountry": "Italy"
        }
    }
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "WebSite",
    "name": "Agenzia Web Online",
    "alternateName": "",
    "url": "https://www.agenzia-web.online",
    "potentialAction": [
        {
            "@type": "SearchAction",
            "target": "{search_term_string}",
            "query-input": "required name=search_term_string"
        },
        {
            "@type": "SearchAction",
            "target": "{search_term_string}",
            "query-input": "required name=search_term_string"
        }
    ]
}

but are not to build semantic web page.
The open graph is the fundamentals of search engine but the rdf is the support as fundamentals :
Example of semantic web pages are to add file such as:
<link rel="meta" type="application/json" title="SIOC"  href="https://www.agenzia-web.online/?feed=lhrdf&format=json" />
<link rel="meta" type="text/n3" title="SIOC"  href="https://www.agenzia-web.online/?feed=lhrdf&format=n3" />
<link rel="meta" type="application/n-triples" title="SIOC"  href="https://www.agenzia-web.online/?feed=lhrdf&format=ntriples" />
<link rel="meta" type="application/x-httpd-php-source" title="SIOC"  href="https://www.agenzia-web.online/?feed=lhrdf&format=php" />
<link rel="meta" type="application/rdf+xml" title="SIOC"  href="https://www.agenzia-web.online/?feed=lhrdf&format=rdfxml" />
<link rel="meta" type="text/turtle" title="SIOC"  href="https://www.agenzia-web.online/?feed=lhrdf&format=turtle" />
and more of other type of web pages.

That I have write is my opinion of ceo of Italian web agency that would improve your plugin for the best seo plugin in Wordpress.

Best regards
Stefano Fantin
my url is:
https://www.agenzia-web.online

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by wpsmort** [comment]
This has been moved to our new feature request system.
