### ISSUE TITLE
Yandex reports duplicate user-agent (*)

### ISSUE THREAD

**Issue by hatakealex** [awesomemotive/all-in-one-seo-pack#2487]
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php

User-agent: *
Disallow: /cgi-bin/
Disallow: /?/
Disallow: /wp-/
Disallow: /*?s=/
....

**Comment by arnaudbroes** [comment]
This is a development repository; not a support forum. Please purchase a license for All in One SEO Pack Pro if you'd like to gain access to our support resources - https://semperplugins.com/all-in-one-seo-pack-pro-version/

**Comment by hatakealex** [comment]
I do not ask for support, I report an error

**Comment by arnaudbroes** [comment]
It's not an error.

**Comment by hatakealex** [comment]
Yandex.Webmaster displays as an error

**Comment by hatakealex** [comment]
I understood you, I simply informed. all the best

**Comment by arnaudbroes** [comment]
@hatakealex can you show us a screenshot of the error that Yandex is reporting to you?

**Comment by hatakealex** [comment]
https://ibb.co/BKx2pNw

**Comment by arnaudbroes** [comment]
@hatakealex thanks, we'll take a look at it!

**Comment by arnaudbroes** [comment]
I've confirmed this. We'll have to discuss whether this is an actual issue, see whether it affects other search engines as well and then decide whether we want to something about it.

![image](https://user-images.githubusercontent.com/18156697/58987863-be801580-87e0-11e9-80db-e879d56bea8d.png)

**Comment by shchastny** [comment]
Проблема актуальна

**Comment by wpsmort** [comment]
Reported again by David by contact form.

**Comment by adnankhan250** [comment]
Yeh Rishta Kya Kehlata is indian star plus drama serial started on 2009.
Its cast involve naira and kartik they have good chemistry in love and other.

<a href="https://yehrishtakyakehlatahai.su/">Yeh Rishta Kya Kehlata Hai</a>

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #859](https://github.com/awesomemotive/aioseop-pro/issues/859) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
I'm moving this to our new repo for the code refactor so this can be dealt with as part of that project.
