### ISSUE TITLE
dismissed notices in database

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#25]
We should store this better so that we can eventually have lots of notices.

**Comment by michaeltorbert** [comment]
Related to #43

**Comment by EkoJr** [comment]
I added this concept to the Notice Management Class. Notices are inserted, and de/activated when no longer in use, but can remain stored on the Database. There is a remove method added, but is intended for deprecated and obsolete notices.

https://github.com/EkoJr/all-in-one-seo-pack/commit/c84a9364193f80c7d6dbaac3c3333e265f988072

**Comment by arnaudbroes** [comment]
As Ben mentioned before, this has already been implemented.

**Comment by adnankhan250** [comment]
https://barristerbabu.su/episodes/
Barrister Babu is a Hindi language Indian Television serial on 
Colors TV of 2020. This tv serial features Madhushree Sharma

**Comment by adnankhan250** [comment]
[Barrister Babu](url) is a Hindi language Indian Television serial on 
Colors TV of 2020. This tv serial features Madhushree Sharma

<a href="https://desiserialapnetv.su/">Desi Serial</a>

**Comment by adnankhan250** [comment]
Welcome to DesiSerials Youtube Channel. We exhibit desi serial channels 
broadcast online. Desi TV Serial that are loved by people around the world.

<a href="https://desiserialapnetv.su/">Desi Serial</a>

**Comment by adnankhan250** [comment]
Barrister Babu is a Hindi language Indian Television serial on 
Colors TV of 2020. This tv serial features Madhushree Sharma

<a href="https://barristerbabu.su/author/colorstv/">Colors Tv Dramas</a>
