### ISSUE TITLE
Code Refactor - Pointer code should be removed

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2502]
Saw we had pointers back in the early days and I'm not sure why we're not using them anymore since we definitely should -
![image](https://user-images.githubusercontent.com/18156697/58375868-697d0d80-7f5d-11e9-9d67-537df493b0a2.png)

Also, we should remove old pointer content from new releases since it's still in there.

**Comment by arnaudbroes** [comment]
Related to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/187.

**Comment by wpsmort** [comment]
I was not a fan of these pointers when we implemented them.  I'd rather we 1). introduce our dashboard for notices, and 2). implement a setup wizard.

**Comment by arnaudbroes** [comment]
Agreed. In the meantime I'll remove the remaining code.

**Comment by tonyzeoli** [comment]
I like the setup wizard idea.


[image: photo]
Tony Zeoli
Founder, Digital Strategy Works LLC
O  (828) 412-0990  <(828) 412-0990> M  (917) 705-4700  <(917)
705-4700> E  az@digitalstrategyworks.com
<az@digitalstrategyworks.com>
W  https://digitalstrategyworks.com
Whatsapp 9177054700
Skype tonyzeoli
<http://www.facebook.com/digitalstrategyworks>
<http://www.twitter.com/dswks>
<http://www.linkedin.com/company/digital-strategy-works>
<http://plus.google.com/digitalstrategyworks>
<http://slideshare.com/tonyzeoli> <http://about.me/tonyzeoli>
<http://angel.co/tonyzeoli>
<https://calendly.com/tonyzeoli> Schedule a 30-minute Meeting
<https://calendly.com/tonyzeoli>
<https://digitalstrategyworks.com/drupal-to-wordpress-migration-for-bookstr-com/2019/02/05/2575/>
Latest
post: Drupal to WordPress Migration for Bookstr.com
<https://digitalstrategyworks.com/drupal-to-wordpress-migration-for-bookstr-com/2019/02/05/2575/>
<https://facebook.com/digitalstrategyworks>   <https://twitter.com/dswks>
<https://linkedin.com/in/+tonyzeoli>
<https://www.youtube.com/+digitalstrategyworks>


<https://gsuite.google.com/landing/partners/referral/trial.html?utm_source=sign-up&utm_medium=referralbutton1&utm_campaign=apps-referral-program&utm_content=https://goo.gl/BG4yH8>

**Comment by michaeltorbert** [comment]
@tonyzeoli Anything in particular you'd like it to do?

**Comment by arnaudbroes** [comment]
This is done.
