### ISSUE TITLE
Refactor instance for Save Settings to an earlier WP hook

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2544]
Currently, saving the plugin settings occurs with `\All_in_One_SEO_Pack_Module::handle_settings_updates()` only during the `\All_in_One_SEO_Pack_Module::display_settings_page()` method; which is hooked in the callback for `add_menu_page()`, `add_submenu_page()`, & `\All_in_One_SEO_Pack_Module::__call()`.

It's isolated to its own aioseop screens, which is good. The problem is, saving the settings and displaying the page are so close together, that it makes it difficult to find any median in-between, and that would also allow operations across all WP screens. Saving settings also occurs later than expected, causing other operations that require an earlier hook to miss the new settings.

It would probably be better to have the save settings methods hooked into a WP hook as early in the instance as possible. So that it is easier for later hooks to reflect the changes.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #817](https://github.com/awesomemotive/aioseop-pro/issues/817) via [**ZenHub**](https://www.zenhub.com/)
