### ISSUE TITLE
Phase out force rewrites option

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#255]
Force rewrites is on by default. We shouldn't need force rewrites (output buffering) for a properly coded theme. Even themes like twentyfifteen, etc require it though. We should look into making sure we handle titles in good themes so that we don't require OB so often.

**Comment by michaeltorbert** [comment]
Depends on https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/877 and https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1007

**Comment by wpsmort** [comment]
Replaced by https://github.com/awesomemotive/aioseop-pro/issues/52
