### ISSUE TITLE
Correct spelling of ecommerce

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2560]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/523cefc39a2291e816d3bdbd716e2a0c72908efe/all_in_one_seo_pack.php#L6

eCommerce? e-commerce?

**Comment by arnaudbroes** [comment]
ecommerce is used more than e-commerce as search term so I'd go with eCommerce.

**Comment by michaeltorbert** [comment]
I'm curious about regional variations. @arnaudbroes  Can you check out the glossaries for the various WP locales?
