### ISSUE TITLE
WooCommerce notice button to dismiss forever

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2564]
Requested here: https://wordpress.org/support/topic/woocommerce-pro-upgrade-nag-notice/

We currently have buttons to upgrade and to dismiss for 30 days. We may want to change this to something like:

"Upgrade"
"Remind me later"
"Never show me this again"

Thoughts?

**Comment by 7thcirclegit** [comment]
I would suggest not showing it in the primary dashboard, but then the options under the plugin should be as you suggest.

**Comment by arnaudbroes** [comment]
I'd like for us to show it on the Edit Product and Edit Product Category screen too.

**Comment by t8pe** [comment]
Right now you're showing a nag every time I go to the main WordPress dashboard, and the options are "Upgrade" and "No Thanks" - but No Thanks just means it's going to nag me again... and again... Dismissing for 30 days would be fine.

**Comment by michaeltorbert** [comment]
@t8pe Are you saying it isn't dismissing for you?

**Comment by EkoJR** [comment]
There is a WP Community Constant DISABLE_NAG_NOTICES to prevent any nag messages.

`define('DISABLE_NAG_NOTICES', true);`

**Comment by michaeltorbert** [comment]
@t8pe  The new tab bug will be fixed in 3.0.2. We *hope that the bug about not being able to dismiss it will be fixed as well, but so far we've been unable to reliably reproduce it.
If you'd like to let us investigate the state of your site so we can develop a fix, you can submit your login info to our secure form here: https://semperplugins.com/contact/support-login-information/

**Comment by wpsmort** [comment]
We have a PR open for v3.4.3 here - https://github.com/awesomemotive/aioseop-pro/pull/740
