### ISSUE TITLE
Code Refactor - Change metabox icons to dashicons

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2584]
In #1154 we started using font-icons.

Even better would be to use the built-in dashicons. https://developer.wordpress.org/resource/dashicons/#arrow-right-alt2

There's nearly a 1:1 replacements for each.

**Comment by arnaudbroes** [comment]
Related to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1157.
