### ISSUE TITLE
XML Sitemap - Sitemap shows non-existing pages

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2596]
Related to #1834 
Reported https://wordpress.org/support/topic/sitemap-has-nonexistent-pages/#post-11607939

Based on the info we have, it looks like a post type Portfolio was created by an old theme, some portfolio entries were added, and some images were attached to them.
The post type registration was then removed (switched themes) but the pages are in the database, public, and published, but they're 404 on the site.

The attachments are configured to redirect to post parent, which in this case is the above 404ed portfolio post.
This creates two issues... 
1) #1834 attachments redirecting to post parent 404, because we're incorrectly picking up these "posts". This may be a bug in WordPress itself?
2) This issue, which is that these attachment pages show up in the sitemap. We need to discuss how to handle that. Should attachment pages that are redirecting anyway (even to a page that doesn't 404) show up in the sitemap at all, assuming what they're redirecting to is there?

**Comment by wpsmort** [comment]
The same steps to reproduce can be used here https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1834#issuecomment-523216429
