### ISSUE TITLE
Bug - Issue with WPML after updating to v3.x

### ISSUE THREAD

**Issue by leandroprz** [awesomemotive/all-in-one-seo-pack#2625]
Please fill out this form as completely as possible so that we can help you more quickly.

- [x] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Provide the relevant URL(s) here**
http://leandroperez.com.ar

**Describe the bug**
What happened?
What did you expect to happen?

I'm using WPML to add a second language to my site. After updating to v3.x of All in One SEO Pack, my home title and home description got changed to the second language (English) instead of mantaining the first one (Spanish). This happened from v3.0.0 to v3.0.4, every update changed my strings.

**To Reproduce**
1. Install WPML. Add a second language. Translate the home description and home title strings.
2. Update All in One SEO Pack to v3.x
3. The home title and home description strings will change to the second language.

**Expected behavior**
I expected not to see a change in my strings.

**Screenshots**

**Version Info (please complete the following information):**
 - WordPress version: 4.9.10
 - All in One SEO Pack version: 3.0.4
 - PHP version: 7.0
- WPML Multilingual CMS: 4.2.6
- WPML String Translation 2.10.4
- WPML Translation Management 2.8.5

**Additional context**

**Comment by wpsmort** [comment]
I am not able to reproduce this.  I tested updating from 3.0 to all releases since then and the translated strings were present in the front end and in the database.
