### ISSUE TITLE
XML Sitemap - Include additional namespaces

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#2628]
We should consider including the additional namespaces in our XML Sitemaps (these do not need to be added to the main sitemap index, only the sitemaps within the index):

```
<urlset 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" 
	xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 
	http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd 
	http://www.google.com/schemas/sitemap-image/1.1 
	http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" 
	xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
```

Here's our current namespaces:

```
<urlset 
	xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" 
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
```

**Comment by wpsmort** [comment]
I found this documentation on valid namespaces for XML Sitemaps - https://www.sitemaps.org/protocol.html#validating

Based on this, we need to implement the following changes:

We should output the following for sitemap indexes only:
```
<sitemapindex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd"
	xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
```

We should output the following for sitemaps within an index:
```
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd"
	xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
```

We should output the following for the video sitemap:
```
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"
	xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-video/1.1/ http://www.google.com/schemas/sitemap-video/1.1/sitemap-video.xsd"
	xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
```

**Comment by arnaudbroes** [comment]
@wpsmort can you tell me what the difference is between "sitemap indexes only" and "sitemaps with an index"?

**Comment by wpsmort** [comment]
@arnaudbroes The sitemap indexes only refers to the index page that lists the sitemaps.  See screenshot below:

<img width="791" alt="Screen Shot 2019-07-08 at 9 50 06 AM" src="https://user-images.githubusercontent.com/17548525/60815515-ccb9ac80-a165-11e9-97fe-3668f65aaa06.png">

The sitemaps within an index refers to the individual sitemaps that are listed within the index file (or the main sitemap is sitemap indexes is disabled).

**Comment by michaeltorbert** [comment]
The way to do this is probably to add our own filter: aiosp_sitemap_xml_namespace

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #853](https://github.com/awesomemotive/aioseop-pro/issues/853) via [**ZenHub**](https://www.zenhub.com/)
