### ISSUE TITLE
Robots.txt - Add robots testing tool

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#2703]
Google has open-sourced the code they use for parsing robots.txt files and this includes a testing tool - https://webmasters.googleblog.com/2019/07/repp-oss.html

The code can be found here - https://github.com/google/robotstxt 

We should look at whether we want to incorporate this into AIO for users to test and validate their robots.txt

**Comment by arnaudbroes** [comment]
I like the idea. This might require a bit of work though because their code is written in C++ and will need to be ported to PHP.
