### ISSUE TITLE
Bug - Add missing macros for preview snippet title

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2718]
While testing https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2705 Steve found that a bunch of macros, such as the author related ones, never were included in the code for the preview snippet title. I'll check which ones are missing and add them after https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2705 is merged.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #906](https://github.com/awesomemotive/aioseop-pro/issues/906) via [**ZenHub**](https://www.zenhub.com/)
