### ISSUE TITLE
Fetch correct ID for static posts page/Woocommerce shop page in get_current_options()

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2729]
Currently we use the ID that's part of the global $post variable. 
In the case of these two pages, this does not reflect the actual ID of the page but rather the first post/product appearing on that page. This causes issues when we e.g. need to fetch the noindex/nofollow values for that page.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #816](https://github.com/awesomemotive/aioseop-pro/issues/816) via [**ZenHub**](https://www.zenhub.com/)
