### ISSUE TITLE
Add CSS Class 'aioseop_count_chars' to default_options

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2746]
Refactor https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a9f2bb6b607c6b6720ff6d702acd0628b6119304/admin/aioseop_module_class.php#L2296
```
if ( ! empty( $options['count'] ) ) {
	$n ++;
	$classes = isset( $options['class'] ) ? $options['class'] : '';
	$classes .= ' aioseop_count_chars';
	$attr .= " class='{$classes}' data-length-field='{$prefix}length$n'";
}
```
Into a module's `*->default_options` as

`'class'      => 'aioseop_count_chars',`

It's what was initially intended for the following reasons. 

1) It's organized with setting's layout configs.
2) Allows more control

# Additional Info
PR that created it - https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1412
PR that removed the initial operations - https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2740

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #854](https://github.com/awesomemotive/aioseop-pro/issues/854) via [**ZenHub**](https://www.zenhub.com/)
