### ISSUE TITLE
Bug - Run Shortcodes in Autogenerated Descriptions doesn't affect the Preview Snippet 

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2754]
As reported here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2736#issuecomment-516996965.

**Comment by wpsmort** [comment]
Reported again here - https://secure.helpscout.net/conversation/1076779545/623803?folderId=3532975

**Comment by wpsmort** [comment]
Reported again here - https://secure.helpscout.net/conversation/1092782088/635200?folderId=3532975

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #907](https://github.com/awesomemotive/aioseop-pro/issues/907) via [**ZenHub**](https://www.zenhub.com/)
