### ISSUE TITLE
UX - Improve Phone Number field in Schema Settings

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#2764]
We need to look at improving the Phone Number field so that it's easier for users to enter the phone number with the country code, i.e. 1-888-888-8888.

**Comment by arnaudbroes** [comment]
We might be abe to use something like https://intl-tel-input.com/

**Comment by michaeltorbert** [comment]
Reported by Tim via email.
-------- 

According to https://developers.google.com/search/docs/data-types/corporate-contact#definitions, the country code should include a "+". 
If this is the case, we should enforce this on our end.

Strangely, in example 2, this doesn't seem to be the case: https://schema.org/telephone

This needs to be verified, and if there's a change, we need to update our documentation to be more specific.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #836](https://github.com/awesomemotive/aioseop-pro/issues/836) via [**ZenHub**](https://www.zenhub.com/)
