### ISSUE TITLE
Schema.org - Use post_content/meta description for Schema description

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2790]
Let's fix what we took out in https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2786#issuecomment-518433672.

Also, let's make sure that we skip the excerpt if aioseop_skip_excerpt is set in the General Settings menu @EkoJR.

**Comment by wpsmort** [comment]
This should wait until we refactor the code that generates the meta description and move that code to its own file.

**Comment by arnaudbroes** [comment]
> This should wait until we refactor the code that generates the meta description and move that code to its own file.

I'm moving this up to 3.4 then.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #855](https://github.com/awesomemotive/aioseop-pro/issues/855) via [**ZenHub**](https://www.zenhub.com/)
