### ISSUE TITLE
XML Sitemap - Support for GTranslate

### ISSUE THREAD

**Issue by OramSrl** [awesomemotive/all-in-one-seo-pack#2795]
Compatibility with the multilanguage plugin GTranslate (https://gtranslate.io/) for wordpress.
This plugin can create multiple subdirectories for language, can be used with second-level domain or localized first level domain with automatic machine learning translation + the ability to correct every single translation or string, wich is totally great.

Hope this can be possible in the future.
Kind regards and great work with the latest updates.

**Comment by michaeltorbert** [comment]
Hi @OramSrl 

Thank you for your input. Please provide the specifics about the compatibility you'd like to see.

**Comment by wpsmort** [comment]
I'm closing this in favor of #102 which covers support for all translation plugins.
