### ISSUE TITLE
Dev Env - Implement GitHub actions

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2822]
GitHub just launched a new task runner feature and I'm sure there's great stuff we could add or automate such as the [greeting for new contributors](https://github.com/actions/starter-workflows/blob/master/automation/greetings.yml) and issue triaging.

https://help.github.com/en/articles/about-github-actions

I for one would love labeling new issues from non-team members with "Initial review".

**Comment by michaeltorbert** [comment]
Love this!

**Comment by michaeltorbert** [comment]
Here's one we may want to consider https://github.com/10up/action-wordpress-plugin-deploy

**Comment by michaeltorbert** [comment]
Yeah it's probably not worth the money we'd have to pay.

**Comment by arnaudbroes** [comment]
I'll just reopen this on the off-chance we still want to switch plans.
