### ISSUE TITLE
Social Meta - Add support For editing OG:url

### ISSUE THREAD

**Issue by mackenly** [awesomemotive/all-in-one-seo-pack#2824]
By adding support for editing og:url users would be able to use GIFs as their Facebook preview image as described here: http://voidcanvas.com/how-to-display-gif-thumbnail-while-sharing-the-webpage-in-facebook/

**Comment by arnaudbroes** [comment]
I've quickly tested this and this does works so I'm open to the idea. The only concern I have is that this would add yet another field to the social meta tab while this is already possible through this filter - https://semperplugins.com/documentation/aiosp_opengraph_meta/

**Comment by mackenly** [comment]
@arnaudbroes That makes sense. What if the field could be enabled/disabled via a check box in the plugin settings that defaults to disabled? That would allow users that want to use the option to use it and it wouldn't be in the way of users who do not (probably the majority).

**Comment by arnaudbroes** [comment]
@mackenly that's not a bad suggestion. We'll definitely consider that.

**Comment by wpsmort** [comment]
This has been moved to our new feature request system.

**Comment by mackenly** [comment]
@wpsmort @arnaudbroes @benjaminprojas  So is this something that will not be added/considered?

**Comment by wpsmort** [comment]
No, this just means we've moved all feature requests to a new tool that's specifically designed to handle those.
