### ISSUE TITLE
Color Upgrade link to not clash with admin color scheme

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2864]
Requested here: https://wordpress.org/support/topic/please-improve-the-menu-set-up-of-your-plugin/

> can you reconsider the red, bold ‘Upgrade to Pro’ sub-menu too? Depending on your Admin Colour Scheme, this can look hideous and you’ve not considered this. Default WordPress menus are monochrome and adjust automatically to any colour scheme change – can you please do this?

**Comment by dartiss** [comment]
Here's an example, using one of the Admin Colour Schemes that comes built into WordPress core...

<img width="176" alt="Screenshot 2019-09-04 at 14 08 45" src="https://user-images.githubusercontent.com/14928971/64277646-c1ef7e00-cf42-11e9-8894-531ada852432.png">

I understand you wanting to try and promote your paid-for features but the bold, red colouring overrides any user-specific colour changes. For a11y, you should really use the default base colouring for menu options.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #837](https://github.com/awesomemotive/aioseop-pro/issues/837) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dartiss** [comment]
That link is not publicly available @wpsmort

**Comment by wpsmort** [comment]
@dartiss That's correct.  We've moved this issue to our new Github repo which is currently not public. This does not mean we're ignoring the issue, it's just that we've changed the Github repo for our code.
