### ISSUE TITLE
Schema.org - Add JSON+LD markup to custom post types by default

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2874]
Currently we require users to do this: https://semperplugins.com/documentation/enabling-schema-for-custom-post-types-and-custom-taxonomies/

If feel like from a user's perspective, that's a bit much. (Also, most are just going to assume AIOSEOP doesn't do it.)

It seems much better to enable it for custom post types by default, then have an easy way (option or at least easy filter hook) to change the type.

Related to #146 and #507

**Comment by wpsmort** [comment]
I think that we should enable Schema by default for all post types where SEO is enabled and we should default the type to WebPage.  We have an issue open for the filter for type - #146.

**Comment by michaeltorbert** [comment]
@zombiefredrik If you need it now you should use the code provided in the documentation. We don't have a projected release date for this issue. 
It's still under initial review.

**Comment by wpsmort** [comment]
@arnaudbroes @EkoJR I think we should go ahead and enable Schema for all post types in the 3.4 release.  What do you think?  Is there any reason to hold off?

**Comment by arnaudbroes** [comment]
> @arnaudbroes @EkoJR I think we should go ahead and enable Schema for all post types in the 3.4 release. What do you think? Is there any reason to hold off?

I'm good.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #934](https://github.com/awesomemotive/aioseop-pro/issues/934) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
This has been moved to our new repo for the v4 release.
