### ISSUE TITLE
Repeated strings should be defined once and then referred to

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2893]
![image](https://user-images.githubusercontent.com/18156697/64626036-75e28480-d3ed-11e9-8028-e80f043fcc85.png)

This should be done when we refactor aioseop_performance.php.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #814](https://github.com/awesomemotive/aioseop-pro/issues/814) via [**ZenHub**](https://www.zenhub.com/)
