### ISSUE TITLE
New Feature - Add nofollow + title attribute field for links in Gutenberg Editor

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2905]
As announced here - https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html

I believe we should be able to do this by adding custom format actions to the editor toolbar.

**Comment by michaeltorbert** [comment]
We should add nofollow to this. Also, we should decide whether to do it as a button or in the little carrot dropdown which has open in a new tab, or both.
<img width="468" alt="Screen Shot 2019-09-13 at 9 44 42 AM" src="https://user-images.githubusercontent.com/17364998/64867606-b881a800-d60b-11e9-8f77-017fdd214752.png">

**Comment by arnaudbroes** [comment]
I'm bumping this for now since there's no proper way to add this at the moment (we'd have to unregister the current link format, adjust it and then register it again AND ship a bunch of Gutenberg code), but I'm subscribed to the issue in the Gutenberg repo. I might also look into adding a filter myself and submitting it as a PR.

**Comment by arnaudbroes** [comment]
https://github.com/WordPress/gutenberg/issues/17556
