### ISSUE TITLE
Add post_type slug to the Post Types selection list

### ISSUE THREAD

**Issue by Garconis** [awesomemotive/all-in-one-seo-pack#2906]
When having a large site, of which WooCommerce is active — or a site has many custom post types with the same name — it would be useful to know what the CPT slug is. This would help ensure the correct one is being enabled/disabled within the list. Otherwise, it's hard to know exactly which one is being referred to. 

In this screenshot, there is one called Products with a value of `product` and another one called Product with a value of `jp_pay_product`. I legit didn't know which one I wanted to toggle, without inspecting the DOM to find the input value.

Screenshot: https://gyazo.com/e2bfb49ddfcb1b86f8529d7e30f24a20

![screenshot](https://user-images.githubusercontent.com/8608632/64881304-6d29c280-d628-11e9-8a79-b774ce253299.png)

**Comment by michaeltorbert** [comment]
@Garconis Great suggestion!
Any input on the best way to display that info? Maybe hovering over it has a tooltip with the slug?

**Comment by Garconis** [comment]
I'd certainly be happy with a tooltip of some sort. Probably not necessary for the majority of users to see it by default.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #935](https://github.com/awesomemotive/aioseop-pro/issues/935) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
This has been moved to our new repo for the v4 release.
