### ISSUE TITLE
RSS Sitemap - Yandex does not support title, description, link tags in RSS sitemap

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2911]
Reported here - https://wordpress.org/support/topic/issue-about-tags-in-sitemap-rss/

@wpsmort you were the most involved in the development of that feature so I'm wondering whether there ever was any schema/protocol we based our RSS sitemap on? Based on the issue, I'm
guessing we decided to do whatever https://wordpress.org/plugins/www-xml-sitemap-generator-org/ is doing. 

Related issues are https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2487 and https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2704 because at some point we need to discuss how far we're willing to go to support Yandex.

**Comment by michaeltorbert** [comment]
Other plugins have dropped support completely for yandex-specific things. 
From the other issue:

> We do have a lot of Russian users, so I hate to alienate them.
So we could 1) drop it completely, even though Yandex uses it, 2) move it to a free add-on plugin, 3) move it to a paid add-on plugin, or 4) move it to Pro

**Comment by arnaudbroes** [comment]
Here's a thought but what we actually could do here is detect the user agent and remove these from the sitemap if we detect that Yandex is crawling the sitemap.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #858](https://github.com/awesomemotive/aioseop-pro/issues/858) via [**ZenHub**](https://www.zenhub.com/)
