### ISSUE TITLE
Remove unprotect post meta fields option

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2912]
I'm not sure why we need this: https://semperplugins.com/documentation/all-in-one-seo-pack-advanced-settings/#unprotect-post-meta-fields

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #761](https://github.com/awesomemotive/aioseop-pro/issues/761) via [**ZenHub**](https://www.zenhub.com/)
