### ISSUE TITLE
Change saving image in options from URL to (image) ID

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2917]
Currently, any image options used on the AIOSEOP settings page use the URL. In turn, some instances require converting the URL to an ID, and it is known to be memory intense. Which was the primary cause for site's breaking roughly around AIOSEOP version 2.7~2.9.

This would be more efficient to save the image ID instead since there's been multiple occasion additional image data is needed from a site.

## Proposed Solution

Change image setting values to use the image ID instead, and save as an ID within the database. Functions that interact with the variable will need to be changed to `wp_get_attachment_metadata( $image_id )`, or improve the operations as well as removing any uses of  `aiosp_common::attachment_url_to_postid()`.

The function `aiosp_common::attachment_url_to_postid()` would then need to be deprecated for performance reasons, but do not delete.

Database update would be required to change all the site image URLs used to image ID instead. This would need to use `aiosp_common::attachment_url_to_postid()` in order to convert the URLs. Other sites should already be using the function, so there should be a low probability of breaking sites. This should still be marked as a potential breaking change. _Note: Avoid using the query_2 function since it is confirmed to break sites._

## Additional Information

* This would also eliminate the need for users to specify an image width and height. Like with a post's Social Settings.
  * Allows the ability to use the Image ID to retrieve the meta data.

**Comment by michaeltorbert** [comment]
What if, instead of doing the db update, we support both?

So, going forward they'd be saved as IDs, and the code to use them would use the better code if it's an int and the old code if it's a string.

**Comment by EkoJR** [comment]
I've thought about what you said, and I'm not sure if that would be ideal. Here's a few thoughts I've had.

* (Reducing update workload) I'm not sure if it would be conceptually sound to have a loose option to save either an ID or URL, and then have it become a question whether it is an ID or URL. I feel it would make it more prone to bugs. 
  * However, I do wonder if we can create an update that splits the load into different (timed) instances, and have another function to get/convert-to the ID on-demand whenever accessing a value that isn't converted in AIOSEOP's options. Once completed, the function(s) will no longer used.
* (Possible bug) One thing to be cautious about is WP saves all data as strings. Although this could be corrected with `is_numeric()` there is still the possibility of some strings being considered numeric. Depends on the URL string used, but the possibility seems low.
* (Impacts performance) We might be able to save data as an array, which would include the ID and URL, and possibly any other meta data. However, in the past with sites with bulk images I've experienced how this severely impacts performance and can even break the SQL queries if too large. _One of the main goals to this issue is to improve performance._

I would still recommend reducing the database to just image IDs, but also in conjunction have a static function with a static variable that also uses transient data to store any additional data a site might be frequently fetching. That way we can still have both (limited to just what data is needed) and improve performance & flexibility.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #813](https://github.com/awesomemotive/aioseop-pro/issues/813) via [**ZenHub**](https://www.zenhub.com/)
