### ISSUE TITLE
Deprecate/Remove 'Specify Image Width/Height' Settings in Post Metabox > Social Settings

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2930]
## Is your feature request related to a problem? Please describe,

Requires #2917 - Makes the Image ID available for use.

With the Image ID, it is possible to retrieve the metadata for images which would include the image's width & height. So instead of relying on users to input the dimensions, which could be prone to errors, operations would instead use WP's metadata containing the pre-calculated dimensions.

## Describe the solution you'd like

Operations in `All_in_One_SEO_Pack_Opengraph::add_meta()` would have the image dimensions changed to use WP's [wp_get_attachment_metadata()](https://codex.wordpress.org/Function_Reference/wp_get_attachment_metadata).

Options 'Specify Image Width/Height' can then be deprecated/removed in the Post Metabox > Social Settings.

![Post Metabox Social Settings - Image Dimensions](https://user-images.githubusercontent.com/2794445/65395310-fdb18280-dd4d-11e9-8d4c-4705d86957df.png)

**Additional context**

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #803](https://github.com/awesomemotive/aioseop-pro/issues/803) via [**ZenHub**](https://www.zenhub.com/)
