### ISSUE TITLE
Code Refactor - Replace date_i18n with wp_date

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2931]
When 5.3 is out. We'll have to do a version check for <5.3 to keep using date_i18n, but in 5.3 this function will be deprecated and instead we should use wp_date() which localizes the time based on the Unix timestamp instead of the WP timestamp.

We use this function a few times in aioseop-class.php for the localized month macro.

source: https://make.wordpress.org/core/2019/09/23/date-time-improvements-wp-5-3/

**Comment by michaeltorbert** [comment]
Shouldn’t this be included in 3.3 since 5.3 will be out soon?

Since we use the function in multiple places, my recommendation is we make a wrapper function to figure out which to use.

**Comment by arnaudbroes** [comment]
> Shouldn’t this be included in 3.3 since 5.3 will be out soon?

I would hold off till WP 5.3 RC1 is out since we otherwise don't have a way of testing it.

> Since we use the function in multiple places, my recommendation is we make a wrapper function to figure out which to use.

Agreed.

**Comment by michaeltorbert** [comment]
RC1 is in 3 weeks, which is probably well before AIOSEOP 3.5.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #812](https://github.com/awesomemotive/aioseop-pro/issues/812) via [**ZenHub**](https://www.zenhub.com/)
