### ISSUE TITLE
XML Sitemap - Including More Search Engines to Ping in Sitemap

### ISSUE THREAD

**Issue by mathewdiekhake** [awesomemotive/all-in-one-seo-pack#2936]
Hello,

Would you be willing to add more search engines to the ping list for the sitemap? According to the notes, it only pings Google and Bing. 

My website is now getting only 50% of its traffic from Google. Thankfully my traffic is still decent thanks to Bing, Yahoo, Baidu, DuckDuckGo, Ecosia, and a few more search engines that make up at least 1% of traffic each as per my statcounter.com statistics. 

With more and more people coming online every day, I believe these other search engines are now proving useful for webmasters. 

Thanks for reading and to anyone who is willing to help implement this.

**Comment by michaeltorbert** [comment]
Someone needs to check what, if any, other search engines have a URL/API for pinging.

**Comment by Makio9** [comment]
Oh Ok. 

Thanks for the update. 

I had checked "how to get indexed Baidu" and it seemed like a thing, but I guess not.

**Comment by michaeltorbert** [comment]
@Makio9 That wasn't addressed to you specifically.

**Comment by Makio9** [comment]
Gotcha. 

Carry on lads. 

I'd love to help but I'm not a developer.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #933](https://github.com/awesomemotive/aioseop-pro/issues/933) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
Moved to our new repo for inclusion in the v4 release.
