### ISSUE TITLE
Schema - Slow query with thousands of users

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2937]
Reported here: https://wordpress.org/support/topic/slow-query-on-shop-with-thousands-of-users/

> I’m running a large shop with around 12000 registered customers and we’re investigating slow db performance. We’ve installed “query monitor” and one of the slow queries is linked to your plugin.
Is there any way to optimise this query to run more efficiently on a large shop?
Screenshot: https://www.dropbox.com/s/5jndd0y4k8y28eg/Bildschirmfoto%202019-09-26%20um%2013.13.31.png?dl=0
Query is in
wp-content/plugins/all-in-one-seo-pack/aioseop_class.php:1093

		$user_args = array(
			'role__in' => array(
				'administrator',
				'editor',
				'author',
			),
			'orderby'  => 'nicename',
		);
		$users = get_users( $user_args );

![fZbbMYVA](https://user-images.githubusercontent.com/17364998/65694792-6a759700-e044-11e9-87f6-cddf998fc0df.png)

**Comment by JulianMar** [comment]
Is there a workaround for this?

**Comment by notmike101** [comment]
Another example of long query times for this on a shop with nearly 6 thousand users.

![image](https://user-images.githubusercontent.com/7198316/66776855-3db2e380-ee7c-11e9-87e3-d7993ab8c6e9.png)

If anyone knows of any fixes for this, please let me know.

**Comment by jmock** [comment]
Same here. We have 140,000 users and I had to disable the plugin because it was melting our database this morning.

**Comment by leonelectro** [comment]
The WP database architecture makes these checks for users of certain roles expensive. You can mitigate this problem with caching, but you still have to generate the cache values regularly. You could do that in a cron.

This code seems to be pulling a list of admins for the sake of default options on every request. Perhaps the defaults can be generated once on activation or only on the wp-admin side on a particular configuration page.

A temporary fix would be to stay on version 3.1.x. After 9 patches to 3.2 and a month gone by, it's straining the concept of temporary.

**Comment by michaeltorbert** [comment]
I’m assigning this to 3.3. @arnaudbroes or @EkoJR can one of you have a look?

**Comment by arnaudbroes** [comment]
I've confirmed the behaviour.

**Comment by michaeltorbert** [comment]
At a minimum, limit this code to the the settings page.

**Comment by wpsmort** [comment]
@arnaudbroes As discussed, in this release (#2792) we are adding an option to the Person's Username dropdown in Schema Settings to select Manually Enter which, when selected, displays the Person's Username and Person's Image fields.  We could detect when the users table has more than X rows and then automatically default the dropdown to Manually Enter.

<img width="607" alt="Screen Shot 2019-10-28 at 3 41 39 PM" src="https://user-images.githubusercontent.com/17548525/67712159-d592f000-f999-11e9-90e0-e6d9bcad4323.png">

**Comment by wpsmort** [comment]
Potential options for improving this are:
- Use selectize.js instead of a drop down so that when someone types the name we match against users (preferred option)
- We have a filter to change the threshold for displaying the manually enter fields from 20 users to a number specified in the filter

**Comment by arnaudbroes** [comment]
> Potential options for improving this are:
> 
> * Use selectize.js instead of a drop down so that when someone types the name we match against users (preferred option)
> * We have a filter to change the threshold for displaying the manually enter fields from 20 users to a number specified in the filter

In retrospect, I believe we only need the latter. Former might be a bit overkill for this setting.

**Comment by leonelectro** [comment]
It appears that 4.x reverts to the previous behavior, which has once again made it impossible for us to edit pages.

**Comment by arnaudbroes** [comment]
@leonelectro you're probably experiencing another issue. If you haven't already, could you reach out to us here - https://aioseo.com/contact/. That way we'll be able to quickly follow up with you and get the issue resolved.
