### ISSUE TITLE
Extra space between meta keywords name and content

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2943]
Reported here: https://wordpress.org/support/topic/between-name-and-content-there-are-two-spaces-that-may-effect-seo/

> Between name and content, there are two spaces that may effect SEO.
<meta name=”keywords” content=”keyword 1, keyword 2″ />

This is caused by our use of a placeholder in https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/c52e3f666665515a9574d9e5fd7526768b96fb20/aioseop_class.php#L4370

**Comment by SaifullahAslam** [comment]
Sir Michael Torbert, is it possible to fix these issues on upcoming updates of AIO SEO Pack in free version?

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #828](https://github.com/awesomemotive/aioseop-pro/issues/828) via [**ZenHub**](https://www.zenhub.com/)
