### ISSUE TITLE
Change aiosp_skip_excerpt setting label OR db name

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#2950]
This causes confusion on the backend and is also conceptually mislabeled. The easiest option is to change the option label "Use Content For Autogenerated Descriptions" on the admin setting to **"Skip Excerpt For Descriptions"**.

Other option is to change the database name to match the admin setting to `aiosp_use_content`, which conceptually interferes with auto gen descriptions and requires a Db update.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #811](https://github.com/awesomemotive/aioseop-pro/issues/811) via [**ZenHub**](https://www.zenhub.com/)
