### ISSUE TITLE
Code Refactor - Remove Gutenberg/Chrome fix

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2957]
We should remove this again (compatibility/gutenberg-chrome.php) once Google Chrome v77 is well behind us.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #810](https://github.com/awesomemotive/aioseop-pro/issues/810) via [**ZenHub**](https://www.zenhub.com/)
