### ISSUE TITLE
Code Refactor - Remove aioseop_sitemap_index_filenames filter

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2974]
No longer being used now that https://github.com/semperfiwebdesign/aioseop-pro/pull/550 has been merged.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #809](https://github.com/awesomemotive/aioseop-pro/issues/809) via [**ZenHub**](https://www.zenhub.com/)
