### ISSUE TITLE
XML Sitemap - Look into possible code issue with sitemap array

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#298]
https://wordpress.org/support/topic/sitemapxml-blank?replies=15#post-8468343

"I was having the same trouble on some sites.
Setting " Enable Sitemap Indexes" to on fixes the problem.

PHP Warning: array_merge(): Argument #1 is not an array in __________wp-content/plugins/all-in-one-seo-pack/modules/aioseop_sitemap.php on line 1094
"

**Comment by wpsmort** [comment]
@michaeltorbert I get this similar error on my dev site running the latest code from the Dev branch:

PHP Warning:  array_merge(): Argument #1 is not an array in /wp-content/plugins/all-in-one-seo-pack/admin/aioseop_module_class.php on line 1393

Not sure if this is related or relevant.

**Comment by michaeltorbert** [comment]
@wpsmort Since I can't replicate yours and you don't know what circumstances made it happen it's hard to know for certain, but I think yours may have to do with #357 and #332

**Comment by michaeltorbert** [comment]
As for the other one, I'd really need to know more about his site. It may be a multisite issue...

**Comment by EkoJr** [comment]
`All_in_One_SEO_Pack_Sitemap::get_child_sitemap_urls()` keeps returning a string instead of an array.

**Comment by michaeltorbert** [comment]
@EkoJr What is your suggestion?

**Comment by EkoJr** [comment]
I was thinking of correcting the pattern, but at the same time, they appear to be the compressed files from the other (multi) sites. 

This also appears to part of some other issues related. #745 

I think the root issue is that there is only a sitemap.xml.gz link, which goes to a file to download. Unsure on the intend, but suspect it was intended to be displayed.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #860](https://github.com/awesomemotive/aioseop-pro/issues/860) via [**ZenHub**](https://www.zenhub.com/)
