### ISSUE TITLE
Code Refactor - Use minified CSS and JS files

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2991]
We've now added these but we're still enqueuing the non-minified ones.

**Comment by arnaudbroes** [comment]
> It's a good idea, but we would also need a constant (eg. AIOSEOP_DEBUG_SCRIPTS) to bypass minify for development purposes. It's near impossible to debug a minified file.

**Comment by EkoJR** [comment]
When adding this, be sure to include in the User Report documentation/troubleshooting, regarding to JS errors, with instructions on how to enable debug mode.

**Comment by arnaudbroes** [comment]
We'll use Webpack in V4.
