### ISSUE TITLE
Bug - Sitemap logging all verbosity levels to error log

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#3002]
Reported by Frank R. on 11/5 via e-mail.

> We are encountering on our server log error the following lines:
> 
> [04-Nov-2019 16:16:43 UTC] 0.07 MB memory used generating the dynamic sitemap in 0.068 seconds, 6.75 MB total memory used.
> [04-Nov-2019 16:46:41 UTC] 5.62 MB memory used generating the dynamic sitemap in 0.189 seconds, 12.30 MB total memory used.

Those are just informational messages that shouldn't be logged to the error_log. 

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/f3f25ca97e459e460d2cb6a45448f2ba88353086/inc/aioseop_functions.php#L1056-L1077

We'd have to rewrite some code in the sitemap and/or the aiosp_log() function to improve this. Apart from that, I believe it'd be better to create a logger class that can handle all verbosity levels.

**Comment by arnaudbroes** [comment]
Reported again here - https://wordpress.org/support/topic/fastcgi-sent-in-stderr/

**Comment by wpsmort** [comment]
Replaced by #3003
