### ISSUE TITLE
New Feature - Logger class that handles all events (info, warning, error)

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#3003]
The "Log important events" option is pretty terrible at the moment. For instance, we log an entry when someone visits the second page of any paginated post/page. What's the point of that?

We should have a central logger class that handles all levels of verbosity.

**Comment by arnaudbroes** [comment]
Related to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3002.

**Comment by wpsmort** [comment]
See also #48
