### ISSUE TITLE
Update Testing Documentation for Gutenberg

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#3006]
#3004 and #3005 were added because of missing AIOSEOP functionality in Gutenberg that works in the Classic Editor. 
We need to update the documentation to accomodate galleries added via each method, if the code itself is different in the post.

**Comment by arnaudbroes** [comment]
In particular any plugins that use HTML markup in the Classic Editor and now shortcodes in the Gutenberg Editor will be affect our testing.
