### ISSUE TITLE
Code Refactor - Load plugin options as Singleton

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#3010]
Ben and I agreed today that we should load the plugin options as a singleton in a static class instead of fetching them multiple times and storing them as a global. 

Also, I'd prefer that the we map the plugin options to a class object instead of keep using it as an array. The static class thus should probably also have a parameter-less `update_options` method to update the options based on its current state.

**Comment by EkoJR** [comment]
This would need to be implemented before admin operations can be separated from the modules into admin classes. Currently, the options is encapsulated into the base module which is intended for each module, and accessing them requires depending on the module's global variable.

Recommend using a singleton class to reduce loading the db options multiple times, and should reduce SQL queries. It also eliminates having to depend on `global $aioseop_options`, and prevents any duplicates that may occur.

**Comment by arnaudbroes** [comment]
We're doing this in V4.
