### ISSUE TITLE
Code Refactor - Create context object class

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#3011]
We should have one or multiple (static) context object classes where we store data in that otherwise needs to be fetched multiple times (e.g. post data, term data, title format, etc.)

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #808](https://github.com/awesomemotive/aioseop-pro/issues/808) via [**ZenHub**](https://www.zenhub.com/)
