### ISSUE TITLE
Bug - "open_basedir restriction in effect" on IIS web servers

### ISSUE THREAD

**Issue by halilselcuk** [awesomemotive/all-in-one-seo-pack#3036]
Pro link makes warning at AIO Seo admin menu.

1. Go to any admin panel page
2. Check errors logs
3. See warning report "PHP Warning:  file_exists(): open_basedir restriction in effect..... wp-content/plugins/https://semperplugins.com/all-in-one-seo-pack-pro-version/.......  in wp-admin\menu-header.php on line 240"

 - WordPress version: 5.3
 - All in One SEO Pack version: 3.3.2
 - PHP version: 7.3.11
 - OS: Windows Server 2012

**Comment by arnaudbroes** [comment]
@halilselcuk This isn't a bug, but rather a support issue. 

Your IIS application pool does not have the right permissions to access the relevant file. If you're using the Standard version of Windows Server, I'd recommend that you navigate to the plugins folder where All in One SEO Pack Pro is located, select the plugin folder, go to "Properties > Security" and then click "Edit > Add > Locations", enter the name of your application pool like this (`IIS AppPool\<nameofyourpool>`) and give it "Read" permissions. Then apply the changes.

If you're using the Core version of Windows Server, then you'll have to navigate via the prompt to the plugin folder and add the necessary permissions by command line. In that case you'll want to pass this info on to your sysadmin if you're not experienced in Powershell.

That's just what I know off the top of my head. If that doesn't work and you require more assistance, then please contact us here with your license key for further support - https://semperplugins.com/contact/

**Comment by halilselcuk** [comment]
Giving read permissions not solved problem. I'm not pro user.

PHP Warning:  `file_exists(): open_basedir restriction in effect. File(C:\inetpub\vhosts\x.com\httpdocs/wp-content/plugins/https://semperplugins.com/all-in-one-seo-pack-pro-version/) is not within the allowed path(s): (C:/Inetpub/vhosts/x.com\;C:\Windows\Temp\) in C:\inetpub\vhosts\x.com\httpdocs\wp-admin\menu-header.php on line 240`

Maybe need use better way to add custom URLs. Maybe like this. It's not makes warnings. Sorry, I'm too lazy to make pull request. 
`<?php
/**
 * Menu
 *
 * @package All_in_One_SEO_Pack
 * @since ?
 */

/**
 * Class AIOSEOPAdminMenus
 *
 * @since 2.3.11.5
 */
class AIOSEOPAdminMenus {

	/**
	 * Constructor to add the actions.
	 */
	function __construct() {

		add_action( 'network_admin_menu', array( $this, 'remove_menus' ), 15 );

		if ( is_multisite() ) {
			return;
		}

		if ( ! AIOSEOPPRO && ( current_user_can( 'manage_options' ) || current_user_can( 'aiosp_manage_seo' ) ) ) {
			add_action( 'admin_menu', array( $this, 'add_pro_submenu' ), 11 );
		} else {
			return;
		}

		add_action( 'admin_enqueue_scripts', array( $this, 'admin_enqueue_scripts' ) );
	}

	function remove_menus() {
		remove_menu_page( AIOSEOP_PLUGIN_DIRNAME . '/aioseop_class.php' ); // Remove AIOSEOP menu from the network admin.
	}

	/**
	 * Adds Upgrade link to our menu.
	 *
	 * @since 2.3.11.5
	 */
	function add_pro_submenu() {
		$url          = 'https://semperplugins.com/all-in-one-seo-pack-pro-version/?loc=aio_menu';
		$upgrade_text = __( 'Upgrade to Pro', 'all-in-one-seo-pack' );
		add_submenu_page( AIOSEOP_PLUGIN_DIRNAME . '/aioseop_class.php',
		" ",
		"<span class='upgrade_menu_link'>$upgrade_text</span>",
		"manage_options",
		"aioseopro",
		array( $this, 'empty_function' ),
		);
		
		if ($_SERVER["REQUEST_URI"] == '/wp-admin/admin.php?page=aioseopro')
		{
			header('location:'.$url);
		}
	}
	
	function empty_function() {
	}

	/*
	 * Opens Upgrade to Pro links in WP Admin as new tab.
	 *
	 * Enqueued here because All_in_One_SEO_Pack_Module::admin_enqueue_scripts does not work.
	 *
	 * @param string $hook
	 *
	 * @since 3.0
	 */
	function admin_enqueue_scripts( $hook ) {
		wp_enqueue_script( 'aioseop_menu_js', AIOSEOP_PLUGIN_URL . 'js/aioseop-menu.js', array( 'jquery' ), AIOSEOP_VERSION, true );

		if ( 'plugins.php' === $hook ) {
			wp_enqueue_script( 'aioseop_plugins_menu_js', AIOSEOP_PLUGIN_URL . 'js/plugins-menu.js', array( 'jquery' ), AIOSEOP_VERSION, true );
		}
	}
}

	new AIOSEOPAdminMenus();

`

**Comment by arnaudbroes** [comment]
@halilselcuk

**Comment by arnaudbroes** [comment]
@halilselcuk I misunderstood your initial comment. Thanks, I had a quick look at that code and that does seem like an improvement. Were you able to confirm that fixes the issue for IIS?

**Comment by halilselcuk** [comment]
Yes, that fixes issue for IIS.

**Comment by arnaudbroes** [comment]
I'll try and see if I can reproduce this on a virtual machine but in either case the code that @halilselcuk submitted is an improvement and we should implement it.

**Comment by arnaudbroes** [comment]
Related to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1332, https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1123

**Comment by wpsmort** [comment]
This has been moved to our new repo.
