### ISSUE TITLE
Preview Snippet - Title placeholder should also reflect title format

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#3037]
Now that the Preview Snippet and Character Counter code both have been refactored, this is something we can improve easily.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #856](https://github.com/awesomemotive/aioseop-pro/issues/856) via [**ZenHub**](https://www.zenhub.com/)
