### ISSUE TITLE
XML Sitemap - Add filter to exclude posts/pages by ID

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#3040]
Requested here - https://wordpress.org/support/topic/developer-question-3/

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #784](https://github.com/awesomemotive/aioseop-pro/issues/784) via [**ZenHub**](https://www.zenhub.com/)
