### ISSUE TITLE
Bug - HTML code in Gutenberg Screen Options when Social Meta module is disabled

### ISSUE THREAD

**Issue by FactorExtremo** [awesomemotive/all-in-one-seo-pack#3055]
It is just a small display error
![Screenshot_1](https://user-images.githubusercontent.com/35585666/69202329-519ed480-0b0f-11ea-840c-f7a8eb4dde75.png)

**Comment by arnaudbroes** [comment]
@FactorExtremo on what screen is this? Looks like a custom display or plugin.

**Comment by FactorExtremo** [comment]
Hi, on options when I am editing a post or page

**Comment by michaeltorbert** [comment]
![Nov-20-2019 14-34-10](https://user-images.githubusercontent.com/17364998/69271445-de46a280-0ba2-11ea-8053-622940da0fd0.gif)

**Comment by EkoJR** [comment]
I believe I found what triggers the error.

## Steps to reproduce.

1. Deactivate the Social Meta module (if active).
2. Go to Post Editor > Options (as shown in video).

**Comment by arnaudbroes** [comment]
> I believe I found what triggers the error.
> 
> ## Steps to reproduce.
> 1. Deactivate the Social Meta module (if active).
> 2. Go to Post Editor > Options (as shown in video).

I can confirm this works to reproduce the issue.

**Comment by FactorExtremo** [comment]
Yes, you are right, thank you very much

**Comment by wpsmort** [comment]
@arnaudbroes This bug is not new, it was introduced in v2.0.4.1.  It's hidden on the Screen Options pull down in the Classic Editor using the CSS below: 

.metabox-prefs label a {
display: none;
}

This CSS doesn't work in the Block Editor so the raw HTML is output.
