### ISSUE TITLE
Stop overriding wp-admin navigation after update

### ISSUE THREAD

**Issue by Garconis** [awesomemotive/all-in-one-seo-pack#3057]
After a plugin update to AIOSEO, it seems you always show a "splash" screen of `/wp-admin/index.php?page=aioseop-about`. This is shown when trying to navigate to a new backend page. For example, I run updates (including AIOSEO). I then try to navigate to the Pages area. Instead, your plugin overrides/redirects that attempt and shows your "About" page instead.

Preferably, this would not be the case. I often check the changelog before updating, so I don't need to see the splash screen. And I especially don't want it to override my expected navigation.

If you're adamate about showing your splash screen (and thus overriding desired navigation), then at least please make an option to "never show me this again".

**Comment by michaeltorbert** [comment]
Thanks for reporting this and for your feedback. Currently, it should only be showing when updating to a new major version. Are you seeing it for each minor version update as well?

**Comment by Garconis** [comment]
What do you consider major? I see it on the `3.3.3` update (from `3.2.10`).

Video: https://drive.google.com/uc?id=1JVy8ZuVWhtsL1YEkiiS1WPUigqDxIq7U

I'd be OK with it, for whole version numbers (e.g., 3.X.X to 4.X.X). Though I still don't think it's OK to override a navigation attempt. But it gets a bit annoying for minor and patch updates.

**Comment by michaeltorbert** [comment]
x.y is major, x.y.z is minor. It’s currently configured so that you’ll see it after each major release, including if you’ve skipped one like in this case.

**Comment by Garconis** [comment]
Yeah, not a fan of that, and wish there were a setting somewhere to opt out of that. I work with hundreds of installs with this plugin, and I don't need to see that screen after each update. Granted, I don't continue to use the backend of most of those installs after running an update. But it just seems strange to override navigation like this. 

No other plugin we use does this, as far as I'm aware. Not to sound like a jerk, but you're not WordPress core. I don't think it's that vital. 

Some sort of message box at the top may suffice? Especially since this splash screen doesn't offer any real substance anyway...

**Comment by michaeltorbert** [comment]
> No other plugin we use does this, as far as I'm aware. Not to sound like a jerk, but you're not WordPress core.
We actually lifted much of the code from two core/featured plugins, BuddyPress and bbPress. But no, you don't sound like a jerk. I sincerely appreciate the feedback. We're always looking for ways to improve the UX.

**Comment by Garconis** [comment]
As an FYI, this also seemed to happen from `3.3.1.1` to `3.3.3`.

Video: https://drive.google.com/uc?id=1X2D8TNxYcf40Sko6_uHJCgS4Y7SlwbOp

**Comment by wpsmort** [comment]
Requested again here - https://wordpress.org/support/topic/annoying-splash-screen-when-updating-still/

**Comment by wpsmort** [comment]
This will be included in the v3.6 release which is due for release this week.
