### ISSUE TITLE
Preview Snippet/Character Counter - Use "KeyUp" instead of "Change" event listener 

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#3060]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/3059 introduced support for the text tab of the Classic Editor. 

Unfortunately, I was only able to apply a "Change" event listener tothe content area. It would be much better to have a "KeyUp" event listener. I'll have to do more research to see how I can implement it. The difficulty with TinyMCE is that the fields we see as a user aren't the ones we actually type in.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #857](https://github.com/awesomemotive/aioseop-pro/issues/857) via [**ZenHub**](https://www.zenhub.com/)
