### ISSUE TITLE
Code Refactor - Use logical properties in CSS where possible

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#3085]
For instance - https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline
This removes the need for separate RTL CSS files.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #807](https://github.com/awesomemotive/aioseop-pro/issues/807) via [**ZenHub**](https://www.zenhub.com/)
