### ISSUE TITLE
Bug - SEO meta missing from translated content in WPML

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#3103]
Reported by Leandro by contact form.

Leandro is using WPML on his site and noticed that the SEO meta was missing from the translated content in his WooCommerce products.  See screenshot below:

![IryGVzI](https://user-images.githubusercontent.com/17548525/72176095-afcb9380-33ab-11ea-90a1-ff6169b0561b.jpg)

I reported this to WPML and they responded with this:

It's happened because when updating products, plugin author is deleting post_meta and re-adding it again instead of updating post_meta and it's triggering our function to clean post_meta which not using for translations ( based on new WC logic )

Please ask plugin author to adjust their code in All_in_One_SEO_Pack::save_post_data instead of deleting post_meta and re-adding it again use updating post_meta function"

See screenshot below:

![image1577280409294](https://user-images.githubusercontent.com/17548525/72176253-03d67800-33ac-11ea-9681-874f286f05e6.png)

**Comment by arnaudbroes** [comment]
@wpsmort I tried reproducing this but was unsuccessful. Here's what I tried:

1. Install the latest version of WPML and All in One SEO Pack.
2. Enable SEO for Products in the General Settings menu and enable translations for Products under WPML > Settings.
3. Add a Product (English), some content, a title and a description.
4. Add a translation for said Product in another language, with some content, a different title and a different description.
5. Check if both the English version of the Product and other language use different titles and descriptions.
6. Update both the English version and other language version and check this again. 

After going through these steps, both the English version and other language version were outputting different titles and descriptions. These also showed up both on the Edit page and in the columns on the List page. 

Can you go through the same steps and report back here?

**Comment by kkarpieszuk** [comment]
Hi guys, thank you for handling this. I pinged our WCML developer to reply to your last comment

**Comment by grey-rsi** [comment]
Hello @arnaudbroes you also need to add "All in One SEO Pack" keywords and description to product and translate these fields via WPML editor.

Here a steps to reproduce:
- Go to its Settings and enable it for Products/pages/posts/etc.
- Add a product with a Title, Description, and Product Description
- Now also add some AIOSEOP keywords and description
- Add a translation using the classic translation editor, at the bottom there are 2 fields Aioseop: AIOSEOP keywords and Aioseop description, Copy them over or add your own translation and save.
- Now go back to the original product, make a small change in AIOSEOP fields
- Click on the secondary language to update it and you will notice that the field is completely empty now and reset.

**Comment by wpsmort** [comment]
@grey-rsi I tested the steps above but the _aioseop_description and _aioseop_keywords in the Multilingual Content Setup box on the Edit Product screen are greyed out.  See screenshot below:

<img width="1304" alt="Screen Shot 2020-01-13 at 1 55 24 PM" src="https://user-images.githubusercontent.com/17548525/72283338-8bbabd00-360c-11ea-89d0-c3941c8701bb.png">

**Comment by grey-rsi** [comment]
@wpsmort it's right ( they are pre-defined to be translatable in wpml-config.xml file )

**Comment by arnaudbroes** [comment]
I'm still not able to reproduce this unfortunately. Would you be able to record what it is exactly that you do?

**Comment by arnaudbroes** [comment]
I wonder whether https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2625 is related.

**Comment by grey-rsi** [comment]
Hello, sorry missed notifications... I have recorded a video of a problem https://www.screencast.com/t/38rMHvBoI

**Comment by wpsmort** [comment]
Reported again here - https://secure.helpscout.net/conversation/1125271191/658483?folderId=3532975

In the case of this report, the customer provided me access to their site and a video of what they were seeing.  I repeated the same steps on the same WC product but everything worked for me.  I could not work out why this clearly didn't work for the customer but worked for me every time when following the same steps on the same product.

**Comment by wpsmort** [comment]
@grey-rsi I'm not able to view that screencast because it requires Flash.  

Mihai Apetrei from WPML support sent this message via our customer:

Modify "all-in-one-seo-pack-pro/aioseop_class.php" Lines 5104 - 5119:

From:

`foreach ( $optlist as $field_name ) { $field = "aiosp_$field_name"; if ( isset( $_POST[ $field ] ) ) { $$field = $_POST[ $field ]; } delete_post_meta( $id, "_aioseop_{$field_name}" ); } foreach ( $optlist as $field_name ) { $var = "aiosp_$field_name"; $field = "_aioseop_$field_name"; if ( isset( $$var ) && ! empty( $$var ) ) { add_post_meta( $id, $field, $$var ); } }`

To:

`foreach ( $optlist as $field_name ) { $field = "aiosp_$field_name"; update_post_meta( $id, "aioseop{$field_name}", $_POST[ $field ] ); }`

Is this the fix you're suggesting?

**Comment by grey-rsi** [comment]
@wpsmort you can enable flash on that page or check it on https://drive.google.com/file/d/1TOFV1JFmrlzOvJ0-v-kv66MC4rqr7Lyn/view?usp=sharing

Yes the problem in deleting and adding back post meta, please use `update_post_meta` instead. I didn't provide a possible fix because it may affect your logic in other places so better if you can review all places where you're deleting and adding it back.

**Comment by wpsmort** [comment]
The video provided by grey-rsi finally shows all the steps you need to follow in order to reproduce this.  I've followed the video and confirmed that I can reproduce this.

I'm moving this to the Pro repo for the dev team to work on for v3.5.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #882](https://github.com/awesomemotive/aioseop-pro/issues/882) via [**ZenHub**](https://www.zenhub.com/)
