### ISSUE TITLE
Incorrect header's lengh

### ISSUE THREAD

**Issue by andrewinsidelazarev** [awesomemotive/all-in-one-seo-pack#3135]
Plugin shows incorrect length 
![Снимок экрана 2020-02-13 в 11 26 50](https://user-images.githubusercontent.com/31416889/74420400-0ec17400-4e54-11ea-954e-2a7676703530.png)

**Comment by arnaudbroes** [comment]
It does not. It also takes your title format into account (see "Title settings" in the General Settings menu and have a look at the preview snippet).
