### ISSUE TITLE
Issue with Twitter cards

### ISSUE THREAD

**Issue by albertodlc15** [awesomemotive/all-in-one-seo-pack#3141]
We're having an issue where Twitter is unable to pick up the meta tags and create a summary or summary with image when posting links from our site on Twitter. I've check and All-in-one-seo pack is inserting the meta tags, but the Twitter card validator says "no meta tags found." (see attached screenshots)

Our website is babalublog.com
![babalu twitter meta tags](https://user-images.githubusercontent.com/61166402/74687999-18c0db00-51a4-11ea-84fe-06d2191200a2.PNG)
![babalublog twitter card validator](https://user-images.githubusercontent.com/61166402/74688005-1bbbcb80-51a4-11ea-8e2f-61f52190b4c9.PNG)

Thank you for your help.

Alberto de la Cruz
albertodlc@babalublog.com

**Comment by wpsmort** [comment]
This is a development repository and not a support forum.  Please read the troubleshooting guide here - https://semperplugins.com/documentation/troubleshooting-incorrect-social-meta-when-sharing-or-publishing-content/

**Comment by albertodlc15** [comment]
My mistake. Thank you for the reference.
