### ISSUE TITLE
field brand is not exist

### ISSUE THREAD

**Issue by disciple98** [awesomemotive/all-in-one-seo-pack#3144]
using plugin can't get field brand for product. how to fix this problem? Brand info is added...
![предупреждение](https://user-images.githubusercontent.com/61317927/75035868-3cfe1e00-54fc-11ea-8f02-7ac6961283f1.jpg)

**Comment by wpsmort** [comment]
This is not a support forum, it is a development repository.  Also, All in One SEO Pack is not outputting that schema markup, another plugin is.
