### ISSUE TITLE
Error in og:description

### ISSUE THREAD

**Issue by andrewinsidelazarev** [awesomemotive/all-in-one-seo-pack#3145]
On page: [view-source:https://andrew-lazarev.com/wedding-videograph-kharkov/](view-source:https://andrew-lazarev.com/wedding-videograph-kharkov/)

It should be:

"+380662971402 Услуги свадебной видеосъемки в Харькове и Харьковской области. Видеограф на свадьбу в Харькове. Видеосъемка свадеб минимум двумя видеооператорами."

But fact is:

"Видеограф на свадьбу в Харькове https://vimeo.com/370007211https://vimeo.com/360133820https://vimeo.com/274075622https://vimeo.com/304032300 Услуги видеосъемки свадеб в Харькове и Харьковской области. Видеограф на свадьбу. Видеосъемка свадеб двумя (и более) операторами. Художественная видеосъемка свадьбы выполняется двумя видеооператорами, так как Свадьба &#8212; это событие, которое не повторяется и мы не хотим упустить важные и ценные для Вас моменты. Съемка производится на камеры: Sony A6400&hellip;"

**Comment by arnaudbroes** [comment]
This is not a support forum, it is a development repository. Support for customers with a valid license for All in One SEO Pack Pro is available here - https://semperplugins.com/contact/

You can follow these steps to check if there's a conflict - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/
