### ISSUE TITLE
The NOINDEX for Tags and Categories does not seem to work

### ISSUE THREAD

**Issue by Davian007** [awesomemotive/all-in-one-seo-pack#3150]
I have the All in One SEO Pack installend on my WP site.
In Noindex settings I see there are lots of boxes that are checked. When I click on the checked boxes, it tuns blue. So I guess that having a box blue is saying "yes, you can NOINDEX this option".

So that is what I did. I clicked on Tags and Categories , but after a few weeks I see that Google has indexed tags, even archives and stuff. 

Did I do something wrong?

**Comment by wpsmort** [comment]
@Davian007 This is not a support forum, this is a development repository.  Pro customers with a valid license key can get support here - https://semperplugins.com/contact/

Users of the free plugin can find documentation here - https://semperplugins.com/documentation/ or get support here - https://wordpress.org/support/plugin/all-in-one-seo-pack/
