### ISSUE TITLE
Stop Sitemap creation

### ISSUE THREAD

**Issue by Fred497** [awesomemotive/all-in-one-seo-pack#3156]
Hello. 

I use All in One SEO Pack for my sitemaps, but it only generates 8 sitemaps. From 29/02 it doesn't generate more sitemaps. Is that a problem?

**Comment by wpsmort** [comment]
@Fred497 This is a development repository. We don't answer support questions here.

Pro customers with a valid license key can get support here - https://semperplugins.com/contact/

Users of the free plugin can find documentation here - https://semperplugins.com/documentation/ or get support here - https://wordpress.org/support/plugin/all-in-one-seo-pack/
