### ISSUE TITLE
Why do I need to specify title tag in a separate place for home page

### ISSUE THREAD

**Issue by nasadowski** [awesomemotive/all-in-one-seo-pack#3157]
I noticed that my home page title is empty despite specifying title and description for the HOME page that is specified for my front page in general settings.

**Comment by wpsmort** [comment]
@nasadowski This is a development repository. We don't answer support questions here.

Pro customers with a valid license key can get support here - https://semperplugins.com/contact/

Users of the free plugin can find documentation here - https://semperplugins.com/documentation/ or get support here - https://wordpress.org/support/plugin/all-in-one-seo-pack/
