### ISSUE TITLE
The Last Change doesn't appear

### ISSUE THREAD

**Issue by Dhanamerdeka** [awesomemotive/all-in-one-seo-pack#3159]
Hello admin...
can you fix the problem that "Last Change" doesn't appear on my sitemap?
https://kurodisk.web.id/sitemap.xml

**Comment by wpsmort** [comment]
Last Change is a required field in an XML Sitemap.  Search engines will reject the sitemap without that field.

**Comment by Dhanamerdeka** [comment]
are u kidding me? you know my problem or no?!
my problem THE LAST CHANGE DOESN'T SHOW THE DATA (BLANK)
Is that bug or what?
the date not show in LAST CHANGE tab

**Comment by arnaudbroes** [comment]
We would have been happy to respond to you if you weren't rude. I'm locking this due to your toxicity.
