### ISSUE TITLE
bug for "Noindex for category" option

### ISSUE THREAD

**Issue by yvano403** [awesomemotive/all-in-one-seo-pack#3160]
Hi there 
seems i have a bug with this option, not selected, but appear in source code :
view-source:https://www.acteurdurable.org/developpement-durable/energies-renouvelables/
<meta name="robots" content="noindex, follow" />
but as you can see on my admin page, this option is not selected
https://prnt.sc/rnbrtm
Could you help me please to resolve that ?
best regards
yvan

**Comment by wpsmort** [comment]
This is a development repository, you cannot access support here.

However, I can tell you that the noindex tag is not coming from our plugin.  It's being output by something else on your site.

**Comment by yvano403** [comment]
yes it comes from allinseo plugin

**Comment by yvano403** [comment]
anyway... where can i talk with someone can help me ?

**Comment by wpsmort** [comment]
All meta tags output by All in One SEO are shown between the HTML lines shown below.  This is not coming from All in One SEO.
