### ISSUE TITLE
Version 3.4.1 upgrade affects Make Theme from Theme Foundry Page Builder

### ISSUE THREAD

**Issue by tonyzeoli** [awesomemotive/all-in-one-seo-pack#3162]
Please fill out this form as completely as possible so that we can help you more quickly.

- [x] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Provide the relevant URL(s) here**

https://netmix.com

**Describe the bug**
What happened?
What did you expect to happen?

When I upgraded to 3.4.1, all my panels for Make theme and its associated Make Plus plugin, which gives you a few more panel options disappeared.

**To Reproduce**

You'd have to install Make and Make Plus or I can give you my user/pass in the Semper Plugins private form to login and view the issue. I have to roll back to the earlier version now, which I don't know how to get.

**Expected behavior**

**Screenshots**

**Version Info (please complete the following information):**
 - WordPress version: 5.3.2 multisite network
 - All in One SEO Pack version: Version 3.4.1
 - PHP version: 7.4

**Additional context**

**Comment by arnaudbroes** [comment]
Hey Tony, thank you for reporting this. Are you seeing any console errors by any chance? In the meanwhile, I've reached out to you by e-mail to get you rolled back to the previous version.

**Comment by wpsmort** [comment]
This was fixed in v3.4.3

**Comment by tonyzeoli** [comment]
Thanks, Steve! Really appreciate it!
