### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by iPSWeb** [awesomemotive/all-in-one-seo-pack#3163]
/sitemap.xml
This page contains the following errors:
error on line 5 at column 6: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.

**Comment by arnaudbroes** [comment]
This is a development repository. We don't answer support questions here.
Pro customers with a valid license key can get support here - https://semperplugins.com/contact/

I'd suggest that you troubleshoot the issue using these steps - https://semperplugins.com/documentation/this-page-contains-the-following-errors/
