### ISSUE TITLE
Issue The date not show the data...

### ISSUE THREAD

**Issue by Dhanamerdeka** [awesomemotive/all-in-one-seo-pack#3164]
Hello can you fix data from the "Sitemap"
my sitemap not show the last change date
https://kurodisk.web.id/sitemap.xml
but the other that use "Yoast SEO" have the date
https://kusonime.com/sitemap_index.xml
can you fix that?

**Comment by arnaudbroes** [comment]
@Dhanamerdeka thank you for reporting this. We're planning on adding the Last Change date to the sitemap root file in the near future. In the meanwhile, please note that the lack of a date there currently does not prevent search engines from crawling your sitemap.

**Comment by Dhanamerdeka** [comment]
yeah i only need that show...
