### ISSUE TITLE
Don't upload a style for users

### ISSUE THREAD

**Issue by webliberty** [awesomemotive/all-in-one-seo-pack#3166]
The style `/wp-content/plugins/all-in-one-seo-pack/css/admin-toolbar-menu.css` is loaded for all users, including the administrator and unregistered users who can't see the admin toolbar in principle.

Please, don't upload this style for unregistered users.

**Comment by arnaudbroes** [comment]
Hey @webliberty,

As I mentioned on the WordPress.org forums, we already have a fix for this, which will be released with the next update. You can't find it here since we're no longer doing any development inside this specific repository. 

- Arnaud
