### ISSUE TITLE
My issue complete but not fix after update 1 april yet?

### ISSUE THREAD

**Issue by Dhanamerdeka** [awesomemotive/all-in-one-seo-pack#3171]
https://github.com/awesomemotive/all-in-one-seo-pack/issues/3164
my problem in root of the sitemap data that "last change" not present in there...
when you guys will fix this :( it's annoying since the tab "last change" present in there but with no data appear

**Comment by arnaudbroes** [comment]
@Dhanamerdeka we're going to add this in a future update. The issue for this feature is located in another repo where we do development.

I'm going to go ahead and close this issue, but please note that we will be adding this. As mentioned before, not having those dates there does not prevent search engines from scanning your sitemap. Also, creating any additionally issues here will unfortunately not speed up the development of this feature.
