### ISSUE TITLE
Can't see Files' editor in all-in-one-seo-pack

### ISSUE THREAD

**Issue by lisaphil** [awesomemotive/all-in-one-seo-pack#3174]
I have activated files' editor in all-in-one-seo-pack but after this it's not shown in sidebar

**Comment by arnaudbroes** [comment]
@lisaphil can you provide us with a screenshot of your Feature Manager menu screen and our admin menu?

**Comment by lisaphil** [comment]
It's in Russian
![image](https://user-images.githubusercontent.com/52919456/83403366-6c56dd80-a3bd-11ea-9bc7-7064afca28b6.png)

![image](https://user-images.githubusercontent.com/52919456/83403427-8abcd900-a3bd-11ea-8690-86e81da9da56.png)

**Comment by wpsmort** [comment]
@lisaphil Please check our documentation on this here - https://semperplugins.com/documentation/the-file-editor-or-robots-txt-modules-are-missing/

Let us know if this does not fix your problem.

**Comment by lisaphil** [comment]
maybe my rights are resticted or I need to update version?

**Comment by wpsmort** [comment]
No, this is usually caused by DISALLOW_FILE_EDIT or DISALLOW_FILE_MODS directives in your wp-config.php file – https://codex.wordpress.org/Editing_wp-config.php#Disable_the_Plugin_and_Theme_Editor

**Comment by lisaphil** [comment]
I have checked my wp-config.php, and there is no mention neither of DISALLOW_FILE_EDIT or DISALLOW_FILE_MODS

**Comment by wpsmort** [comment]
Please send us an Administrator login for your site and FTP login for your server using the secure form here - https://semperplugins.com/contact/support-login-information/
