### ISSUE TITLE
attachment_id links in sitemap not available

### ISSUE THREAD

**Issue by RobertoDonPedro** [awesomemotive/all-in-one-seo-pack#3177]
I have enabled the option `Redirect Attachments to Post Parent`.
Recently I updated to V3.7.1 and the plugin creates links in the sitemap like `/?attachment_id=20` since then. But this link does not exist and Google sends a coverage issue.
The only way to overcome this issue is to completely disable the post type `Media / Attachments` in the sitemap setting, but thats not what I want since I do not want to exclude images from search engines.

**Comment by wpsmort** [comment]
@RobertoDonPedro You wouldn't be excluding images from search, only media attachment pages which are a type of content in WordPress.  Please review this article - https://semperplugins.com/documentation/what-are-media-attachments-and-should-i-submit-them-to-search-engines/
