### ISSUE TITLE
global $post not set in add_meta in aioseop_opengraph.php for single post

### ISSUE THREAD

**Issue by steam0r** [awesomemotive/all-in-one-seo-pack#3178]
Please fill out this form as completely as possible so that we can help you more quickly.

- [x] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Describe the bug**

Maybe due to other plugins interfering i was missing opengraph information on single posts.
After a debugging session i found that `add_meta()` returns in the else branch at line 1289 in
the said file because `$post` is/was NULL.

this caused all the opengraph information not to appear for single posts. i expect these
to appear on pages and posts.

**Version Info (please complete the following information):**
 - WordPress version: 5.5.1
 - All in One SEO Pack version: 3.7.1
 - PHP version: 7.3

**Additional context**

If i added this line at line 1278 (after `global $post...`) everything works as expected:

`if(!is_object($post)) $post = get_queried_object();`

since this is setting/changing the global `$post` (which seems to be the issue somewhere else in the
first place) and a few methods seem to rely on this i could not easily create a pull request.

maybe this small "fix" helps anyhow...

**Comment by wpsmort** [comment]
I'm closing this as this code is being rewritten in the next major release.
