### ISSUE TITLE
Social Meta Module - Scan Social Meta is not pickup up duplicate OG meta

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#318]
When you use the Scan Social Meta feature (http://semperplugins.com/documentation/social-meta-module/#scan_meta), it should detect other Open Graph meta tags in the source code of the site.  However, when you manually paste some Open Graph meta tags into the header.php file in your active theme and click the Scan button, it does not detect these additional tags.

Here are the sample meta tags I'm adding in my theme: 

`<meta property="og:title" content="Facebook Open Graph META Tags"/>`
`<meta property="og:image" content="https://davidwalsh.name/wp-content/themes/klass/img/facebooklogo.png"/>`
`<meta property="og:site_name" content="David Walsh Blog"/>`
`<meta property="og:description" content="Facebook's Open Graph protocol allows for web developers to turn their websites into Facebook "graph" objects, allowing a certain level of customization over how information is carried over from a non-Facebook website to Facebook when a page is 'recommended', 'liked', or just generally shared."/>`

This used to work and has broken some time recently.

**Comment by wpsmort** [comment]
@arnaudbroes: Can you find which version from our version library when this last worked and which version broke this feature.

**Comment by michaeltorbert** [comment]
@arnaudbroes I just wanted to point out that this is for the free version.

**Comment by wpsmort** [comment]
The code is only checking for OG meta that is output through the wp_head() hook.  It does not scan the source code like we first assumed. 

We need to update this check to crawl the source code of the site for the presence of OG meta.
