### ISSUE TITLE
PHP Warning:  file_exists(): open_basedir restriction in effect. 

### ISSUE THREAD

**Issue by jd4u** [awesomemotive/all-in-one-seo-pack#3180]
- [X ] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.

**Describe the bug**
- Lots of PHP Warning file_exists(): open_basedir restriction in effect. 
- menu-header php tries to check the URL of every submenu registered with file_exists. As the Pro Upgrade menu link is directly an Url, the file_exists error is raised.

Solution : The error shall be avoided using javascript based url, instead of direct url. (in other words use onclick instead of href to assign the url for Pro Upgrade link in WordPress Admin Bar SEO Menu.

Log Sample: 
PHP Warning:  file_exists(): open_basedir restriction in effect. File(D:\var\customerdomain\www\public_html/wp-content/plugins/https://semperplugins.com/all-in-one-seo-pack-pro-version/) is not within the allowed path(s): (D:\var\customerdomain\www\) in D:\var\customerdomain\www\public_html\wp-admin\menu-header.php on line 256

**Comment by arnaudbroes** [comment]
Hey @jd4u,

Thank you for reporting this.

We are aware of this issue and believe it should be fixed in the next major version of All in One SEO. I assume you were seeing this issue on Windows Server with an IIS web server?

- Arnaud

**Comment by jd4u** [comment]
> I assume you were seeing this issue on Windows Server with an IIS web server?

Yes.

**Comment by marcverkade** [comment]
Same here, any clue when this is fixed?

**Comment by benjaminprojas** [comment]
@marcverkade based on your screenshot this looks like an issue unrelated to All in One SEO. If you are seeing otherwise, please open a new issue as this one was resolved with a major rewrite of AIOSEO (4.x).
