### ISSUE TITLE
Google Analytics 4 support

### ISSUE THREAD

**Issue by Garconis** [awesomemotive/all-in-one-seo-pack#3181]
Google Analytics is now pushing for new properties to utilize GA4 going forward. It's not the default.

It would be ideal if AIOSEO could somehow support both Universal Analytics and Google Analytics 4 methods.

I realize GA4 is new, and may not have as many integrations/API methods yet, but it would still be nice if it could at least be used for basic GA implementation within your plugin.

**Comment by wpsmort** [comment]
Hi @Garconis,

We don't support GAv4 as it's still considered experimental by Google.

Google's v4 doesn't yet support all of the features of v3 and consequentially doesn't have all of the developer APIs needed for anyone to build on top of yet.

I recommend following the steps in this video to set up a normal web analytics account - https://a.supportally.com/YeX0Nx

**Comment by Garconis** [comment]
But it's not worth keeping a ticket open to begin some form of implementation? As mentioned, GA4 is now the default for new Analytics properties. So you're going to get a lot of users (or users who have clients) that are using GA4 going forward.
