### ISSUE TITLE
aioseo_disable is called too early

### ISSUE THREAD

**Issue by qualmy91** [awesomemotive/all-in-one-seo-pack#3184]
Please fill out this form as completely as possible so that we can help you more quickly.

- [x] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Provide the relevant URL(s) here**
http://localhost/test :stuck_out_tongue_winking_eye:

**Describe the bug**
The filter `aioseo_disable` is called too early to use any logic for disabling aioseo. Since it is called from `after_setup_theme` it is impossible to get any information on the page that is going to be loaded. I would suggest moving `aioseo_disable` inside the function `getTitle` like this:

```
/**
	 * Returns the page title.
	 *
	 * @since 4.0.5
	 *
	 * @param  string $wpTitle   The original page title from WordPress.
	 * @return string $pageTitle The page title.
	 */
	public function getTitle( $wpTitle = '' ) {
        if ( apply_filters( 'aioseo_disable', false ) || apply_filters( 'aioseo_disable_title_rewrites', false ) ) {
            return self::$pageTitle;
        }
		if ( null !== self::$pageTitle ) {
			return self::$pageTitle;
		}
		self::$pageTitle = aioseo()->meta->title->filterPageTitle( $wpTitle );
		return self::$pageTitle;
	}
```

**To Reproduce**
Try to disable AIOSEO on a specific page.

**Expected behavior**
Ability to use logic for applying the filter. 

**Screenshots**

**Version Info (please complete the following information):**
 - WordPress version: 5.6
 - All in One SEO Pack version: 4.0.12
 - PHP version: 7.4.12

**Additional context**

**Comment by arnaudbroes** [comment]
Hey @qualmy91, this is already fixed in the new version that will be going out today! We moved it to `wp` instead of `after_setup_theme`.
