### ISSUE TITLE
G4A Support

### ISSUE THREAD

**Issue by kofdasad** [awesomemotive/all-in-one-seo-pack#3187]
Google sent a message ending support for UA codes…
We are using Seo Pack pro...
it'll support G4A?

**Comment by arnaudbroes** [comment]
@kofdasad Google Analytics support has been deprecated some time ago, so we won't be supporting GA4. We recommend that you switch over to MonsterInsights (https://wordpress.org/plugins/google-analytics-for-wordpress/) or ExactMetrics (https://wordpress.org/plugins/google-analytics-dashboard-for-wp/)
