### ISSUE TITLE
Adjusting Breadcrumbs Font Size

### ISSUE THREAD

**Issue by techpuzzles** [awesomemotive/all-in-one-seo-pack#3188]
Hello,

Thanks for the new breadcrumbs feature. 

Do you know the custom CSS that would allow me to adjust the breadcrumb font size?

It appears to naturally inherit the same font and font size as the single post and I don't see any option to change it from the settings. 

Cordially,
Mathew

**Comment by wpsmort** [comment]
@techpuzzles This CSS works for me:

```
.aioseo-breadcrumbs {
    font-size: 40px;
}
```
