### ISSUE TITLE
Bug: AIOSEO removes the "dashicons" stylesheet from WP frontend

### ISSUE THREAD

**Issue by devAsadNur** [awesomemotive/all-in-one-seo-pack#3196]
AIOSEO: 4.1.4.4
WordPress: 5.8.1

WordPress uses `Dashicons` officially. Some plugins or themes enqueue `dashicons` on the frontend pages. But, if we activate `AIOSEO` it removes the stylesheet. Which results missing `dashicons` icons.

**Comment by benjaminprojas** [comment]
@devAsadNur we cannot reproduce this. Can you share how you are enqueuing the `Dashicons` on the front end in your plugin or theme so we can try and replicate this?

The PR you created (#3197) doesn't seem to get to the root of the problem, but rather just fixes the symptom. We'd rather understand why this is happening in the first place and fix it there.
