### ISSUE TITLE
meta og:site_name generated despite being left blank

### ISSUE THREAD

**Issue by razethion** [awesomemotive/all-in-one-seo-pack#3200]
I noticed a display issue with some platforms that pull both og:site_name and og:title when the WP site title & tagline are left blank. This happens for services like slack & telegram.

![image](https://user-images.githubusercontent.com/34228517/158904323-efec63a7-1df5-4031-9795-bd47d4c43f01.png)

If just the site title is provided, a hyphen is generated and it looks funky. If both site title & tagline are left blank, just a hyphen will be generated. This does not occur when AIOSEO is disabled.

See the source here:
![image](https://user-images.githubusercontent.com/34228517/158904457-bcc9cc26-6e61-4b52-9da7-85fb5faa4772.png)

Ideally this needs it's own control, or should be disabled entirely.

You can also see that despite setting a custom homepage setting:
![image](https://user-images.githubusercontent.com/34228517/158904760-3bd266cb-41af-49a0-8cf2-37c0e25f64b8.png)

It will still display the wordpress configuration:
![image](https://user-images.githubusercontent.com/34228517/158904815-fae2cfd9-a90d-40d0-87bb-044af947a1c5.png)

Also the separator setting here doesn't control the og:site_title separator.

**Comment by razethion** [comment]
Bump.

**Comment by arnaudbroes** [comment]
Hey @razethion,

Our apologies for the delay, we're not that active in this repository.

We actually have a setting for this, but it's a global one that lives outside of the metabox in the post editor.
You can control the Open Graph site name under Social Networks > Facebook > General Facebook Settings > Site Name - https://a.supportally.com/i/2Dqjwf

Let me know if that works! I'll close the issue for now but feel free to reopen it if you're still experiencing any problems.
