### ISSUE TITLE
Call to Undefined Method -  When saving a menu

### ISSUE THREAD

**Issue by colbyalbo** [awesomemotive/all-in-one-seo-pack#3202]
Steps to reproduce:
1) modify the wordpress menu (appearance > menu)
2) attempt to save the menu by clicking save

WordPress version 6.0
Active theme: GeneratePress Child (version 0.1) Current plugin: All in One SEO (version 4.2.1.1) PHP version 7.4.26

Error Details
=============
An error of type E_ERROR was caused in line 243 of the file /wp-content/plugins/all-in-one-seo-pack/app/Common/Sitemap/File.php. Error message: Uncaught Error: Call to undefined method AIOSEO\Plugin\Common\Sitemap\Sitemap::saveXslData() in /wp-content/plugins/all-in-one-seo-pack/app/Common/Sitemap/File.php:243

Stack trace:
#0 /wp-content/plugins/all-in-one-seo-pack/app/Common/Sitemap/File.php(209): AIOSEO\Plugin\Common\Sitemap\File->writeSitemap()
#1 /wp-content/plugins/all-in-one-seo-pack/app/Common/Sitemap/File.php(179): AIOSEO\Plugin\Common\Sitemap\File->writeSitemaps()
#2 /wp-content/plugins/all-in-one-seo-pack/app/Common/Sitemap/Sitemap.php(192): AIOSEO\Plugin\Common\Sitemap\File->generate()
#3 //wp-includes/class-wp-hook.php(309): AIOSEO\Plugin\Common\Sitemap\Sitemap->regenerateStaticSitemap()
#4 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /wp-includes/plugin.php(476): WP_Hook->do_action()
#6/wp-includes/taxonomy.php(3346): do_action()
#7 /wp-includes/nav-menu.php(386): wp_update_term()
#8 /wp-ad

**Comment by arnaudbroes** [comment]
Hey @colbyalbo,

This is already fixed in the next version, 4.2.2, which is going to be released on June 21. If you'd like to get a beta build in the meantime, please feel free to reach out to us via our Basic Question form here  - https://aioseo.com/contact. Our support team will be happy to send it to you.

**Comment by colbyalbo** [comment]
Thanks!
