### ISSUE TITLE
Ping not working

### ISSUE THREAD

**Issue by Tzafra** [awesomemotive/all-in-one-seo-pack#3203]
The ping triggered by the action 'aioseo_sitemap_ping' does not appear to be working. 
In the remote request that pings the search engines, the search engine's own endpoint URL is also urlencoded along with the sitemap URL. 
app/Common/Sitemap/Ping.php
`wp_remote_get( urlencode( $endpoint . $url ) );`
This is resulting in an error response from wp_remote_get() itself, and is not pinging the search engine. 
Should be changed to:
`wp_remote_get( $endpoint . urlencode( $url ) );`

**Comment by arnaudbroes** [comment]
Hey @Tzafra,

Thank you for reporting this. You are totally right.

I'll go ahead and close the issue because I've developed a fix for it. It will be included in our next release, v4.2.3, which will be going out somewhere next month.

Thanks again for brining this to our attention!
