### ISSUE TITLE
Updating link editor modal styles for WordPress 6.1

### ISSUE THREAD

**Issue by sabernhardt** [awesomemotive/all-in-one-seo-pack#3205]
Related: [Core Trac 56956](https://core.trac.wordpress.org/ticket/56956) and [support topic](https://wordpress.org/support/topic/updating-link-editor-modal-styles-for-wp6-1/)

In WordPress 6.1, the link editor modal is taller (600 pixels instead of 500). The 30% `top` value at smaller screen sizes does not work well now, though it apparently was necessary with WP 6.0.

## Steps to replicate

1. Activate Classic Editor (or similar plugin).
2. Open the post editor.
3. If using a desktop browser, shrink the window to less than 782 pixels wide or increase the magnification until the side menu disappears and the admin toolbar only shows icons.
4. Type some text, highlight it and create a link. Click the Link options button (gear icon) to open the link modal.
5. Check the modal's positioning.

## Screenshots in 6.1

The modal is quite low when the viewport is shorter than 620 pixels. When the viewport is 621 to about 1,000 pixels tall, part of the modal can be cut off.

480 × 600
![the top of the modal can be low](https://user-images.githubusercontent.com/17100257/201499452-0eceb066-b6e9-4f67-92f1-ad8151a98ee7.png)

480 × 640
![the top of the modal can be off-screen](https://user-images.githubusercontent.com/17100257/201499453-91fbc8f0-e8b3-4a8c-8399-9fa836bdc7ec.png)

480 × 1000
![the top of the modal can touch the top of the screen](https://user-images.githubusercontent.com/17100257/201499454-df8f0553-6673-4492-985e-88b1a480d479.png)

## CSS to edit

https://github.com/awesomemotive/all-in-one-seo-pack/blob/a7ed9dcb2c34bddecfa406fbb9756bcc8dc8ce47/src/vue/assets/scss/app/link-format.scss#L15-L18

I think changing the selector to `body:not([class*="branch-6-"]) #wp-link-wrap` might be enough. It should apply the `top` property in WordPress versions 6.0 and earlier but not 6.1 (and/or future versions).

**Comment by arnaudbroes** [comment]
Hi @sabernhardt,

Thank you for reporting this issue and providing all those details. I've been able to reproduce this so we'll try to fix this as soon as we can. We'll keep you updated here.

**Comment by arnaudbroes** [comment]
Hey @sabernhardt, we should have completed this a while ago so I'm closing the issue now.
