### ISSUE TITLE
Remove version number from generator meta tag

### ISSUE THREAD

**Issue by andreas-becker** [awesomemotive/all-in-one-seo-pack#3206]
Due to security reasons it is recommended to hide the exact version string of the installed plugin in the generator meta tag.

**Comment by benjaminprojas** [comment]
Hey @andreas-becker we are looking at adding an override in a future version and will keep you posted. Thanks!

**Comment by arnaudbroes** [comment]
Hey @andreas-becker, we added a filter a while back that you can use to hide it if you like - 
`add_filter( 'aioseo_hide_version_number', '__return_true' );`
