### ISSUE TITLE
Person/sameAs invalid type issue

### ISSUE THREAD

**Issue by rsm0128** [awesomemotive/all-in-one-seo-pack#3209]
![image](https://user-images.githubusercontent.com/45686588/235450394-dcb80861-484a-49c0-a7fb-153f30d9cfc0.png)

`sameAs` should be array of string, but it returns an associative array instead.

**Comment by arnaudbroes** [comment]
Hey @rsm0128, thank you for reporting this regression. I'll go ahead and merge your PR since it looks great and make sure this is included in our next update.
