### ISSUE TITLE
Custom Archive and Polylang

### ISSUE THREAD

**Issue by leanca10** [awesomemotive/all-in-one-seo-pack#3211]
I want to translate Custom Archive Descriptions, but Polylang can’t find it. I have to edit the file app/Common/Meta/Description.php and add pll__().

How can this be fixed differently?

`if ( is_post_type_archive() ) {`
`	$postType = get_queried_object();`
`	if ( is_a( $postType, 'WP_Post_Type' ) ) {`
`		$dynamicOptions = aioseo()->dynamicOptions->noConflict();`
`		if ( $dynamicOptions->searchAppearance->archives->has( $postType->name ) ) {`
`			return pll__($this->helpers->prepare( aioseo()->dynamicOptions->searchAppearance->archives->{ $postType->name }->metaDescription ));`
`		}`
`	}`
`}`

**Comment by arnaudbroes** [comment]
Hey @leanca10,

As I mentioned [here](https://wordpress.org/support/topic/custom-archive-and-polylang/) previously, you would be better off reaching out to the support team of Polylang as we unfortunately do not know how their plugin works or is supposed to detect and translate our values.

We are actively tracking the popularity of Polylang among our users and given enough demand, we'll definitely try to integrate further with their plugin at some point. However, right now we don't officially support their plugin.
