### ISSUE TITLE
Please remove "table.wp-list-table .column-name" css rule

### ISSUE THREAD

**Issue by FLUF-Admin** [awesomemotive/all-in-one-seo-pack#3213]
This rule messes up the display of the product name in the wp-admin products list

table.wp-list-table .column-name {
    /* width: auto!important; */
}

<img width="1281" alt="Screenshot 2023-11-13 at 01 16 57" src="https://github.com/awesomemotive/all-in-one-seo-pack/assets/81779163/7c6d452c-8c9c-478a-ab26-648e258076db">

**Comment by arnaudbroes** [comment]
Hey @FLUF-Admin, thank you for your feedback. I've confirmed that CSS rule shouldn't be there so we'll remove it in the next update. I'll close the issue for now but rest assured that it will be fixed in AIOSEO 4.5.1.

**Comment by gosixl** [comment]
Thank you!
