### ISSUE TITLE
Deprecated: Function print_emoji_styles in /wp-admin/index.php?page=aioseo-setup-wizard

### ISSUE THREAD

**Issue by bobbingwide** [awesomemotive/all-in-one-seo-pack#3215]
When visiting my test site to configure AIOSEO ( url `https://cwiccer.local/wp-admin/index.php?page=aioseo-setup-wizard#/smart-recommendations` ) I got the following Deprecated messages.

Deprecated: Function print_emoji_styles is deprecated since version 6.4.0! Use wp_enqueue_emoji_styles instead. in C:\apache\htdocs\cwiccer\wp-includes\functions.php on line 6031

Deprecated: Function wp_admin_bar_header is deprecated since version 6.4.0! Use wp_enqueue_admin_bar_header_styles instead. in C:\apache\htdocs\cwiccer\wp-includes\functions.php on line 6031

Functions attached to admin_print_styles are:
```
70 0 81788928/81788928 256M F=1084 admin_print_styles 
: 0   bw_trace_attached_hooks;9
: 1   wp_resource_hints;1
: 10   print_emoji_styles;1
: 20   print_admin_styles;1
: 50   wp_print_font_faces;1
```

Backtrace
```
0. bw_lazy_backtrace C:\apache\htdocs\wordpress\wp-content\plugins\oik-bwtrace\libs\bwtrace.php:108 0
1. bw_backtrace C:\apache\htdocs\wordpress\wp-content\plugins\oik-bwtrace\includes\bwtrace-actions.php:187 0
2. bw_trace_deprecated_function_run(wp_admin_bar_header,wp_enqueue_admin_bar_header_styles,6.4.0) C:\apache\htdocs\cwiccer\wp-includes\class-wp-hook.php:324 3
3. apply_filters(,array) C:\apache\htdocs\cwiccer\wp-includes\class-wp-hook.php:348 2
4. do_action(array) C:\apache\htdocs\cwiccer\wp-includes\plugin.php:517 1
5. do_action(deprecated_function_run,wp_admin_bar_header,wp_enqueue_admin_bar_header_styles,6.4.0) C:\apache\htdocs\cwiccer\wp-includes\functions.php:5456 4
6. _deprecated_function(wp_admin_bar_header,6.4.0,wp_enqueue_admin_bar_header_styles) C:\apache\htdocs\cwiccer\wp-includes\deprecated.php:5940 3
7. wp_admin_bar_header() C:\apache\htdocs\cwiccer\wp-includes\class-wp-hook.php:324 1
8. apply_filters(null,array) C:\apache\htdocs\cwiccer\wp-includes\class-wp-hook.php:348 2
9. do_action(array) C:\apache\htdocs\cwiccer\wp-includes\plugin.php:517 1
10. do_action(admin_head) C:\apache\htdocs\cwiccer\wp-content\plugins\all-in-one-seo-pack\app\Common\Standalone\SetupWizard.php:178 1
11. setupWizardHeader C:\apache\htdocs\cwiccer\wp-content\plugins\all-in-one-seo-pack\app\Common\Standalone\SetupWizard.php:130 0
12. loadOnboardingWizard C:\apache\htdocs\cwiccer\wp-content\plugins\all-in-one-seo-pack\app\Common\Standalone\SetupWizard.php:118 0
13. maybeLoadOnboardingWizard() C:\apache\htdocs\cwiccer\wp-includes\class-wp-hook.php:324 1
14. apply_filters(null,array) C:\apache\htdocs\cwiccer\wp-includes\class-wp-hook.php:348 2
15. do_action(array) C:\apache\htdocs\cwiccer\wp-includes\plugin.php:517 1
16. do_action(admin_init) C:\apache\htdocs\cwiccer\wp-admin\admin.php:175 1
17. require_once(C:\apache\htdocs\cwiccer\wp-admin\admin.php) C:\apache\htdocs\cwiccer\wp-admin\index.php:10 1
```

### Expected result
No Deprecated messages

### Environment
- WordPress 6.4.1
- all-in-one-seo-pack 4.5.0
- PHP 8.2

### Other notes
- Originally reported in https://github.com/bobbingwide/bobbingwide/issues/112#issuecomment-1817428709
- Similar to https://core.trac.wordpress.org/ticket/59892#ticket
- I appreciate that all-in-one-seo-pack needs to support earlier versions of WordPress than 6.4.0 so can't just change the code to attach different functions to action hooks. 
- I could just set `WP_DEBUG` to `false`, but then I could miss messages from my own logic
- See also https://make.wordpress.org/core/2023/10/17/replacing-hard-coded-style-tags-with-wp_add_inline_style/

**Comment by arnaudbroes** [comment]
Hey @bobbingwide, thank you for reporting this issue. We have already been made aware of it and are currently working on a fix. We'll be including the fix for this in our next update, which should be going out next week.
