### ISSUE TITLE
High number of deprecated notices

### ISSUE THREAD

**Issue by gosixl** [awesomemotive/all-in-one-seo-pack#3217]
- Use of "self" in callables is deprecated in /nas/content/live/yourfluf/wp-content/plugins/aioseo-redirects/app/Utils/WpUri.php on line 145
- preg_match(): Passing null to parameter `#2` `($subject)` of type string is deprecated in /nas/content/live/yourfluf/wp-content/plugins/all-in-one-seo-pack-pro/app/Common/Traits/Helpers/Strings.php on line 478

**Comment by arnaudbroes** [comment]
Hi @gosixl, thanks for reporting these. We hadn't found or received any other reports about these yet. I've already gone ahead and fixed them so they should be resolved in our next update, which is going to be 4.5.4.

**Comment by gosixl** [comment]
Many thanks @arnaudbroes. I think the deprecated notices start around PHP8.2 / 8.3. Unfortunately my host (WPEngine) has forced us to use those versions. Thanks again!
