### ISSUE TITLE
while activating got JS error

### ISSUE THREAD

**Issue by Criss009** [awesomemotive/all-in-one-seo-pack#3220]
Got error like 

There seems to be an issue running JavaScript on your website.
AIOSEO is built with JavaScript to give you the best experience possible.

Help will be appreciated

**Comment by arnaudbroes** [comment]
Hi @Criss009,

Thank you for reaching out. 

Can you please contact our support team via our [free Basic Question form here](https://aioseo.com/contact/)? I will be closing this issue as this is our development repository and not a support forum, but our support team will be happy to assist you through our website.
