### ISSUE TITLE
possible canonical urls issue

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#324]
reported
"The canonical urls works wrong with pagination when simple wp url structure (?p=12345) is on. The canonical url is http://domain.com/page/2 instead of http://domain.com/?paged=2. Paged archives and categories have the same problem.
I think that the problem in All_in_One_SEO_Pack class class in function get_paged (aiseop_class.php:2581). I've tried to change it to "$link = get_pagenum_link($page);" and it works for me."

**Comment by michaeltorbert** [comment]
@wpsmort Are you thinking 2.3.6 for this or later?

**Comment by wpsmort** [comment]
I confirmed this in dev branch.  Here's how the canonical URL currently looks:

First page - link rel="canonical" href="http://aioseop:8888/?p=1171"
Page 2 - link rel="canonical" href="http://aioseop:8888/?p=1171/2
Page 3 - link rel="canonical" href="http://aioseop:8888/?p=1171/3

Here's how it should look:

First page - link rel="canonical" href="http://aioseop:8888/?p=1171"
Page 2 - link rel="canonical" href="http://aioseop:8888/?p=1171&page=2"
Page 3 - link rel="canonical" href="http://aioseop:8888/?p=1171&page=3"

**Comment by michaeltorbert** [comment]
@wpsmort I may have fixed this in the canonical_paged branch.
Canonical URLs needs some work...

**Comment by wpsmort** [comment]
@michaeltorbert I tested this but the format is still the same, see below:

Dev branch format: 
link rel="canonical" href="http://aioseop:8888/?p=1171/2"

Canonical branch format:  
link rel="canonical" href="http://aioseop:8888/?p=1171/2"

**Comment by michaeltorbert** [comment]
I've destroyed the branch... this was the code so far.
https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/a24710b421cd6a7745a7c3648857410f4711934c

**Comment by michaeltorbert** [comment]
This issue may go away once we do #1631

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #861](https://github.com/awesomemotive/aioseop-pro/issues/861) via [**ZenHub**](https://www.zenhub.com/)
