### ISSUE TITLE
Remove aiosp_manage_seo capability

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#363]
Possibly related to #357 and/or #332 

The more I think about it, the more I wonder if we should remove the aiosp_manage_seo capability entirely and change admin menu access back to manage_options or whatever administrator-specific capability. We already have a filter in place for people to change it to some other built-in or custom capability. That would remove any issues we're having with the add capability not firing soon enough on the initial install (which _may_ be fixed now in those two issues anyway, pending testing).

The only negative effect on existing sites we'd have would be if someone is already using the capability for a different role, such as an editor. The non-admin roles would lose access, and the admin would need to use our filter hook in their functions.php.

---

As an added bonus, we should probably have separate capability filters for each menu added (and the edit post metaboxes). If we implement #363, we should make this part a separate issue.

**Comment by michaeltorbert** [comment]
aiosp_manage_seo is in at least the main plugin file, the main class file, module_class, module_manager, aioseop_functions.php, (and deprecated but that likely doesn't matter).
We need to make some or all of these filterable when removing the capability.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #781](https://github.com/awesomemotive/aioseop-pro/issues/781) via [**ZenHub**](https://www.zenhub.com/)
