### ISSUE TITLE
On update, run through and apply any defaults that aren't set

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#364]
If we choose to do this, it could be something we have run every time. We can decide if we want to do this for 2.3.6 or wait.
Related to #332

**Comment by michaeltorbert** [comment]
There's also this https://wordpress.org/support/topic/notice-undefined-index-aiosp_can_set_protocol?replies=29#post-8589589

**Comment by wpsmort** [comment]
This is tested and works fine.

**Comment by michaeltorbert** [comment]
in aioseop_module_class, we are attempting to use defaults in function update_options(). Maybe this only loads defaults if the entire array doesn't exist, not if any individuals don't exist?
Maybe we could go ahead and load the defaults, then do some sort of array merge? perhaps hook into an update hook so it doesn't always fire?

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #841](https://github.com/awesomemotive/aioseop-pro/issues/841) via [**ZenHub**](https://www.zenhub.com/)
