### ISSUE TITLE
Remove Canonical URLs setting

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#374]
Under All in One SEO > General Settings is a checkbox for Canonical URLs.  This option should be removed as a setting.  

We should respect whether this is enabled or disabled and there should be a hook for those who want to disable canonical URLs.

Note: There's some conditional logic here that shows or hides additional options for canonical URLs such as No Pagination, Custom Canonical URLs and Set Protocol.

**Comment by michaeltorbert** [comment]
@wpsmort What do we want to do about the conditionally available settings (other than protocol, which we're removing in #443)?
Should we remove those too and replace them with hooks?

**Comment by contactashish13** [comment]
@wpsmort if the setting is removed, what values should the conditionally available settings take on?

**Comment by wpsmort** [comment]
@contactashish13 We have two issues open for removing those options - #528 and #529.  All three issues should be done together so we can clean up this code.

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1485 takes care of all 3 issues.

As a default, I'm assuming Enable Custom Canonical URLs to be true and No Pagination for Canonical URLs to be false

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #765](https://github.com/awesomemotive/aioseop-pro/issues/765) via [**ZenHub**](https://www.zenhub.com/)
