### ISSUE TITLE
XML Sitemap - Add support for mobile sitemap

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#384]
Jetpack includes the mobile tag in their sitemap to comply with feature phone sitemaps - https://support.google.com/webmasters/answer/6082207?hl=en

This appears in Google Webmaster Tools like this:

<img width="994" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/16632869/4e6cde6a-4394-11e6-89e8-e3396924244b.png">

**Comment by michaeltorbert** [comment]
We need to make sure we make it clear in the UI their mobile sitemap happens, if there are no other indications.

**Comment by contactashish13** [comment]
Interesting discussion here: https://productforums.google.com/forum/#!topic/webmasters/xgwzi09tpFQ/discussion

In today's times when feature phones are almost non existent and most sites are/want to be responsive, is this required?

**Comment by arnaudbroes** [comment]
@contactashish13 that's something that has been outdated for a long time and which we don't want to focus on. Smart devices are all we care about. But indeed, an interesting topic!
