### ISSUE TITLE
Custom canonical URLs don't work on static posts page

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#388]
When you set a custom canonical URL on a static posts page it doesn't appear in the source code.  This was first reported by Geoff Meierhans by email on 07/06/16.

<img width="1016" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/16654663/cb592c9a-4424-11e6-8813-474dd3aeca3d.png">

**Comment by michaeltorbert** [comment]
Looks like if we add the following to the class file around line 3920ish:
`$url = $this->get_paged( trim( $this->internationalize( esc_url( get_post_meta( $post->ID, '_aioseop_custom_link', true ) ) ) ) );`

So it becomes:
```
if ( $aioseop_options['aiosp_can'] ) {
			$url = '';
			if ( ! empty( $aioseop_options['aiosp_customize_canonical_links'] ) && ! empty( $opts['aiosp_custom_link'] ) ) {
				$url = $opts['aiosp_custom_link'];
			}
			$url = $this->get_paged( trim( $this->internationalize( esc_url( get_post_meta( $post->ID, '_aioseop_custom_link', true ) ) ) ) );
```

We'll need to add checks to make sure it's is_home (which is the blog page) and that it's a page, that the page === page_for_posts in the db, and that 'aiosp_custom_link' isset and isn't empty and maybe even that it's a url. I'm pretty sure we have a function already built to determine if it's the page for posts.

Ultimately, as part of a larger project, I'd like to move all the canonical URLs stuff out to its own class-file.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #862](https://github.com/awesomemotive/aioseop-pro/issues/862) via [**ZenHub**](https://www.zenhub.com/)
