### ISSUE TITLE
Social Meta Module - Improve OG image selection 

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#397]
I think, though we should verify this through testing and/or looking at the code, that you can select a global default of how the OG image is selected: default image (pretty much worthless, yet is the default by default), featured image, first attached image, first image in content, image from custom field, post author image, first available image.
I think everything but the default is ignored, if a different image isn't explicitly specified. Even better would be to have these in an order of preference, that can either be changed in the UI (or with a filter).
Something like:
`$og_image_preference_order = array( 'featured image', 'firstattached', 'firstincontent', 'customfield', 'postauthorimage', 'firstavalable'`.

A filter could be used to a) change the order and b) remove things from the array and c) and advanced filter could even make it so that things could be added with a user-supplied function to determine the image.

"First available" essentially does this, but that's not the default. Also, I'm not sure what order that gives. Hopefully it wouldn't start with default_image.

**Comment by wpsmort** [comment]
We discussed this and agreed that we need to not only have a separate way to select the image for Twitter but also need a way for users to set the following for Twitter on a per post basis:

Title
Description
Image
Card Type

For player cards (video) we need the additional fields for:

Player
Player width
Player height
Player stream

See full list of markup tags here - https://dev.twitter.com/cards/markup

Effectively, we need to do what our competitors do and have a separate tab for Facebook and a separate tab for Twitter.  See issue #400

**Comment by michaeltorbert** [comment]
Reported here: https://wordpress.org/support/topic/broken-og-custom-image-does-not-show/

This should be the same issue.
