### ISSUE TITLE
array to string

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#421]
$this->log( "detected output handler $handler" ) in aioseop_class.php on line 3492 may be giving an array to string notice... we may want to check if it's an array first and handle it differently (or we can just wait until we implement our new logging system)

related to #403 (which we can also do)

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #787](https://github.com/awesomemotive/aioseop-pro/issues/787) via [**ZenHub**](https://www.zenhub.com/)
