### ISSUE TITLE
Add local SEO features

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#427]
Add new features for Local SEO. The basic features should include:

1). Output business name, address and phone number in Schema.org markup on a locations page.  
2). Output additional business locations in Schema.org markup on a locations page.
3). Output opening hours in Schema.org markup on a locations page.
4). Display a Google map of each location.
5). Add support for KML files and location information in our XML Sitemap (see http://www.geositemapgenerator.com/ and https://developers.google.com/kml/documentation/kml_tut)

**Comment by wpsmort** [comment]
Requested again by Edward today by email

**Comment by michaeltorbert** [comment]
This should probably be an add-on

**Comment by arnaudbroes** [comment]
This makes SimpleMap more or less redundant, right?

**Comment by michaeltorbert** [comment]
SimpleMap does more than this would, although I'd be fine with phasing it out in favor of this once we get to where we can support add-on plugins.
