### ISSUE TITLE
Importer/Exporter module - Export should exclude Bad Bots log

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#428]
When you export settings and data using the Importer/Exporter module the text from the Bad Bots Blocker log is included, see below:

aiosp_bad_robots_blocked_log = '2016-07-08 21:15:27 Blocked bot with IP ::1 -- matched user agent user agent = Abonti </pre><script>alert(1);</script> found in blocklist.\n'

When you try to import this file it triggers the new security warning because of the <script> tags.

We should not include the Bad Bot Blocker log in the export file.

**Comment by michaeltorbert** [comment]
Off the top of my head, we could either:

1) strip the log from the export
2) strip the log from the import
3) even better, especially for long term would be to stop logging to the db

**Comment by wpsmort** [comment]
See also issue #358

**Comment by michaeltorbert** [comment]
I've added back in the logging of bots, as I think it's pretty important to have an easy way of seeing what has been blocked. 
In #660 we'll move all this to a file.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #911](https://github.com/awesomemotive/aioseop-pro/issues/911) via [**ZenHub**](https://www.zenhub.com/)
