### ISSUE TITLE
Improve logging and add logging levels

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#48]
Have some sort of logging priority from Level 1 - Log Important Things through Level 10 - Log All the Things

**Comment by michaeltorbert** [comment]
This is a new logging system that runs through the WP/PHP error log system.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20logging

aioseop_log( 'This is a sample log entry', 'warning', 7 );

function aioseop_log ( $message = 'unknown message', $type = 'warning', $priority = 5 ){
// process the incoming data
// determine whether it's an array or a string
// what priority are we configured to log? (example: 5 and above)
}

$type could be warning, error, notice, ?...
$priority could be 1-10... and in the settings, someone could choose what priority levels they're interested in logging. For example, >10 = log only the most severe errors, >5 log severe and somewhat important warnings, >=1 = LOG ALL THE THINGS!

**Comment by wpsmort** [comment]
Replaced by #3003
