### ISSUE TITLE
Welcome screen doesn't always appear after updating

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#483]
The Welcome screen introduced in v2.3.9.2 doesn't appear when you update from Dashboard > Updates and sometimes doesn't appear on second click when you update from Plugins.

**Comment by michaeltorbert** [comment]
It only works updating from the plugins screen (one the second click after), and only once unless you clear out the last version option.
It doesn't work on the updates screen for some reason.

I think what we can do is just move the code that calls it from our updates class into the all_in_one_seo_pack.php and early on each wp-admin pageload check to see if it's been displayed for that version, and if not, display it and store into some option key = 'aioseop_welcome' value = '1.2.3(last version shown)' or something.
The code to store it should be in the welcome class itself.

**Comment by wpsmort** [comment]
This should be taken care of in the v4 architecture.
