### ISSUE TITLE
Add support for multiple Google Analytics tracking

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#486]
This was originally requested by https://twitter.com/butchgle on Twitter

You can now have multiple tracking codes on one site: 
https://support.google.com/analytics/answer/1032400?hl=en

We can possibly do this using the current Tracking ID field and allow users to enter multiple UA numbers separated by a comma.  We can then extract out each UA number and display the tracking code.  This could present problems with the advanced options, for example, someone wants to use the e-commerce tracking on one set of tracking code but not the others.

**Comment by michaeltorbert** [comment]
http://www.tjkelly.com/blog/google-analytics-two-tracking-codes-on-same-page-2014/
http://www.lunametrics.com/blog/2009/02/26/pitfalls-tracking-multiple-accounts-ga/
https://www.optimizesmart.com/using-multiple-trackers-for-cross-domain-tracking-in-universal-analytics/

**Comment by michaeltorbert** [comment]
@wpsmort Could in the short term we just apply a filter to this, then officially support it later?

**Comment by wpsmort** [comment]
Yes, we could do this as a filter when we add support for the newer gtag.js tracking code (#2302). 

Here's the docs on how to route to multiple accounts with the gtag.js code - https://developers.google.com/gtagjs/devguide/routing

**Comment by wpsmort** [comment]
Requested again here - https://wordpress.org/support/topic/multiple-ga-ua-ids/
