### ISSUE TITLE
Add breadcrumbs to frontend of sites

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#489]
Feature requested via email:

"Please can you guys add the BREADCRUMB feature in the upcoming version? It will be a great idea. Am currently using another plugin for the breadcrumb in my site"

https://wordpress.org/plugins/breadcrumb-trail/
https://wordpress.org/plugins/breadcrumb-navxt/

Should have the ability to set primary category

**Comment by Baddooking** [comment]
So when are you guys releasing the breadcrumb feature of the AISEO? I'll be glad to know the date :D

**Comment by michaeltorbert** [comment]
@Baddooking We don't have a timeline for this feature at the moment.

**Comment by wpsmort** [comment]
Requested again here https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/integration-of-breadcrumbs/

**Comment by arnaudbroes** [comment]
Requested again by J. Gosset.

**Comment by arnaudbroes** [comment]
This should no longer be pushed back further than 3.4.

**Comment by wpsmort** [comment]
Requested again here - https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/how-can-i-add-breadcrumps-to-my-website/

**Comment by wpsmort** [comment]
Requested again here https://wordpress.org/support/topic/breadcrumbs-100/

**Comment by wpsmort** [comment]
I've added this to our new feature request system.
