### ISSUE TITLE
Bug with title tags when WooCommerce Shop page is front page

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#49]
When you select the WooCommerce Shop page as the home page under Settings, Reading, the Title tag is taken from the latest product, not the Title setting for that page.

**Comment by nishant981** [comment]
we are working on Bug with title tags when WooCommerce Shop page is front page.

**Comment by nishant981** [comment]
Can you please explain little more on this to reproduce the issue because it seems to be working fine at our end. It is using shop page title, Title bar using the title mentioned in the Settings section.
![screenshot_2](https://cloud.githubusercontent.com/assets/13958896/14343617/d88d8dae-fcbf-11e5-8bd2-a8d46b0908ba.png)

**Comment by wpsmort** [comment]
Here's the steps to replicate this bug:

1. Create a page called Home and set it as your front page in Settings > Reading
2. Edit the Home page and set an SEO title in the All in One SEO Pack box
3. Go to All in One SEO > General Settings > Home Page Settings > Use Static Front Page Instead and select Enabled and click Update Options
4. Go to WooCommerce > Settings > Products > Display and set the Home page as the Shop Page 
5. You should now see that the Title tag shows the title of the latest product.

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14355320/7f4a3280-fcae-11e5-9a4f-3a515e1d597d.png)

This bug does not occur if you have Use Static Front Page Instead disabled.

**Comment by amostajo** [comment]
@wpsmort Is this issue still active? I followed the steps described and these are the results for me:
![image](https://user-images.githubusercontent.com/1645908/29236426-9523f6ee-7ec7-11e7-9572-a495a0a84e93.png)

**Comment by wpsmort** [comment]
@amostajo I can still reproduce this although it's a little tricky.  It seems to depend on which WooCommerce product has an SEO title assigned.  I have a local test site where I've reproduced the issue and I can send you a copy of the files and database. 

Please note that this bug is marked for 2.3.17 so we shouldn't worry about it until after all work for v2.3.16 has been completed.

**Comment by Garconis** [comment]
Any word on this? Just stumbled upon this issue. :(

**Comment by wpsmort** [comment]
@Garconis This is currently in development and is slated for the next major release.

**Comment by benjaminprojas** [comment]
Lets see if we can still reproduce

**Comment by wpsmort** [comment]
This is no longer a bug.  It was fixed at some point.
