### ISSUE TITLE
Hide Home Page Settings if Front Page is static page

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#495]
Hide the Home Title, Home Description and Home Keywords fields if the Front Page is set as a static page under Reading Settings.

We can then remove the Use Static Front Page Instead option. 

This is a complex issue because we need to consider users who are using the Home Page Settings section for their homepage SEO.  Can we migrate their title, description and keywords to the fields in the static homepage.

See also issue #515 for the same discussion regarding OG meta.

**Comment by michaeltorbert** [comment]
One option is to do a one-time migration from the homepage settings to the page settings. We'd need to check if we're overwriting anything though. The problem is that we don't know which they intend to use.

We could give first preference to the page settings, then if it's empty, look at the Home Page Settings (which will now be hidden). 

I'm not sure what the best thing to do is.

**Comment by wpsmort** [comment]
If you have set Use Static Front Page Instead to Enabled then AIOSEOP will output the SEO Title and Description entered on the Home page.  This case is fine and should not be affected by any change we make here.

If you have set Use Static Front Page Instead to Disabled then AIOSEOP will output the SEO Title and Description entered under Home Page Settings and will IGNORE anything entered on the Home page.  

In this second case, we will need to copy over what is entered in the Home Page Settings fields to the Home page overwriting anything that was entered there.  This does not change what's displayed in the source code, it only changes what is displayed in the SEO Title and Description fields on the Home page.

**Comment by wpsmort** [comment]
Comment copied over from #1478:

Suggestion to gray out/disable whichever portion isn't in use https://wordpress.org/support/topic/social-image-settings/#post-10613006

**Comment by wpsmort** [comment]
@michaeltorbert Here's my recommendations for action to be taken:

1. If "Your homepage displays" is set to "A static page" then we gray out the "Home Title", "Home Description" and "Home Keywords" fields and we set "Use Static Front Page Instead" to Enabled

2. The customer should be able to change this by toggling "Use Static Front Page Instead" to Disabled if they so wish

3. We update the Help to explain why the fields are grayed out

4. We perform a one-time database migration to copy the contents of the "Home Title", "Home Description" and "Home Keywords" fields to the Title, Description and Keywords fields of the homepage.  If there's anything present in these fields then we overwrite it.  

I realize that overwriting the title and description on the static home page is not ideal because we don't know what the user intended.  However, I believe that we have to preserve what's output in the source code and that would be what's set under Home Page Settings.

If you agree, I'll assign this issue to a dev.

**Comment by michaeltorbert** [comment]
[]We need to make sure to change the documentation as appropriate in both the plugin and on semperplugins.com/documentatin.
[]We also need to mention the changes in our release blog post, and maybe even a post just for this.
[]The changelog should make it very clear what's happening.

**Comment by michaeltorbert** [comment]
When testing, test all scenarios in the spreadsheet.

**Comment by wpsmort** [comment]
I knew I'd seen a theme that interferes with the Settings > Reading option in WordPress.  It was the ProPhoto theme that does it.  See screenshot from a site running ProPhoto:

<img width="702" alt="Screen Shot 2019-03-14 at 5 48 35 PM" src="https://user-images.githubusercontent.com/17548525/54393815-835ac400-4681-11e9-9880-92f2a8be201a.png">

When testing, we'll have to test with this theme as we have a lot of shared users.

**Comment by arnaudbroes** [comment]
This can only be done once we've fixed our known bugs with the home title.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #766](https://github.com/awesomemotive/aioseop-pro/issues/766) via [**ZenHub**](https://www.zenhub.com/)
