### ISSUE TITLE
Add support for Hreflang tags

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#501]
reported here, along with an example of a plugin that does it https://wordpress.org/support/topic/how-add-hreflang-tag-by-using-all-in-one-seo-tool/#post-8185423

@wpsmort Is this something we want to do, and do you have any thoughts on it?

**Comment by wpsmort** [comment]
When we do this we should unhook the hreflang tags output by WPML.  There is a setting to disable this under WPML > Languages > SEO Options.

**Comment by drw285** [comment]
Looks like the recommended plugin for this hreflang-tags-by-dcgws.1.3.6  is outdated, at least if the developer's page http://devoirtechno.net is defunct.
What's the current recommended solution?

**Comment by wpsmort** [comment]
@drw285 It looks like this plugin is still maintained - https://wordpress.org/plugins/hreflang-tags-by-dcgws/

**Comment by wpsmort** [comment]
I've moved this into our new feature request system.
