### ISSUE TITLE
Schema.org - Add other content types

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#507]
We're adding support for articles in issue #73 and for AMP articles in issue #506.  We should discuss whether we want to add the other content types listed here - https://developers.google.com/search/docs/guides/mark-up-content and here - https://developers.google.com/search/docs/guides/search-gallery

We could do something similar to the All In One Schema.org Rich Snippets plugin

**Comment by michaeltorbert** [comment]
cloudways.com/blog/add-schema-to-wordpress-website/

**Comment by luxurypropertyagent** [comment]
Add the following for educational pages (courses), rest consider:
https://developers.google.com/search/docs/data-types/course
https://developers.google.com/search/docs/data-types/social-profile
https://developers.google.com/search/docs/data-types/logo
https://developers.google.com/search/docs/data-types/local-business

**Comment by wpsmort** [comment]
Requested schema for How To articles here - https://wordpress.org/support/topic/how-to-schema-org/

**Comment by wpsmort** [comment]
This is the master issue for adding schema for each of the rich search results detailed here:

https://developers.google.com/search/docs/guides/search-gallery

I'll open a separate issue for each schema type we add in each new release.

**Comment by wpsmort** [comment]
We currently have the following issues open (I'll update this list as the Schema project proceeds):

Issue #506 - Add Schema for AMP scheduled for v3.3
Issue #2813 - Add Schema for breadcrumbs scheduled for v3.4
Pro issue 98 - Add Schema for WooCommerce products scheduled for v3.4
Pro issue 462 - Add Schema for videos scheduled for v3.5

**Comment by wpsmort** [comment]
Closing this as it's been replaced by issues in our Pro repo and in our feature request system.
