### ISSUE TITLE
Social Meta Module: Hide Home Page Settings if Front Page is static page

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#515]
If you set OG Title, OG Description and OG Image under All in One SEO > Social Meta > Home Page Settings and then set them again under the Social Settings tab of your static home page, we always use the OG meta from the Home Page Settings.  

We could add a Use Static Home Page Instead option under Social Meta > Home Page Settings or we could just do what other plugins do and detect from the WordPress settings.

**Comment by wpsmort** [comment]
We should treat this exactly the same way as we treat the Home Page SEO Settings.  See issue #495 which discusses the best way forward.

**Comment by wpsmort** [comment]
Reported here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/facebook-image/#p5886#spEditFormAnchor

**Comment by michaeltorbert** [comment]
What does "detect from the WordPress settings" mean?

**Comment by wpsmort** [comment]
If you have set an OG Title and Description on the Home page it is never used. Only the OG Title and Description set under Home Page Settings is ever used with on exception:

If you check the setting for Use AIOSEO Title and Description then we always use the SEO Title and Description for the Home page which is dependent on the setting for Use Static Front Page Instead (see issue #495).

The OG image that is used is always the image set under Home Page Settings.  We never use the image set on the Home page.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #767](https://github.com/awesomemotive/aioseop-pro/issues/767) via [**ZenHub**](https://www.zenhub.com/)
