### ISSUE TITLE
Remove the No Pagination for Canonical URLs option

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#529]
We should remove this option and replace it with a filter.

We need to respect the default and any user setting.

**Comment by michaeltorbert** [comment]
We need to determine if we want to keep the functionality to disable pagination for canonical urls. Why would someone want this? This would cause the >1 pages to be excluded from Google.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #768](https://github.com/awesomemotive/aioseop-pro/issues/768) via [**ZenHub**](https://www.zenhub.com/)
