### ISSUE TITLE
XML Sitemap - Remove static sitemap option

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#541]

**Comment by michaeltorbert** [comment]
Though we were the _first_ WordPress plugin to have dynamic sitemaps, we're now the **ONLY** plugin still being updated to have static sitemaps. 

The static sitemap functionality is outdated and has a much higher technical burden, especially when dealing with the filesystem. At some point we should remove it entirely. 

We may want to look into caching via transients or something.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #844](https://github.com/awesomemotive/aioseop-pro/issues/844) via [**ZenHub**](https://www.zenhub.com/)
