### ISSUE TITLE
delete_metadata on every page load in admin

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#603]
See if we can optimize this

**Comment by michaeltorbert** [comment]
So far we've removed it from the front-end.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #776](https://github.com/awesomemotive/aioseop-pro/issues/776) via [**ZenHub**](https://www.zenhub.com/)
