### ISSUE TITLE
Use the WordPress Help pull down tab

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#64]
Add additional help/documentation to the WordPress Help pull down tab. Use WooCommerce as an example (see screenshot).

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14157326/867b2a26-f698-11e5-90ef-8d02aec4821f.png)

**Comment by michaeltorbert** [comment]
We could do a couple things:

1) add to the pull-down on our own menus, and
2) add to the pull-down on all areas where we show up (ex: edit post screen)

<img width="1138" alt="screen shot 2017-08-22 at 6 02 13 pm" src="https://user-images.githubusercontent.com/17364998/29589669-1b997b3c-8764-11e7-9950-0540bb368cba.png">
<img width="1112" alt="screen shot 2017-08-22 at 6 01 47 pm" src="https://user-images.githubusercontent.com/17364998/29589671-1b9ab682-8764-11e7-9c13-bca9881d1377.png">
<img width="1122" alt="screen shot 2017-08-22 at 6 01 39 pm" src="https://user-images.githubusercontent.com/17364998/29589670-1b999270-8764-11e7-861c-859832eb36d3.png">

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #830](https://github.com/awesomemotive/aioseop-pro/issues/830) via [**ZenHub**](https://www.zenhub.com/)
