### ISSUE TITLE
Remove bad bot log from options screen

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#659]
We're now logging this to the regular aiosp_log, so we can remove both the option to log blocked bots and the log display.

**Comment by michaeltorbert** [comment]
We'll do this when we do #660

**Comment by wpsmort** [comment]
I'm pushing this back to v3.6 as it is dependent on #660.  In testing I found that we're currently not logging blocked bots to the AIO log file.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #763](https://github.com/awesomemotive/aioseop-pro/issues/763) via [**ZenHub**](https://www.zenhub.com/)
