### ISSUE TITLE
Remove canonical URL for noindexed content

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#661]
We should look into not having a canonical tag on pages with noindex.

Reported here: https://wordpress.org/support/topic/option-to-disable-canonicals-from-noindex-pages/

Source: https://www.seroundtable.com/noindex-canonical-google-18274.html

**Comment by michaeltorbert** [comment]
BTW, in the meantime, code like this would work:

```
add_filter('aioseop_canonical_url','nocanonicalonnoindex', 10, 1);

function nocanonicalonnoindex($url){

	global $post;
	if( get_post_meta($post->ID,'_aioseop_noindex', true)){
			return false;
	}

	return $url;

```

**Comment by mattypants** [comment]
Added the filter to functions.php, but had no effect (I also added the missing closing bracket from the code above).

**Comment by michaeltorbert** [comment]
https://ignitevisibility.com/rel-canonical-and-no-index-no-follow-on-same-page-google-seo/

**Comment by michaeltorbert** [comment]
Suggestion: remove canonical on noindexed pages, unless they've entered a custom canonical URL... and we could also make a filter to disable this.

**Comment by wpsmort** [comment]
Requested again today by Glenn Gabe by email.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #916](https://github.com/awesomemotive/aioseop-pro/issues/916) via [**ZenHub**](https://www.zenhub.com/)
