### ISSUE TITLE
Add option to strip the category base

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#665]
Requested here https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/remove-category-base-is-there-an-option-for-this/

This should be in advanced options.
This should be off by default.
We also need to consider all the times we'd need to flush rewrite rules, such as creating a new category, renaming a category, etc.

Our documentation needs to explain the option, but make it clear that the WordPress rewrite system is complex and it can cause unpredictable results and to only use it if they know what they're doing.

**Comment by mawais999** [comment]
but this is saying only for pro users

**Comment by michaeltorbert** [comment]
@mawais999 This is the free Github repository. Features and code for Pro are in a different repository.

**Comment by wpsmort** [comment]
Requested again here - https://wordpress.org/support/topic/canonical-trouble-for-catagories-without-prefix/

**Comment by wpsmort** [comment]
Requested again today by Sandra.

**Comment by wpsmort** [comment]
See also #3169

**Comment by wpsmort** [comment]
This has been added to our new feature request system.
