### ISSUE TITLE
Improve the behavior of post type selections across the plugin

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#67]
Change the behavior of post type selection throughout the UI to only display checkboxes for post types that are checked under Custom Post Type Settings.  See screenshots.

![changes to custom post type settings section in aioseop v2 3 - 2](https://cloud.githubusercontent.com/assets/17548525/14110126/290c3e26-f593-11e5-9723-92bed2a39939.png)
![changes to custom post type settings section in aioseop v2 3 - 3](https://cloud.githubusercontent.com/assets/17548525/14110125/290847bc-f593-11e5-9303-97e3e29d7fe6.png)
![changes to custom post type settings section in aioseop v2 3 - 4](https://cloud.githubusercontent.com/assets/17548525/14110127/290c751c-f593-11e5-83fd-f30f61d8a345.png)

**Comment by michaeltorbert** [comment]
Comment from other issue:

> Good idea! I might set it so that those options appear but are greyed out, and perhaps a tooltip appears when you hover over them, explaining why they're greyed out.
