### ISSUE TITLE
Improve performance/server status page

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#681]
<img width="590" alt="screen shot 2016-12-07 at 4 49 48 pm" src="https://cloud.githubusercontent.com/assets/17364998/20988254/fc6435cc-bc9d-11e6-8f62-9d4ea94c34a7.png">

**Comment by arnaudbroes** [comment]
We'll discuss https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2375 first.
