### ISSUE TITLE
Long links push description field on Installed Plugin page

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#690]
Paal Joachim Romdahl wrote this to me on 16.12.2016. 

He doesn't like the fact that the links of AIOSEO on the Installed Plugin Page push the description fields to the right.

**correspondence**

Hi Arnaud

Again regarding the long links under installed plugin title line.
Upgrade to Pro I etc etc.

I zoomed out in Chrome to give a higher perspective on the links below the title in the installed screen.
See attachment.

![image](https://cloud.githubusercontent.com/assets/18156697/21270223/f7ead5a4-c3b5-11e6-91de-6b8532586ffb.png)

This is a nuisance that really should be fixed soon. Either by shortening the names or creating a line two below it. Or finding some other good solutions that does not push the Description column further to the right.

Have a great evening!

Paal Joachim

--

**Comment by arnaudbroes** [comment]
Paal sent another e-mail with a suggestion:

![screen shot 2017-02-16 at 15 34 50](https://cloud.githubusercontent.com/assets/18156697/23134746/36499b6e-f796-11e6-9c67-a1aaedb10a9b.png)

**Comment by paaljoachim** [comment]
The other suggestion I have is adding some of the links below the plugin description.

![screen shot 2017-02-16 at 15 34 50](https://cloud.githubusercontent.com/assets/5323259/23341551/ff004442-fc49-11e6-90db-4094228d1af5.png)

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #832](https://github.com/awesomemotive/aioseop-pro/issues/832) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
I've moved this issue over to our new repo for our design team to look at.
