### ISSUE TITLE
XML Sitemap - Include BuddyPress Groups, Members and Activity

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#703]
We should add support for including BuddyPress Groups, Members and Activity in our XML Sitemap.

**Comment by contactashish13** [comment]
Does this pertain to https://wordpress.org/plugins/bbpress/ or https://wordpress.org/plugins/groups-bbpress/ or https://wordpress.org/plugins/groups/?

**Comment by wpsmort** [comment]
@contactashish13 This pertains to https://buddypress.org/.  In BuddyPress you can create Groups, Members and members can create activity.  Let me know if you want me to set up a dummy install of BuddyPress for you to work with.

**Comment by contactashish13** [comment]
@wpsmort that would be very helpful, thanks!

**Comment by wpsmort** [comment]
@contactashish13 I've set you up a demo BuddyPress site and you should have an email inviting you to login as an admin.

I've set up a test group and added you and me as members and I've created some dummy activity.  You'll see Groups and Activity in the WordPress menu and Members are WordPress users with extended profiles.  You can view Groups, Members and Activity here:

http://wordpress-118694-407786.cloudwaysapps.com/groups/test-group/
http://wordpress-118694-407786.cloudwaysapps.com/members/ashish/
http://wordpress-118694-407786.cloudwaysapps.com/members/sfwd/activity/4/

Activity is possibly the only content that we may not be able to add to the XML Sitemap.

**Comment by contactashish13** [comment]
So this is a little confusing. Which of the below do we want to show?

Members, irrespective of groups
OR
Members in a group (iterating over all groups)

Activity stream per group (iterating over all groups)
OR 
Activity stream sitewide
OR 
Activity stream per member (iterating over all members)

**Comment by wpsmort** [comment]
@contactashish13 We'd want all members irrespective of group and all activity sitewide.  

Effectively we'd just be picking up all content by type just like we do with posts, pages and custom post types.

**Comment by wpsmort** [comment]
@contactashish13 This is unrelated to #37.  Issue #37 is for supporting Google AMP pages.  This is for supporting the content types added by BuddyPress.  Let's set up a call to discuss if you're still unsure what's required here.

**Comment by contactashish13** [comment]
@wpsmort Additional sitemaps would not really work properly without my changes in #37. If indexes are on, BuddyPress sitemap would constitute a separate sitemap hence the need to make this a subject of changes in #37. It is unrelated to Google AMP pages but the concept of using additional sitemap remains common. I have 2 options, could you please let me know which would be preferred?

1. Wait till #37 is merged
2. Duplicate changes from #37 here.
