### ISSUE TITLE
Social Meta - Improved BuddyPress support

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#705]
See also #387 

Currently we're using the default og:image for BuddyPress Groups, Members and Activity.  However, the following images are better suited for use as the og:image.

Groups - We could use the Group Cover Image which a Group Admin can set on the Group page
Members - We could use the Member Cover Image or Profile Photo which each member can set on their profile
Activity - We could use the Member Cover Image or Profile Photo for the member posting the activity

The recommended size for the cover images is 605px wide by 225px tall which is close to the recommended size for a Facebook OG image (600px by 315px), whereas the Profile Photo is a square image.

Requested here - https://wordpress.org/support/topic/module-social-meta/

**Comment by michaeltorbert** [comment]
Can this all be done with filters? If so, should this be a paid add-on?
