### ISSUE TITLE
Improved meta support for BuddyPress Activity

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#706]
See also #387

Currently, we output a title tag, OG meta and robots meta tags on Activity but we are missing a meta description. Activity is paginated content that has its own DB table and theme template.  It behaves more like comments. Somehow we are outputting meta to them but we're just not outputting a meta description.  

We should do two things here:

1). Improve the title tag which is always "Activity".  As there's no title and only an Action field and a Content field we could use the Action as the title tag (see screenshot)
2). Use the Content field as the meta description

<img width="1043" alt="screen shot 2017-01-13 at 1 47 09 pm" src="https://cloud.githubusercontent.com/assets/17548525/21941468/dc832018-d996-11e6-81ee-f73d50cdc3e6.png">

Requested here - https://wordpress.org/support/topic/seo-meta-title-for-activity-posts/

**Comment by wpsmort** [comment]
Here's what we currently output:
```
<title>Activity | aioseop</title>
<link rel="author" href="https://plus.google.com/102594674486171076537" />
<meta name="robots" content="noindex,follow" />
<meta property="og:title" content="Activity | aioseop - Part 2" />
<meta property="og:type" content="article" />
<meta property="og:image" content="http://aioseop.dev/wp-content/uploads/2017/05/default-og-image.jpg" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:site_name" content="aioseop" />
<meta property="fb:admins" content="100001245990747" />
<meta property="fb:app_id" content="328808010542949" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="@wpsmort" />
<meta name="twitter:domain" content="aioseop.dev" />
<meta name="twitter:title" content="Activity | aioseop - Part 2" />
<meta name="twitter:image" content="http://aioseop.dev/wp-content/uploads/2017/05/default-og-image.jpg" />
<meta itemprop="image" content="http://aioseop.dev/wp-content/uploads/2017/05/default-og-image.jpg" />
```

**Comment by amostajo** [comment]
@wpsmort There is no individual page for each activity entry...

BuddyPress creates a page called "Activity", here is where you can edit SEO as you would normally do for any page.

So it is a bit confusing what it is requested for this issue.

**Comment by wpsmort** [comment]
@amostajo So there are three things we'd like to achieve here:

1. Improve the title tag that we're outputting for activity
For the title tag, is it possible to include the member name? i.e. Activity by Steve Mortiboy
Is it also possible to include the group name (if the activity is in a group)? i.e. Activity by Steve Mortiboy in Support Group

2. Output a meta description when Autogenerate Descriptions is enabled
3. Output an og:description and twitter:description (Autogenerate OG Descriptions is now enabled by default)

For the descriptions, we can use the Activity Action field, i.e. Steve posted an update in the group Support
We could have a filter hook to use the Activity Content field instead of the Action field, however, some activities don't have content, only an action.

Please let me know what's possible and I can review.

**Comment by amostajo** [comment]
As discussed with @wpsmort, we will extend this issue so activities support full AIOSEOP metabox features.

**Comment by klettersteige** [comment]
is this feature already available. would be great to have editable SEO activities within buddypress. Can you pls. tell me how to use this feature?

**Comment by wpsmort** [comment]
@klettersteige This feature is still in development.  We do not have an estimated release date as yet.

**Comment by klettersteige** [comment]
@wpsmort thank you very much for your quick feedback. I would be happy to use this feature soon!! Happy coding! :-) :+1:
