### ISSUE TITLE
Add inline js and css in aioseop_functions.php to their own file as appropriate

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#718]

**Comment by michaeltorbert** [comment]
We may also want to go through all other files looking for any scripts or styles

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #778](https://github.com/awesomemotive/aioseop-pro/issues/778) via [**ZenHub**](https://www.zenhub.com/)
