### ISSUE TITLE
Social Meta - Add support for OG:locale

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#737]
Requested by José María González by email on 01/29/2016

Consider adding support for og:locale - https://developers.facebook.com/docs/opengraph/guides/internationalization

**Comment by michaeltorbert** [comment]
We should reference https://www.facebook.com/translations/FacebookLocales.xml to make sure things match up with WP locales.

**Comment by michaeltorbert** [comment]
Compatibility with WPML also needs to be considered. For instance, if WPML is installed, would we then use its locale instead of the WP locale?

**Comment by michaeltorbert** [comment]
From the closed dupe:

> Add support for og:locale - https://developers.facebook.com/docs/opengraph/guides/internationalization

We could take the og:locale from the Site Language setting in WordPress and offer a drop down to select a different locale. We could also consider including an advanced option to select multiple locales as og:locale:alternate.

**Comment by wpsmort** [comment]
Requested again today by Matthias acheramann

**Comment by michaeltorbert** [comment]
@arnaudbroes Can you research this to see what various translation (and seo?) plugins are doing to accomodate multi-language sites

**Comment by michaeltorbert** [comment]
We'll also need API filter hooks to a) remove this and b) change it via code. We should have another filter hook to add an array of alternates.
A separate issue should be made for each of these.

**Comment by wpsmort** [comment]
This has been moved to our feature request system.
