### ISSUE TITLE
XML Sitemap - Subdomain sitemaps included in primary site map in WordPress network

### ISSUE THREAD

**Issue by tonyzeoli** [awesomemotive/all-in-one-seo-pack#745]
Not sure if this is a bug or not, but submitted to the forums and Michael suggested I add it here.

I noticed that Google Search Console is citing two errors for URLs linking to compressed sitemaps in a multisite's primary site sitemap.xml file.

See the sitemap.xml file here: https://melibeeglobal.com/sitemap.xml

You can see the the other two sites in the network have compressed site maps included in the primary site map. Is that the correct functionality?

**Comment by wpsmort** [comment]
Reported again here - https://wordpress.org/support/topic/incorrect-sitemap-in-multisite-mode/

I have confirmed this on a multisite that I have access to and it is a bug.  Other sites in the network are being included in the main site XML Sitemap.

**Comment by EkoJr** [comment]
in `All_in_One_SEO_Pack_Sitemap::get_simple_sitemap()` the child URLs are being added

`$child   = $this->get_child_sitemap_urls();`

`$prio  = array_merge( $child, $prio, $prio2, $prio3 );`

**Comment by michaeltorbert** [comment]
@EkoJr Do you want to do this one?

**Comment by michaeltorbert** [comment]
Does this only apply to compression? When/if we get rid of xml sitemap compression will it still be an issue?
Also, does this apply for dynamic sitemaps or just static? Does the issue go away when we get drop support for static sitemaps?
