### ISSUE TITLE
Add better integration for Simple:Press

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#775]
Currently on semperplugins.com/support we can either disable AIO and use the SEO settings in SimplePress to output the title tag but then we don't get a meta description.   SimplePress does output some basic OG meta though.

We should have better integration with SimplePress so that AIO creates better titles and descriptions for forums and topics.

**Comment by michaeltorbert** [comment]
I've ping Steve Klasen to let him know. Until then, it's probably best to just not use AIOSEOP for the forum page.
