### ISSUE TITLE
Social Meta Module breaks Nextgen gallery

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#787]
Reported here: https://wordpress.org/support/topic/confilct-social-meta-and-nextgen/

A user reported that turning on the social meta module with "run shortcodes in description" breaks his nextgen gallery.

I've been unable to reproduce this, but we should try to reproduce it with various other nextgen settings.

**Comment by wpsmort** [comment]
I've also not been able to replicate this problem.  I've reach out to Kiriakos again to see if we can get access to his site.

**Comment by wpsmort** [comment]
@michaeltorbert I have a copy of the site where this is happening installed locally and I am able to reproduce this.  In this instance, the Run Shortcodes In Description option should be disabled because the shortcode for the gallery does not need to run in order for AIOSEOP to generate an OG description.

**Comment by wpsmort** [comment]
This is not a new bug.  We tested back to v2.3.6 and it was broken then.

**Comment by wpsmort** [comment]
I tested further and found that the problem ONLY occurs with shortcodes from NextGen Gallery Pro.

**Comment by wpsmort** [comment]
Update:  In version 2.3.15 we added do_shortcode() to run on all titles and descriptions instead of having the Run shortcodes options which users could enable or disable.  Because we no run shortcodes in titles and content, this user's galleries are broken.

**Comment by wpsmort** [comment]
I'm no longer able to reproduce this and we've had no other reports of this problem so we likely fixed this in a release at some point.
