### ISSUE TITLE
Twitter description character count in multi-byte characters

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#797]
Reported here: https://wordpress.org/support/topic/og-twitterdescription-is-not-automatically-generated-for-post-pages/#post-8882359

> It seems that “Home Description” setting on Social Media has maximum number of characters to be set. When I reduced it to less than 24 multi-byte characters(Japanese), “twitter:description” tag appeared and I passed Twitter Card Validator.

We should see if this is something we can better accommodate.

**Comment by takekasai** [comment]
Hi,
I have just tested only using many single-byte characters on my WP environment. I haven't faced the same issue as I have found the "twitter:description" tag with the many sigle-byte characters normally. So we can say that the issue occurs for only multi-byte characters.

I also tried to figure out what is the real limitation number. The results are a bid weird but as below.
NG (50 characters)
アメリカ生活かさまりブログでは、これからアメリカ生活を始める方向けにこれがあったらよかったという情報
OK (49 characters)
アメリカ生活かさまりブログでは、これからアメリカ生活を始める方向けにこれがあったらよかったという情
NG (47 characters)
アメリカ生活かさまりブログでは、これからアメリカ生活を始める方向けにこれがあったらよかった情報
OK (46 characters)
アメリカ生活かさまりブログでは、これからアメリカ生活を始める方向けにこれがあったらよかった情

Best Regards,

**Comment by wpsmort** [comment]
It appears that we fixed this when we rewrote the character counter code so I'm closing this.
