### ISSUE TITLE
Measure SEO title length by pixels instead of characters

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#800]
Google titles can be up to 600px, not 60 (or 70) characters

seomofo.com/experiments/serp/google-snippet-07.html
searchenginejournal.com/google-titles-and-descriptions-2016/163812/

See if we can do this better.

related to #799 and #1395

**Comment by arnaudbroes** [comment]
Good to know. :-)

**Comment by michaeltorbert** [comment]
1) This may supercede #51 
2) We need to make sure this supports single character (Mandarin, etc) languages.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #919](https://github.com/awesomemotive/aioseop-pro/issues/919) via [**ZenHub**](https://www.zenhub.com/)
