### ISSUE TITLE
i18n - Description for translators

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#803]
We should describe for translators some of the more confusing strings.

It's seen here, but I'm sure a description for translators would be helpful:: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/794/commits/a431a382282a1fbc8f0f96b947f6fd91677384e7

More info: https://codex.wordpress.org/I18n_for_WordPress_Developers#Descriptions

**Comment by michaeltorbert** [comment]
We can add "Front Page Displays" to the list of confusing strings

**Comment by michaeltorbert** [comment]
@arnaudbroes Also, you may want to make a separate issue for each file, and add comments for each string as needed. Err on the side of too many comments.
For strings in an array... we'll have to figure out how to do that, if we can.

**Comment by arnaudbroes** [comment]
Ok, I'm going to create a separate issue for each file and link those issues to this one.
