### ISSUE TITLE
consider using separate arrays for sitemap

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#826]
We should consider using separate arrays (or think of an alternative solution) for the sitemap and the sitemap interface because the current array on line 166 (aioseop_sitemap.php) can't be translated.

It is both used for the update frequency in the sitemap itself and for the interface in WordPress:

foreach ( array( 'always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never' ) as $f ) {

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #785](https://github.com/awesomemotive/aioseop-pro/issues/785) via [**ZenHub**](https://www.zenhub.com/)
