### ISSUE TITLE
Notification Center - XML Sitemap - Add a warning for nginx users to add rewrite rules 

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#827]
![rewrites](https://cloud.githubusercontent.com/assets/17364998/24048579/bdd2cb2e-0aff-11e7-94e7-37fb743be3c4.png)

Requested here: https://wordpress.org/support/topic/sitemap-404-at-nginx/page/2/#post-8926313

**Comment by arnaudbroes** [comment]
Related to #945.

**Comment by EkoJR** [comment]
Should this also be made an admin notice?

**Comment by arnaudbroes** [comment]
@EkoJR that's correct. We added it to 3.2 since you already have plenty of work, but feel free to squeeze it in wherever you like.

**Comment by wpsmort** [comment]
Replaced by #538
