### ISSUE TITLE
Social Meta - Add API Filter Hook for default image

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#836]
Requested here - https://semperplugins.com/support/configuring-all-in-one-seo-pack-pro/social-meta-twitter-settings-chose-image/

We should have a filter where you can set the default for any social media network, not just Twitter.  For example, the filter could be used to set a different default image for any specified social media network.

Note: Twitter uses twitter:image whereas other social media networks use og:image

**Comment by michaeltorbert** [comment]
@wpsmort  Is this something different than "Default OG:Image"?

**Comment by wpsmort** [comment]
@michaeltorbert Yes, the user is asking to be able to set a separate image here.  Currently we use the Default OG Image but this person wants to set a separate default Twitter image.

**Comment by michaeltorbert** [comment]
This should be a setting instead of a filter.

**Comment by michaeltorbert** [comment]
This hook needs an argument to specify the social media site.

**Comment by wpsmort** [comment]
I discussed this with Ben and he's going to look to see if we can detect which social media network is crawling the page and then present the correct default OG image for that social media network.

**Comment by EkoJR** [comment]
This is actually already now possible, but hasn't been completely documented yet. It is related to `aiosp_opengraph_default_image` #2020. You can use the hook and then use `$_SERVER['HTTP_USER_AGENT']` to detect what bot is currently crawling the site.

Should be able to detect which crawler with this method.

```
function prefix_change_og_default_image( $thumbnail ) {
	$_SERVER['HTTP_USER_AGENT'];

	switch ( $_SERVER['HTTP_USER_AGENT'] ) {
		case 'facebookexternalhit' :
		case 'Facebot' :
			// Do URL stuff.
			$thumbnail = 'IMAGE_URL';
			break;
		case 'Googlebot' :
		case 'Googlebot-Image' :
			// Do URL stuff.
			$thumbnail = 'IMAGE_URL';
			break;
		case 'LinkedInBot' :
			// Do URL stuff.
			$thumbnail = 'IMAGE_URL';
			break;

	}

	return $thumbnail;
}
add_filter( 'aiosp_opengraph_default_image', 'prefix_change_og_default_image' );
```

**Comment by tonyzeoli** [comment]
That's very cool! Glad y'all are working on something like this!

**Comment by wpsmort** [comment]
Dupe of https://github.com/awesomemotive/aioseop-pro/issues/780
