### ISSUE TITLE
Maybe remove old legacy options migration code

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#844]
This originated here: https://wordpress.org/support/topic/all-changes-getting-lost-your-database-options-need-to-be-updated-error/
Although it's unclear what is actually causing his issue, and if my recommendation to remove all this code will fix his specific issue.

In aioseop_class.php display_right_sidebar() we have
 if ( ! get_options( 'aioseop_options' ) ) 
which was used ages ago to migrate options of some kind from an old way to a new way.

If caught, it runs inc/aioseop_functions.php aioseop_mrt_mkarry() which seems to migrate a few fields from an old value to a new one. 
These come from aioseop_get_options() and the option "aioseop_options" which doesn't make any sense, because all this only fires if option "aioseop_options" doesn't exist in the first place.

I'd say we should look to see if we need any of the above.
We should check if any of the options being migrated from have existed in a long time. If not, we could probably just remove them. If they exist now or existed recently we can put them in our modern migration class.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #789](https://github.com/awesomemotive/aioseop-pro/issues/789) via [**ZenHub**](https://www.zenhub.com/)
