### ISSUE TITLE
Add better support for modern theme titles with title-tag

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#877]
Currently, I think that if a theme uses title-tag as they should, rather than wp_title, we're still brute-forcing it. We should verify and try to do this more gently.

make.wordpress.org/core/2014/10/29/title-tags-in-4-1/

**Comment by michaeltorbert** [comment]
In testing, it doesn't even look like our OB works for this. Do we have support at all?

**Comment by wpsmort** [comment]
Dupe of https://github.com/awesomemotive/aioseop-pro/issues/52
