### ISSUE TITLE
SEO Data Importer - Add OG data to importer

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#880]
Requested here: https://wordpress.org/support/topic/import-tool-not-working-with-ogimage-from-yoast/

**Comment by michaeltorbert** [comment]
The problem with this is that we don't have a 1:1 relationship here...
Our social meta is serialized and stored in a single field.

**Comment by wpsmort** [comment]
Bumping the priority higher as we'll need this for AM sites.
