### ISSUE TITLE
trouble with get_posts function

### ISSUE THREAD

**Issue by hotelwp** [awesomemotive/all-in-one-seo-pack#881]
Hi,

I am developing a WP theme and ran some testing with All in One SEO Pack. I came across an issue as All in One SEO datas for a page/post where not saved/retrieved properly after editing a post. 

Here is a description of the issue step by step:
- Enter a title in "SEO Title" for a certain page in Pages menu of WP admin
- Click "Edit" to edit the content of the page
- Check the All-in-One SEO section: it contains data that is not related to the post/page being edited, and does not show the "SEO Title" as added
- If clicking on "Update" to save the modifications of the page, then nothing is saved as All in One SEO data. There will be "No title" shown as the value of "SEO Title" for this page on Pages menu.

On debug, I found that the following happens:
- When editing a page, All in One SEO Pack always retrieve the information associated to the latest post called by get_posts (and not the information of the current post being edited).

Here is the piece of code of my theme that contains get_posts WordPress function:
```
$args = array(
'post_type' => $post_type,
'posts_per_page'=> -1,
'suppress_filters' => false,
);
$posts = get_posts( $args );
$post_type_titles = array();
foreach ( $posts as $post ) {
setup_postdata( $post );
$post_type_titles[ $post->ID ] = get_the_title();
}
wp_reset_postdata();
```

I would be interested to understand why All in One SEO plugin conflicts with get_posts function and create that bug. Have you any information on the issue? Any advice?

Best regards,

Aurelien

**Comment by michaeltorbert** [comment]
@hotelwp Please also include a link to download your theme.

**Comment by hotelwp** [comment]
@michaeltorbert I can't link to a download of the theme (it is already for sale) but I can send it as zip file in a private message or to an email address.

**Comment by michaeltorbert** [comment]
@hotelwp That's fine, send it to the email address you have for us.

**Comment by hotelwp** [comment]
@michaeltorbert Just sent

**Comment by michaeltorbert** [comment]
@hotelwp Adding/editing a title or any other AIOSEOP postmeta works fine for me with your theme active. Try these troubleshooting steps: https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/

**Comment by hotelwp** [comment]
@michaeltorbert Thank you for your message. I have just tried again on a fresh install of WordPress with Adomus theme and All-in-one SEO Pack plugin. I still have the same issue. 

Have you tried to add/edit AIOSEOP postmeta on a Page? This is where the problem happen. If you tried on a Post, you will not have seen the issue.

I have again done the debug before replying. In the file wp-content/adomus/admin/sections-meta-fields.php, in the function adomus_get_post_type_titles: if I remove `$posts = get_posts( $args )` and replace it with `$posts = array()`, it works perfectly. 

Best regards,

Aurelien

**Comment by hotelwp** [comment]
@arnaudbroes Any update on the issue? Thank you.

**Comment by arnaudbroes** [comment]
@hotelwp 
Hi Aurelien
I have this on my schedule, and I'm testing this evening whether or not I can reproduce this.
I'll get back to you in a few hours from now.
Arnaud

**Comment by arnaudbroes** [comment]
@hotelwp 
I've tried this with a fresh installation of WordPress, All in One SEO Pack and your WordPress theme, but I wasn't able to reproduce this issue either when creating a few pages and adding meta content (SEO title, description) to them.
Could you please provide me with the exact steps to reproduce this issue, starting from a brand new WordPress installation with the theme installed & activated, and the exact configuration of WordPress, your theme (if applicable) and All in One SEO Pack.
You can also verify what I tried to reproduce this issue by checking out my test site:
http://wordpress-72523-255145.cloudwaysapps.com/wp-admin/
username: aurelien
password: %aKe^9kE4iqUHR%nfRX$mz@J

**Comment by hotelwp** [comment]
@arnaudbroes I would be happy to check on your test site but the user you created for me has subscriber role. So I can't see Pages... ;-)

**Comment by arnaudbroes** [comment]
@hotelwp 
My mistake, assigned it to the wrong user. Changed it to Admin. :-)

**Comment by hotelwp** [comment]
Hi,

Thank you. Good that we can work on same install. I have re-created the issue for you on the test site.

I have added a custom post type (Accommodation->test accommodation). Then I create a new Page (example 3) and you can see that the All in One SEO section (when editing the page example 3) shows the data of the page "test accommodation". 

Come back to Pages list and edit the SEO title (it says No title. I edit to "example 3" and click on the green tick to save. Then click on "Edit" to edit example 3 page. Click Update (you don't need to edit anything). Go back to Pages list and you will see that it says "No title". 

This is why I included the code at first. The function adomus_get_post_type_titles is used to retrieve the titles of certain post types (for example the titles of all testimonials posts). This function include get_posts() WordPress function.

I could narrow the problem down to that point when debugging. I don't know how/why All in One display the data of the last post retrieved by get_posts function.

Hoping it clarifies the issue!

**Comment by arnaudbroes** [comment]
@hotelwp 
Thank you! I indeed saw that there was no title for that post. However, if I try to Edit it, it does show up, even when I refresh the page. Definitely a weird issue. I think I did everything right according to your steps. Could we perhaps arrange a quick Skype call and share your/my screen to go through the steps once more? I'm available this evening or tomorrow afternoon/evening (CET - Brussels).
Skype: arnaudbroes

**Comment by hotelwp** [comment]
Steps by steps with screenshots:

![step 1 and 2](https://cloud.githubusercontent.com/assets/27673460/25495128/6e1d314e-2b7c-11e7-9a96-a03db60e6472.png)

![step 3](https://cloud.githubusercontent.com/assets/27673460/25495140/75c10fb0-2b7c-11e7-9af3-0c554c94c7b9.png)

![before step 4](https://cloud.githubusercontent.com/assets/27673460/25495150/7d3d8bc4-2b7c-11e7-873f-7bd4f99dc3ad.png)

![step 4](https://cloud.githubusercontent.com/assets/27673460/25495158/8377390e-2b7c-11e7-8329-01a78f939272.png)

![step 5](https://cloud.githubusercontent.com/assets/27673460/25495170/8a2fdf76-2b7c-11e7-9383-506126fd8476.png)

![seo title deleted](https://cloud.githubusercontent.com/assets/27673460/25495178/9059815e-2b7c-11e7-96ef-3e7d719bf90f.png)

You should be able to reproduce the issue now. :-)

**Comment by arnaudbroes** [comment]
@hotelwp 
Agreed, I misunderstood something in your previous explanation. 
Patching this through to Michael once more. 
@michaeltorbert 
I tested this on a fresh install while following the exact steps Aurelien specified in his screenshots and I was able to reproduce the issue. Also tested this with older versions with the plugin.

**Comment by hotelwp** [comment]
Hello,

@michaeltorbert : May I check if there is any update on the issue please?

Have a nice week-end!

**Comment by wpsmort** [comment]
I'm closing this as it's very old and we've had no other reports of the conflict.
