### ISSUE TITLE
Social Meta Module - Add support for multiple Open Graph images

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#90]
Users should have the option on the Edit Post / Edit Page screen to add multiple Open Graph images.  This is supported by Facebook as per their documentation here - https://developers.facebook.com/docs/sharing/opengraph/object-properties

Here's a screenshot of how this could appear in the All in One SEO Pack meta box:

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14158864/952b398c-f6a0-11e5-9aaf-178672fd012f.png)

Note that field labels and button text has been changed, and radios have been changed to checkboxes so you can select multiple images.

The Upload Images button should allow you to upload multiple images to use.

**Comment by TrilipuT** [comment]
+1 for this improvement!

**Comment by michaeltorbert** [comment]
As a reminder, if there are multiple images, Facebook wants them on separate lines, along with the dimensions. http://ogp.me/#array
