### ISSUE TITLE
Illegal string offset aiosp_can

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#923]
PHP Notice:  Uninitialized string offset: 0 in all-in-one-seo-pack/aioseop_class.php on line 3613
PHP Warning:  Illegal string offset 'aiosp_can' in all-in-one-seo-pack/aioseop_class.php on line 3613

This may require having a really really old (even <2.0?) version installed, then updating in order to reproduce.

**Comment by michaeltorbert** [comment]
Actually, to reproduce it, it looks like you need to manually delete the options, then when they're created again they aren't fully redone... this isn't much of an issue except it looks like we're not handling no value very well.

**Comment by wpsmort** [comment]
Closing this as we've had no other reports.
