### ISSUE TITLE
XML Sitemap - Ensure compatibility with Polylang plugin

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#941]
This is similar to what we did under #687 for compatibility with WPML.
Reported here - https://wordpress.org/support/topic/how-to-seo-multilingual-website-with-polylang-plugin/

When running Polylang for translating content, the XML Sitemap results in a 404 Page Not Found error for languages other than the default language.

Polylang has four options for handling URL's for translations, these are found under Polylang > Settings > URL Modifications.  We should ensure that the XML Sitemap works for each of these.

For example, if I set this to "The language is set from the directory name in pretty permalinks" then my sitemap should be found under the URL http://domain.com/sitemap.xml for the default language and http://domain.com/fr/sitemap.xml for French language.  However, http://domain.com/fr/sitemap.xml results in a 404 error.

**Comment by Ajilis** [comment]
i hope its the same like my issue:

when we add a new language. SEO pack seems to take the last language and not the default one setup in polylang.
the result is that sitemap.xml is empty.
does google console want an XML for each language or an XML with all ?

**Comment by Ajilis** [comment]
hi,
Do you think this problem should be solved in the 2.3.17 ?

**Comment by Chouby** [comment]
> For example, if I set this to "The language is set from the directory name in pretty permalinks" then my sitemap should be found under the URL http://domain.com/sitemap.xml for the default language and http://domain.com/fr/sitemap.xml for French language.

Not necessarily. It would be acceptable to have all languages in the same sitemap (and to submit only this sitemap to Google). For the compatibility with Yoast SEO, I had to separate sitemaps for subdomains and multiple domains because Yoast did not accept to allow multiple domains in one sitemap. But in all other cases, there is only one sitemap for all languages.

**Comment by contactashish13** [comment]
@arnaudbroes @wpsmort have we concluded on the expected behavior?

**Comment by arnaudbroes** [comment]
@contactashish13 Best to do it like Steve said, multiple sitemaps for each subdomain. But let's check this with @michaeltorbert first.

**Comment by michaeltorbert** [comment]
@wpsmort Is there any authority on this, ie Google documentation?

**Comment by philippea101** [comment]
@michaeltorbert entered a new issue 566 that may be a derivative of this one. In my case I am set up with Polylang in 4 languages in WP multisite ,  with a domain for each language (isails.com, isails.fr, isails.it, and isails.es.)

The site map produced is found only in the isails.com domain, and reflects only isails.com pages.  The other sitemap files  which would be expected at the root of the respective domains (isails.it, etc) are not generated. The issue disappears when the AIOSEO setting that shows the sitemap in the robots.text file is unchecked.

**Comment by wpsmort** [comment]
Google has the following article about this - https://support.google.com/webmasters/answer/189077?hl=en.  This article recommends using one XML Sitemap listing every language variation for each URL.

However, this would only work when submitting each language is in a subdirectory, for example:

http://domain.com/en/
http://domain.com/fr/

This won't work if each language is in a sub domain (http://fr.domain.com/) or on its own domain (http://domain.fr/).  In these cases there will be a sitemap for each language.  

There's a very good article here - https://wplang.org/sitemaps-multiple-languages-wordpress/

It is my recommendation that we implement different sitemaps for each language for now so that we maintain consistency with how we handle sitemaps when using qTranslate or WPML.  

I've created a new issue #2131 to look at implementing the Google recommendations for multi-language sites that use subdirectories.

**Comment by arnaudbroes** [comment]
@wpsmort will talk to @EkoJR about this.

**Comment by wpsmort** [comment]
I discussed this with Ben.  We agreed that he'll look back at the work he did for supporting WPML and then use that as a basis for supporting Polylang.

**Comment by Ajilis** [comment]
actually all-in-one-seo-pack and polylang arent compatible for the sitemap generation EXACT ?

**Comment by arnaudbroes** [comment]
@Ajilis that's what this issue is about.

**Comment by Ajilis** [comment]
Ok the modification should be in "all-in-one-seo-pack" or in "polylang" ?

**Comment by michaeltorbert** [comment]
Just pointing out that according to https://wordpress.org/support/topic/polylang-and-all-in-one-seo-pack-sitemap/ translations work with static, but not dynamic sitemaps.

**Comment by wpsmort** [comment]
This has been moved to our feature request system.
