### ISSUE TITLE
Pro modules should be added via filter

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#947]
1) In aioseop_feature_manager.php line ~63, we have an if (AIOSEOPPRO) which should be replaced by filter hook.

2) Also in all_in_one_seo_pack.php we should do this for line 188/199 $aioseop_module_list

**Comment by contactashish13** [comment]
@michaeltorbert PRs: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1438 and https://github.com/semperfiwebdesign/aioseop-pro/pull/379
