### ISSUE TITLE
Social Meta module - Backslashes are stripped from OG title and description fields

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#950]
Whilst testing #943, I found that when you manually enter a title and description in the OG fields that includes backslashes, the backslashes are stripped from those fields and the meta output in the source code.  See screenshots where I typed the exact same text in the SEO fields and the OG fields:

<img width="846" alt="screen shot 2017-07-06 at 7 03 58 pm" src="https://user-images.githubusercontent.com/17548525/27936277-f09948b4-627d-11e7-8c80-97d3cc7a5e90.png">

<img width="844" alt="screen shot 2017-07-06 at 7 04 08 pm" src="https://user-images.githubusercontent.com/17548525/27936278-f0995598-627d-11e7-857a-972cff9a9cdf.png">

**Comment by michaeltorbert** [comment]
@wpsmort  Is there a reason we want to allow backslashes in any of our fields?

**Comment by wpsmort** [comment]
@michaeltorbert We actually had a user contact us about this around February 29th, 2016 and Dougal worked on a fix for this.  The user wanted to use a description that included this:

Error Can not find script file C:\WINDOWS\Test.vbs

AIOSEOP was stripping the backslashes and I believe we fixed that in v2.3

**Comment by wpsmort** [comment]
@michaeltorbert I've tested this and can confirm that the bug only exists when you manually enter an OG Title and/or OG Description.  This does not affect SEO titles/descriptions and it does not affect autogenerated SEO/OG titles and descriptions.

To reproduce this, edit a post and enter a title and description in the Social Settings tab that has backslashes.  The backslashes will be stripped when you save the post and go back to the Social Settings tab and they'll also be stripped from the meta tags in the source code.

We originally had this working in v2.3 but it has since broken.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #887](https://github.com/awesomemotive/aioseop-pro/issues/887) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #888](https://github.com/awesomemotive/aioseop-pro/issues/888) via [**ZenHub**](https://www.zenhub.com/)
