### ISSUE TITLE
Social Meta Module - OG meta is not being output on post type archive pages

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#96]
The post type archive page, when not set as the homepage, shows either no Open Graph meta or the Open Graph meta from the first post.

Tested with WooCommerce Shop page.

**Comment by michaeltorbert** [comment]
@wpsmort  Is this related to #154 and/or https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/custom-post-type-meta/ ?

**Comment by wpsmort** [comment]
@michaeltorbert: Yes this is somewhat related.  There are two separate issues here:

1.  We currently have no support for custom post type archives.  This is addressed in #154 and is a more complex issue given that custom post type archives are dynamically generated and don't have a static page where you can control SEO/OG meta.  This is probably a situation where we need a filter hook.

2.  We do have support for custom post type archives where there is a page for that archive.  The WooCommerce Shop page is the best example.  You can set your SEO meta on the Shop page and it is output just fine.  However, nothing is output for OG meta.  This is an omission on our part and this issue addresses this bug.

**Comment by michaeltorbert** [comment]
@wpsmort Where should this pull from? Do we want a generic template for this, or should it be specific to the CPT?

**Comment by michaeltorbert** [comment]
@wpsmort Once we've reorganized things a bit, and have options in tabs... maybe the way to go is to dynamically create an option template in the settings for "x CPT archive format" for any existing CPTs.
In the meantime, we could just make a generic "custom post type archive format" setting.

**Comment by wpsmort** [comment]
Reported again here - https://wordpress.org/support/topic/og-image-not-workingoverriding-on-shop-page/

**Comment by wpsmort** [comment]
Reported again here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/all-pages-working-except-shop-blog/

**Comment by wpsmort** [comment]
This also affects the Blog page when you set Front page displays - A static page and you set a Posts page.

If you don't set any SEO or OG meta on the Blog page, then we don't output any OG meta at all.

**Comment by wpsmort** [comment]
Reported again here - https://wordpress.org/support/topic/woocommerce-shop-page-og/

**Comment by wpsmort** [comment]
@michaeltorbert I think for now we should just have a generic template.  If it's possible to support CPT archives that have a static page, i.e. WooCommerce Shop page, and have the OG meta be taken from the page if set then would be ideal.  Otherwise we just fall back to a generic template.

**Comment by wpsmort** [comment]
Moved to Pro repo
