### ISSUE TITLE
New Feature - Notification Center 

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#998]
something similar to what wordfence does...

**Comment by EkoJr** [comment]
Something similar to this; sort of like an announcement list?

![dashboard notifications](https://user-images.githubusercontent.com/2794445/28749527-756c5a6e-747f-11e7-9022-4de7a83cfbb9.png)

**Comment by michaeltorbert** [comment]
We should have once notification center... with notices, problems, etc...
We can color coordinate them by what type they are (we should discuss this).
Users should be able to mute notifications. They shouldn't go away completely, there should be a toggle to show them.

**Comment by michaeltorbert** [comment]
Eventually this will go on our new AIOSEOP dashboard (to replace the General Settings primary options page).
